<?php
$form = $this->configurationsForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            GESTIONE SOGLIE ALLARME
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <?= $this->form()->openTag($form); ?>

                    <?php  $configurations = $form->get('configurations');
                    foreach($configurations as $config): ?>
                        <fieldset style="margin-bottom: 30px;">
                            <label><?= ucfirst($config->get('configKey')->getValue()); ?></label>
                            <?= $this->formRow($config->get('id')); ?>
                            <?= $this->formRow($config->get('configValue')); ?>
                        </fieldset>
                    <?php endforeach; ?>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success">Salva</button>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
