<?php
$form = $this->userForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    AGGIUNGI UTENTE
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('users'); ?>" class="btn btn-success pull-right">
                    <i class="fa fa-arrow-left"></i> Torna Indietro
                </a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Dati Utente</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->form()->openTag($form); ?>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="displayName">Nome & Cognome</label>
                                        <?php
                                        $displayName = $form->get('user')->get('displayName');
                                        echo $this->formElement($displayName);
                                        echo $this->formElementErrors($displayName, array('class' => 'text-danger list-unstyled'));
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <?php
                                        $email = $form->get('user')->get('email');
                                        echo $this->formElement($email);
                                        echo $this->formElementErrors($email, array('class' => 'text-danger list-unstyled'));
                                        ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="email">Ripeti Email</label>
                                        <?php
                                        $email2 = $form->get('user')->get('email2');
                                        echo $this->formElement($email2);
                                        echo $this->formElementErrors($email2, array('class' => 'text-danger list-unstyled'));
                                        ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <?php
                                        $password= $form->get('user')->get('password');
                                        echo $this->formElement($password);
                                        echo $this->formElementErrors($password, array('class' => 'text-danger list-unstyled'));
                                        ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="password">Ripeti Password</label>
                                        <?php
                                        $password2= $form->get('user')->get('password2');
                                        echo $this->formElement($password2);
                                        echo $this->formElementErrors($password2, array('class' => 'text-danger list-unstyled'));
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-success">Crea Utente</button>
                                </div>
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>