<?php
$form = $this->userForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    AGGIUNGI UTENTE
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('users'); ?>" class="btn btn-success pull-right">
                    <i class="fa fa-arrow-left"></i> Torna Indietro
                </a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Dati Utente</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->form()->openTag($form); ?>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <?= $this->formRow($form->get('user')->get('username')); ?>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="displayName">Nome & Cognome</label>
                                        <?= $this->formRow($form->get('user')->get('displayName')); ?>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="state">Stato</label>
                                        <?= $this->formRow($form->get('user')->get('state')); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <?= $this->formRow($form->get('user')->get('email')); ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="email">Ripeti Email</label>
                                        <?= $this->formRow($form->get('user')->get('email2')); ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <?= $this->formRow($form->get('user')->get('password')); ?>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label for="password">Ripeti Password</label>
                                        <?= $this->formRow($form->get('user')->get('password2')); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-success">Crea Utente</button>
                                </div>
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>