<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    AGGIUNGI UTENTE
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('users'); ?>" class="btn btn-success pull-right">
                    <i class="fa fa-arrow-left"></i> Torna Indietro
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">


            </div>
        </div>
    </div>
</div>