<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    ELENCO UTENTI
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('users/add'); ?>" class="btn btn-success pull-right">
                    <i class="fa fa-user-plus"></i> Nuovo Utente
                </a>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-users"></i>Totale utenti <?= count($this->users); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-customers-table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome & Cognome</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            /** @var \ZfcUserDoctrineORM\Entity\User $I_user */
                            foreach($this->users as $I_user): ?>
                            <tr>
                                <td><?= $I_user->getId(); ?></td>
                                <td><?= $I_user->getDisplayName(); ?></td>
                                <td><?= $I_user->getEmail(); ?></td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>