<?php
    $this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
    $this->headScript()
        ->appendFile('/js/datatables/media/js/jquery.dataTables.js')
        ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
        ->appendFile($this->basePath() .'/js/users.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO UTENTI"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>
        <div class="page-bar">
        </div>
         <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.id"><?= $this->translate("Id"); ?></option>
                                    <option value="e.email"><?= $this->translate("eMail"); ?></option>
                                    <option value="e.displayName"><?=  $this->translate("Nome e Cognome"); ?></option>
                                    <option value="e.role"><?= $this->translate("Ruolo"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                         <a href="<?= $this->url('users/add'); ?>" class="btn btn-success pull-right">
                            <i class="fa fa-plus"></i> <?= $this->translate("Aggiungi Utente"); ?>
                        </a>
                    </div>
                </div>
                <hr>
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-users"></i><?= $this->translate("Totale utenti"); ?> <span id="total-users"></span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-users-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Id"); ?></th>
                                <th><?= $this->translate("Nome e Cognome"); ?></th>
                                <th><?= $this->translate("Email"); ?></th>
                                <th><?= $this->translate("Ruolo"); ?></th>
                                <th><?= $this->translate("Azione"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>