<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    <?= $this->translate("ELENCO UTENTI"); ?>
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('users/add'); ?>" class="btn btn-success pull-right">
                    <i class="fa fa-user-plus"></i> <?= $this->translate("Nuovo Utente"); ?>
                </a>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-users"></i><?= $this->translate("Totale utenti"); ?> <?= count($this->users); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-customers-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Id"); ?></th>
                                <th><?= $this->translate("Nome & Cognome"); ?></th>
                                <th><?= $this->translate("Email"); ?></th>
                                <th><?= $this->translate("Ruolo"); ?></th>
                                <th><?= $this->translate("Azione"); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            /** @var \SharengoCore\Entity\Webuser $I_user */
                            foreach($this->users as $I_user): ?>
                            <tr>
                                <td><?= $I_user->getId(); ?></td>
                                <td><?= $I_user->getDisplayName(); ?></td>
                                <td><?= $I_user->getEmail(); ?></td>
                                <td><?= $I_user->getRole(); ?></td>
                                <td><a href="<?= $this->url('users/edit', ['id' => $I_user->getId()]); ?>" class="btn btn-sm btn-success"><?= $this->translate("Modifica"); ?></a> </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>