<?php

use SharengoCore\Entity\CustomerDeactivation;

$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
$form->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formDriver->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formSetting->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));


?>
<div class="row">

    <div class="col-lg-12">
    <?= $this->partial('partials/flash-messages.phtml', []); ?>
    </div>

    <div class="col-lg-9">

        <!-- BEGIN Customer details -->
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Anagrafica"); ?></div>
            <div class="panel-body">

                <?= $this->form()->openTag($form); ?>
                    <input type="hidden" name="type" value="customer">

                    <div class="row">
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="id"><?= $this->translate("Id"); ?></label>
                                <?php $idElement = $form->get('customer')->get('id');
                                $idElement->setAttributes(['type'=>'text','readonly'=>'true','class'=>'form-control']);
                                ?>
                                <?= $this->formRow($idElement); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Titolo"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('gender')->setAttribute('disabled', 'true')); ?>
                                <input type="hidden" id="gender" name="customer[gender]" value="<?= $customer->getGender() ?>">
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Nome"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Cognome"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Email"); ?></label>
                                <?php if ($this->isAllowed('customer', 'changeEmail')) {
                                    echo $this->formRow($form->get('customer')->get('email'));
                                } else {
                                    echo $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'readonly'));
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <b><?= $this->translate("Dati di nascita"); ?></b>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Nazione"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthCountry')->setAttribute('disabled', 'true')); ?>
                                <input type="hidden" id="birthCountry" name="customer[birthCountry]" value="<?= $customer->getBirthCountry() ?>">
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Provincia"); ?></label>
                                <?
                                if($customer->getBirthCountry()==='it') {
                                    echo $this->formRow($form->get('customer')->get('birthProvince')->setAttribute('disabled', 'true'));
                                    echo '<input type="hidden" id="birthProvince" name="customer[birthProvince]" value="'.$customer->getBirthProvince().'">';
                                } else {
                                    echo '<input type="text" class="form-control" id="birthProvince" name="customer[birthProvince]" value="'.$customer->getBirthProvince().'" readonly="readonly">';
                                }
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Comune"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthTown')->setAttribute('disabled', 'true')); ?>
                                <input type="hidden" id="birthTown" name="customer[birthTown]" value="<?= $customer->getBirthTown() ?>">
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Data di nascita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthDate')->setAttribute('disabled', 'true')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <b><?= $this->translate("Residenza"); ?></b>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Nazione"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('country')); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Provincia"); ?></label>
                                <?

                                echo $this->formRow($form->get('customer')->get('province'));

//                                $province2 = $form->get('customer')->get('province');
//                                $input = '<input name="' . $province2->getName() . '" ';
//                                foreach ($province2->getAttributes() as $attribute => $value) {
//                                    $input .= $attribute . '="'.$value .'" ';
//                                }
//                                $input .= ' style="display: none;" value="' . $province2->getValue() . '" disabled></ipnut>';

                                $input = sprintf('<input name="customer[province]" type="text" id="province" class="form-control" required="required" style="display: none;" value="%s" disabled aria-required="true">',
                                    $customer->getProvince());
                                echo $input;
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Città"); ?></label>
                                <?
                                $town = $form->get('customer')->get('town');
                                $select = '<select name="' . $town->getName() . '" ';
                                foreach ($town->getAttributes() as $attribute => $value) {
                                    $select .= $attribute . '="' . $value . '" ';
                                }

                                $select .= '>';
                                if(is_null($customer->getTown())) {
                                    $select .= '<option></option>';
                                } else {
                                    $select .= $attribute . '="' . $customer->getTown() . '">';
                                    $select .= '<option value="' . $customer->getTown() . '">' . $customer->getTown() . '</option>';
                                }
                                $select .= '</select>';
                                echo $select;

                                $town2 = $form->get('customer')->get('town');
                                $input = '<input name="' . $town2->getName() . '" ';
                                foreach ($town2->getAttributes() as $attribute => $value) {
                                    $input .= $attribute . '="'.$value .'" ';
                                }
                                $input .= ' style="display: none;" value="' . $town2->getValue() . '" disabled></ipnut>';
                                echo $input;
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Via e numero civico"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('address')); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("CAP"); ?></label>
                                <?
                                $zipCode = $form->get('customer')->get('zipCode');
                                $select = '<select name="' . $zipCode->getName() . '" ';
                                foreach ($zipCode->getAttributes() as $attribute => $value) {
                                    $select .= $attribute . '="' . $value . '" ';
                                }
                                $select .= '>';
                                if(is_null($customer->getZipCode())) {

                                } else {
                                    $select .= $attribute . '="' . $customer->getZipCode() . '">';
                                    $select .= '<option value="' . $customer->getZipCode() . '">' . $customer->getZipCode() . '</option>';
                                }
                                $select .= '<option value="00000" >00000</option></select>';
                                echo $select;

                                $zipCode2 = $form->get('customer')->get('zipCode');
                                $input = '<input name="' . $zipCode2->getName() . '" ';
                                foreach ($zipCode2->getAttributes() as $attribute => $value) {
                                    $input .= $attribute . '="'.$value .'" ';
                                }
                                $input .= ' style="display: none;" value="' . $zipCode2->getValue() . '" disabled></ipnut>';
                                echo $input;

                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <b><?= $this->translate("Dati Fiscali"); ?></b>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="taxCode"><?= $this->translate("Codice fiscale"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="vat"><?= $this->translate("Partita IVA (opzionale)"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('vat')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Cod. destinatario"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('recipientCode')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("PEC"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('cem')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2">
                            <b><?= $this->translate("Contatti"); ?></b>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="mobile"><?= $this->translate("Cellulare"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('mobile')); ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="phone"><?= $this->translate("Telefono"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('phone')); ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="phone"><?= $this->translate("Lingua preferita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('language')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati Anagrafici"); ?></button>
                        </div>
                    </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
        <!-- END Customer details -->

        <!-- BEGIN Driver's license details -->
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Dati Patente"); ?></div>
            <div class="panel-body">

                <?= $this->form()->openTag($formDriver); ?>
                    <input type="hidden" name="type" value="driver">

                    <div class="row">
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="driverLicenseCountry"><?= $this->translate("Nazione"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="driverLicense"><?= $this->translate("Patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicense')); ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="driverLicenseName"><?= $this->translate("Nome sulla patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')); ?>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label for="driverLicenseName"><?= $this->translate("Cognome sulla patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseSurname')); ?>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label for="driverLicenseExpire"><?= $this->translate("Scadenza"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati Patente"); ?></button>
                        </div>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
        <!-- END Driver's license details -->
    </div>

    <div class="col-lg-3">

        <?= $this->form()->openTag($formSetting); ?>
        <input type="hidden" name="type" value="setting">

        <!-- BEGIN Other details -->
        <div class="panel panel-default">

            <div class="panel-heading"><?= $this->translate("Altri dati"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Stato Iscrizione"); ?></label>
                            <?= $this->formRow($formSetting->get('setting')->get('registrationCompleted'));?>
                        </div>
                    </div>
                </div>


                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Percentuale Sconto"); ?></label>
                                <?= $this->formRow(is_null($formSetting->get('setting')->get('discountRate')) ? '0' : $formSetting->get('setting')->get('discountRate'));                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="goldList"><?= $this->translate("Maintainer"); ?></label>
                                <?php
                                    if($this->isAllowed('customer', 'maintainer')) {
                                        echo $this->formRow($formSetting->get('setting')->get('maintainer'));
                                    } else {
                                        echo $this->formRow($formSetting->get('setting')->get('maintainer')->setAttribute('disabled', 'true'));
                                    }
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="goldList"><?= $this->translate("Gold List"); ?></label>
                                <?php
                                if ($this->isAllowed('customer', 'goldList')) {
                                    echo $this->formRow($formSetting->get('setting')->get('goldList'));
                                } else {
                                    echo $this->formRow($formSetting->get('setting')->get('goldList')->setAttribute('disabled', 'true'));
                                }
                                ?>
                            </div>
                        </div>
                    </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="silverList"><?= $this->translate("Silver List"); ?></label>
                            <?php
                            if ($this->isAllowed('customer', 'silverList')) {
                                echo $this->formRow($formSetting->get('setting')->get('silverList'));
                            } else {
                                echo $this->formRow($formSetting->get('setting')->get('silverList')->setAttribute('disabled', 'true'));
                            }
                            ?>
                        </div>
                    </div>
                </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="firstPaymentCompleted"><?= $this->translate("First Payment Completed"); ?></label>
                                <?php
                                if ($this->isAllowed('customer', 'firstPaymentCompleted')) {
                                    if($customer->getRegistrationCompleted()){
                                        echo $this->formRow($formSetting->get('setting')->get('firstPaymentCompleted'));
                                    }else{
                                        echo $this->formRow($formSetting->get('setting')->get('firstPaymentCompleted')->setAttribute('disabled', 'true'));
                                    }
                                } else {
                                    echo $this->formRow($formSetting->get('setting')->get('firstPaymentCompleted')->setAttribute('disabled', 'true'));
                                }
                                ?>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati"); ?></button>
                        </div>
                    </div>

            </div>

        </div>
        <!-- END Other details -->
        <?= $this->form()->closeTag(); ?>

        <!-- BEGIN Customer activation/deactivation -->
        <?php
            $isEnabled = $customer->getEnabled();
            $deactivations = $this->deactivations;
            $isManuallyDisabled = false;
        ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Abilitazione"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <label class="sng-margin-top"><?= $this->translate("Stato:"); ?></label>
                        <label class="sng-info-box sng-move-right"><?= $isEnabled ? $this->translate('Abilitato') : $this->translate('Disabilitato');?></label>
                    </div>
                </div>

                <?php if (!$isEnabled): ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <label><?= $this->translate("Motivi:"); ?></label>
                    </div>
                </div>

                <?php foreach ($deactivations as $deactivation): ?>

                <div class="row sng-margin-bottom">
                    <div class="col-lg-12">
                        <label class="sng-info-box sng-full-width">
                            <?php if ($deactivation->isGeneratedAutomatically()): ?>
                            <i class="fa fa-info-circle" title="<?= $this->translate("Generata automaticamente, alcuni dati potrebbero non essere corretti"); ?>"></i>
                            <?php endif; ?>
                            <a class="sng-move-right sng-margin-left"
                                href="<?= $this->url(
                                    'customers/edit-deactivation',
                                    ['id' => $this->customer->getId()],
                                    ['query' => ['deactivationId' => $deactivation->getId()]]
                                ); ?>"
                                onclick="removeDeactivation(event)">
                                <i class="fa fa-trash"></i>
                            </a>
                            <?= $deactivation->getReasonTranslated(); ?>
                        </label>
                    </div>
                </div>

                <?php
                    $isManuallyDisabled = $isManuallyDisabled || $deactivation->getReason() == CustomerDeactivation::DISABLED_BY_WEBUSER;
                ?>

                <?php endforeach; ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <form class="portlet-body"
                            action="<?= $this->url('customers/reactivate', ['id' => $this->customer->getId()]); ?>"
                            method="post">
                            <input id="js-reactivate"
                                class="btn btn-success"
                                type="submit"
                                onclick="reactivate(event)"
                                value="<?= $this->translate("Riabilita"); ?>">
                            </input>
                        </form>
                    </div>
                </div>

                <?php endif; ?>

                <?php if (!$isManuallyDisabled): ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <form class="portlet-body"
                            action="<?= $this->url('customers/deactivate', ['id' => $this->customer->getId()]); ?>"
                            method="post">
                            <input id="js-reactivate"
                                class="btn btn-success"
                                type="submit"
                                onclick="deactivate(event)"
                                value="<?= $this->translate("Disabilita manualmente"); ?>">
                            </input>
                        </form>
                    </div>
                </div>

                <?php endif; ?>

            </div>
        </div>
        <!-- END Customer activation/deactivation -->
        <?php if (strpos($customer->getEmail(), '_deactivated@') === false && $webuserRole != 'callcenter') { ?>
            <div class="panel panel-default">
                <div class="panel-heading"><?= $this->translate("Recesso"); ?></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <button onclick="customerRecess()" class="btn btn-success"><?= $this->translate('Conferma recessione cliente'); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customers-edit.js?ver=1'; ?>"></script>
