<?php

use SharengoCore\Entity\CustomerDeactivation;

$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
$form->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formDriver->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formSetting->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
?>
<div class="row">

    <div class="col-lg-12">
    <?= $this->partial('partials/flash-messages.phtml', []); ?>
    </div>

    <div class="col-lg-9">

        <!-- BEGIN Customer details -->
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Anagrafica"); ?></div>
            <div class="panel-body">

                <?= $this->form()->openTag($form); ?>
                    <input type="hidden" name="type" value="customer">

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Titolo"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('gender')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Nome"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Cognome"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Email"); ?></label>
                                <?php if ($this->isAllowed('customer', 'changeEmail')) {
                                    echo $this->formRow($form->get('customer')->get('email'));
                                } else {
                                    echo $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'readonly'));
                                }
                                ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Data di nascita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthDate')->setAttributes(['readonly'=> 'true', 'class' => 'form-control'])); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Stato di nascita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthCountry')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Provincia di nascita (EE = estero)"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthProvince')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("Comune di nascita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('birthTown')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Via e numero civico"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('address')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender"><?= $this->translate("Informazioni aggiuntive"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('addressInfo')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name"><?= $this->translate("CAP"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('zipCode')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname"><?= $this->translate("Città"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('town')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="language"><?= $this->translate("Lingua preferita"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('language')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="taxCode"><?= $this->translate("Codice fiscale"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="vat"><?= $this->translate("Partita IVA (opzionale)"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('vat')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="mobile"><?= $this->translate("Cellulare"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('mobile')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="phone"><?= $this->translate("Telefono"); ?></label>
                                <?= $this->formRow($form->get('customer')->get('phone')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati Anagrafici"); ?></button>
                        </div>
                    </div>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
        <!-- END Customer details -->

        <!-- BEGIN Driver's license details -->
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Dati Patente"); ?></div>
            <div class="panel-body">

                <?= $this->form()->openTag($formDriver); ?>
                    <input type="hidden" name="type" value="driver">

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicense"><?= $this->translate("Patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicense')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseAuthority"><?= $this->translate("Rilasciato da (autorità)"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseAuthority')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseReleaseDate"><?= $this->translate("Rilasciato il"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseReleaseDate')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseName"><?= $this->translate("Nome sulla patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseName"><?= $this->translate("Cognome sulla patente"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseSurname')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseCountry"><?= $this->translate("Rilasciata da (nazione)"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseExpire"><?= $this->translate("Data di scadenza"); ?></label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati Patente"); ?></button>
                        </div>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
        <!-- END Driver's license details -->
    </div>

    <div class="col-lg-3">

        <?= $this->form()->openTag($formSetting); ?>
        <input type="hidden" name="type" value="setting">

        <!-- BEGIN Other details -->
        <div class="panel panel-default">

            <div class="panel-heading"><?= $this->translate("Altri dati"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Stato Iscrizione"); ?></label>
                            <?= $this->formRow($formSetting->get('setting')->get('registrationCompleted'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Percentuale Sconto"); ?></label>
                            <?= $this->formRow(is_null($formSetting->get('setting')->get('discountRate')) ? '0' : $formSetting->get('setting')->get('discountRate'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="goldList"><?= $this->translate("Maintainer"); ?></label>
                            <?= $this->formRow($formSetting->get('setting')->get('maintainer'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="goldList"><?= $this->translate("Gold List"); ?></label>
                            <?= $this->formRow($formSetting->get('setting')->get('goldList'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success"><?= $this->translate("Salva Dati"); ?></button>
                    </div>
                </div>

            </div>

        </div>
        <!-- END Other details -->
        <?= $this->form()->closeTag(); ?>

        <!-- BEGIN Customer activation/deactivation -->
        <?php
            $isEnabled = $customer->getEnabled();
            $deactivations = $this->deactivations;
            $isManuallyDisabled = false;
        ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Abilitazione"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <label class="sng-margin-top"><?= $this->translate("Stato:"); ?></label>
                        <label class="sng-info-box sng-move-right"><?= $isEnabled ? $this->translate('Abilitato') : $this->translate('Disabilitato');?></label>
                    </div>
                </div>

                <?php if (!$isEnabled): ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <label><?= $this->translate("Motivi:"); ?></label>
                    </div>
                </div>

                <?php foreach ($deactivations as $deactivation): ?>

                <div class="row sng-margin-bottom">
                    <div class="col-lg-12">
                        <label class="sng-info-box sng-full-width">
                            <?php if ($deactivation->isGeneratedAutomatically()): ?>
                            <i class="fa fa-info-circle" title="<?= $this->translate("Generata automaticamente, alcuni dati potrebbero non essere corretti"); ?>"></i>
                            <?php endif; ?>
                            <a class="sng-move-right sng-margin-left"
                                href="<?= $this->url(
                                    'customers/edit-deactivation',
                                    ['id' => $this->customer->getId()],
                                    ['query' => ['deactivationId' => $deactivation->getId()]]
                                ); ?>"
                                onclick="removeDeactivation(event)">
                                <i class="fa fa-trash"></i>
                            </a>
                            <?= $deactivation->getReasonTranslated(); ?>
                        </label>
                    </div>
                </div>

                <?php
                    $isManuallyDisabled = $isManuallyDisabled || $deactivation->getReason() == CustomerDeactivation::DISABLED_BY_WEBUSER;
                ?>

                <?php endforeach; ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <form class="portlet-body"
                            action="<?= $this->url('customers/reactivate', ['id' => $this->customer->getId()]); ?>"
                            method="post">
                            <input id="js-reactivate"
                                class="btn btn-success"
                                type="submit"
                                onclick="reactivate(event)"
                                value="<?= $this->translate("Riabilita"); ?>">
                            </input>
                        </form>
                    </div>
                </div>

                <?php endif; ?>

                <?php if (!$isManuallyDisabled): ?>

                <div class="row sng-margin-top">
                    <div class="col-lg-12">
                        <form class="portlet-body"
                            action="<?= $this->url('customers/deactivate', ['id' => $this->customer->getId()]); ?>"
                            method="post">
                            <input id="js-reactivate"
                                class="btn btn-success"
                                type="submit"
                                onclick="deactivate(event)"
                                value="<?= $this->translate("Disabilita manualmente"); ?>">
                            </input>
                        </form>
                    </div>
                </div>

                <?php endif; ?>

            </div>
        </div>
        <!-- END Customer activation/deactivation -->
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customers-edit.js'; ?>"></script>
