<?php
$form = $this->cardForm->prepare();
$this->headLink()
    ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    AGGIUNGI CARD <?= $this->customer ? $this->customer->getName() . ' ' . $this->customer->getSurname() : '';?>
                </h3>
            </div>

            <div class="col-lg-6">
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-lg-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <?= $this->form()->openTag($form); ?>

                <div class="row">
                    <div class="col-lg-12">
                        <label>Codice</label>
                        <?= $this->formRow($form->get('card')->get('code')); ?>
                    </div>
                </div>

                <br />
                <input type=submit name="" class="btn btn-success" value="<?= $this->translate('Aggiungi Card'); ?>">

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>