<?php
$form = $this->promoCodeForm->prepare();
$this->headLink()
    ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
?>
    <div class="page-content-wrapper">
        <div class="page-content">

            <div class="row">
                <div class="col-lg-6">
                    <h3 class="page-title">
                        AGGIUNGI BONUS AL CLIENTE <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                    </h3>
                </div>

                <div class="col-lg-6">
                    <a href="<?= $this->url('customers/edit', ['id' => $this->customer->getId()], ['query' => ['tab' => 'bonus']]); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> Torna alla lista</a>
                </div>
            </div>

            <div class="page-bar">
            </div>

            <div class="row">
                <div class="col-lg-12">

                    <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                    <?= $this->form()->openTag($form); ?>

                    <div class="row">
                        <div class="col-lg-4">
                            <label>Totale</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('total')); ?>
                        </div>
                        <div class="col-lg-4">
                            <label>Tipo</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('type')); ?>
                        </div>
                        <div class="col-lg-4">
                            <label>Descrizione</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('description')); ?>
                        </div>
                    </div>

                    <div class="row" style="margin-top: 10px;">
                        <div class="col-lg-4">
                            <label>Valido Da</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('validFrom')); ?>
                        </div>
                        <div class="col-lg-4">
                            <label>Valido Al</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('validTo')); ?>
                        </div>
                        <div class="col-lg-2">
                            <label>Durata Giorni</label>
                            <?= $this->formRow($form->get('customer-bonus')->get('durationDays')->setAttribute('class', 'form-control')); ?>
                        </div>
                    </div>

                    <br />
                    <input type=submit name="" class="btn btn-success" value="<?= $this->translate('Aggiungi Bonus'); ?>">

                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>

            <!-- END PAGE CONTENT-->
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.date-picker').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            weekStart: 1
        });
    });
</script>