<?php
$form = $this->promoCodeForm->prepare();
$this->headLink()
    ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
?>
    <div class="page-content-wrapper">
        <div class="page-content">

            <div class="row">
                <div class="col-lg-6">
                    <h3 class="page-title">
                        <?= $this->translate("AGGIUNGI PUNTI"); ?> <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                    </h3>
                </div>

                <div class="col-lg-6">
                    <a href="<?= $this->url('customers/edit', ['id' => $this->customer->getId()], ['query' => ['tab' => 'points']]); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla scheda cliente"); ?></a>
                </div>
            </div>

            <div class="page-bar">
            </div>

            <div class="row">
                <div class="col-lg-12">

                    <?= $this->partial('partials/flash-messages.phtml', []); ?>

                    <?= $this->form()->openTag($form); ?>

                    <div class="row">
                        <div class="col-lg-4">
                            <label><?= $this->translate("Numero punti"); ?></label>
                            <?= $this->formRow($form->get('customer-point')->get('total')); ?>
                        </div>
                        <div class="col-lg-8">
                            <label><?= $this->translate("Descrizione"); ?></label>
                            <?= $this->formRow($form->get('customer-point')->get('description')); ?>
                        </div>
                    </div>

                    <div class="row" style="margin-top: 10px;">
                        <div class="col-lg-4">
                            <label><?= $this->translate("Utilizzabile dal"); ?></label>
                            <?= $this->formRow($form->get('customer-point')->get('validFrom')); ?>
                        </div>
                        <div class="col-lg-4">
                            <label><?= $this->translate("Utilizzabile fino al"); ?></label>
                            <?= $this->formRow($form->get('customer-point')->get('validTo')); ?>
                        </div>
                    </div>

                    <br />
                    <input type=submit name="" class="btn btn-success" value="<?= $this->translate('Aggiungi Punti'); ?>">

                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>

            <!-- END PAGE CONTENT-->
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.date-picker').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            weekStart: 1
        });
    });
</script>
