<?php
$form = $this->promoCodeForm->prepare();
?>
    <div class="page-content-wrapper">
        <div class="page-content">

            <div class="row">
                <div class="col-lg-6">
                    <h3 class="page-title">
                        <?= $this->translate("ASSOCIA CODICE PROMO"); ?> <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                    </h3>
                </div>

                <div class="col-lg-6">
                    <a href="<?= $this->url('customers/edit', ['id' => $this->customer->getId()], ['query' => ['tab' => 'bonus']]); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla scheda cliente"); ?></a>
                </div>
            </div>

            <div class="page-bar">
            </div>

            <div class="row">
                <div class="col-lg-12">

                    <?= $this->partial('partials/flash-messages.phtml', []); ?>

                    <?= $this->form()->openTag($form); ?>
                    <div class="form-group">

                        <?php
                            $promoCode = $form->get('promocode')->get('promocode');
                            echo $this->formElement($promoCode->setAttribute('class', 'form-control'));
                            echo $this->formElementErrors($promoCode, array('class' => 'text-danger'));
                            ?>
                    </div>

                    <button type=submit class="btn btn-success"><?= $this->translate("Conferma"); ?></button>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>

            <!-- END PAGE CONTENT-->
        </div>
    </div>