<?php
$form = $this->promoCodeForm->prepare();
?>
    <div class="page-content-wrapper">
        <div class="page-content">

            <div class="row">
                <div class="col-lg-6">
                    <h3 class="page-title">
                        ASSEGNA BONUS CLIENTE <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                    </h3>
                </div>

                <div class="col-lg-6">
                    <a href="<?php echo $this->url('customers/edit', ['id' => $this->customer->getId()]); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> Torna alla lista</a>
                </div>
            </div>

            <div class="page-bar">
            </div>

            <div class="row">
                <div class="col-lg-12">

                    <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                    <?= $this->form()->openTag($form); ?>

                    <p> <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                        <?php
                        $promoCode = $form->get('promocode')->get('promocode');
                        echo $this->formElement($promoCode->setAttribute('class', 'form-control'));
                        echo $this->formElementErrors($promoCode, array('class' => 'text-danger'));
                        ?>
                    </p>

                    <input type=submit name="" class="btn btn-success" value="<?= $this->translate('Aggiungi Bonus'); ?>">

                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>

            <!-- END PAGE CONTENT-->
        </div>
    </div>