<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p>Operazione eseguita con successo</p>
        </div>

        <div class="btn-group btn-group-sm btn-group-solid margin-bottom-10 btn-group-spaced">
            <a href="<?= $this->url('customers/assign-promo-code', ['id' => $this->customer->getId()]); ?>" class="btn green"><i class="fa fa-arrow-circle-o-right"></i> Associa promo code</a>
            <a href="<?= $this->url('customers/add-bonus', ['id' => $this->customer->getId()]); ?>" class="btn green"><i class="fa fa-plus"></i> Aggiungi bonus</a>
        </div>

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

        <?php if(count($this->listBonus) > 0): ?>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Totale</th>
                <th>Residuo</th>
                <th>Valido Dal</th>
                <th>Valido Fino al</th>
                <th>Tipologia</th>
                <th>Descrizione</th>
                <th>Azioni</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\CustomersBonus $bonus */
            foreach($this->listBonus as $bonus): ?>
                <tr id="js-row-bonus-<?= $bonus->getId(); ?>">
                    <td style="font-weight: normal;"><?= $bonus->getTotal(); ?></td>
                    <td><?= $bonus->getResidual(); ?></td>
                    <td><?= is_object($bonus->getValidFrom()) ? $bonus->getValidFrom()->format('d-m-Y H:i:s') : ''; ?></td>
                    <td><?= is_object($bonus->getValidTo()) ? $bonus->getValidTo()->format('d-m-Y H:i:s') : ''; ?></td>
                    <td style="font-weight: normal;"><?= $bonus->getType(); ?></td>
                    <td style="font-weight: normal;"><?= $bonus->getDescription(); ?></td>
                    <td>
                        <?php if ($bonus->canBeDeleted()): ?>
                            <a href="javascript:void(0);" data-id="<?= $this->customer->getId(); ?>" data-bonus="<?= $bonus->getId(); ?>" class="btn btn-default" id="js-remove-bonus">Elimina</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php else: ?>
            <div class="alert alert-info">Il cliente non ha alcun bonus assegnato.</div>
        <?php endif; ?>
    </div>
</div>