<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p><?= $this->translate("Operazione eseguita con successo"); ?></p>
        </div>

        <div class="btn-group btn-group-sm btn-group-solid margin-bottom-10 btn-group-spaced">
            <a href="<?= $this->url('customers/assign-promo-code', ['id' => $this->customer->getId()]); ?>" class="btn green"><i class="fa fa-arrow-circle-o-right"></i> <?= $this->translate("Associa promo code"); ?></a>
            <a href="<?= $this->url('customers/add-bonus', ['id' => $this->customer->getId()]); ?>" class="btn green"><i class="fa fa-plus"></i> <?= $this->translate("Aggiungi bonus"); ?></a>
        </div>

        <?= $this->partial('partials/flash-messages.phtml', []); ?>

        <?php if(count($this->listBonus) > 0): ?>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th><?= $this->translate("Totale"); ?></th>
                <th><?= $this->translate("Residuo"); ?></th>
                <th><?= $this->translate("Valido Dal"); ?></th>
                <th><?= $this->translate("Valido Fino al"); ?></th>
                <th><?= $this->translate("Tipologia"); ?></th>
                <th><?= $this->translate("Descrizione"); ?></th>
                <th><?= $this->translate("Note"); ?></th>
                <th><?= $this->translate("Azioni"); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\CustomersBonus $bonus */
            foreach($this->listBonus as $bonus): ?>
                <tr id="js-row-bonus-<?= $bonus->getId(); ?>">
                    <td style="font-weight: normal;"><?= $bonus->getTotal(); ?></td>
                    <td><?= $bonus->getResidual(); ?></td>
                    <td><?= is_object($bonus->getValidFrom()) ? $bonus->getValidFrom()->format('d-m-Y H:i:s') : ''; ?></td>
                    <td><?= is_object($bonus->getValidTo()) ? $bonus->getValidTo()->format('d-m-Y H:i:s') : ''; ?></td>
                    <td style="font-weight: normal;"><?= $bonus->getType(); ?></td>
                    <td style="font-weight: normal;"><?= $bonus->getDescription(); ?></td>
                    <td style="font-weight: normal;"><?= $bonus->getNote(); ?></td>
                    <td>
                        <?php if ($bonus->canBeDeleted()): ?>
                            <a href="javascript:void(0);" data-id="<?= $this->customer->getId(); ?>" data-bonus="<?= $bonus->getId(); ?>" class="btn btn-default" id="js-remove-bonus"><?= $this->translate("Elimina"); ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php else: ?>
            <div class="alert alert-info"><?= $this->translate("Il cliente non ha alcun bonus assegnato."); ?></div>
        <?php endif; ?>
    </div>
</div>