<div class="row">
    <div class="col-lg-12">

        <?php if(count($this->listBonus) > 0): ?>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Totale</th>
                <th>Residuo</th>
                <th>Valido Dal</th>
                <th>Valido Fino al</th>
                <th>Tipologia</th>
                <th>Descrizione</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\CustomersBonus $bonus */
            foreach($this->listBonus as $bonus): ?>
                <tr>
                    <th style="font-weight: normal;"><?= $bonus->getTotal(); ?></th>
                    <td><?= $bonus->getResidual(); ?></td>
                    <td><?= is_object($bonus->getValidFrom()) ? $bonus->getValidFrom()->format('d-m-Y H:i:s') : ''; ?></td>
                    <td><?= is_object($bonus->getValidTo()) ? $bonus->getValidTo()->format('d-m-Y H:i:s') : ''; ?></td>
                    <th style="font-weight: normal;"><?= $bonus->getType(); ?></th>
                    <th style="font-weight: normal;"><?= $bonus->getDescription(); ?></th>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php else: ?>
            <div class="alert alert-info">Al momento il cliente <strong><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></strong> non ha nessun bonus assegnato.</div>
        <?php endif; ?>
    </div>
</div>