<div class="row">
    <div class="col-lg-12">

            <div id="js-with-code" style="<?= is_object($this->customer->getCard()) ? '' : 'display: none;'; ?>">
                <div class="row">
                    <div class="col-lg-5">
                        <h1>Codice Card: <span id="js-code"><?= is_object($this->customer->getCard()) ? $this->customer->getCard()->getCode() : ''; ?></span></h1>
                    </div>
                    <div class="col-lg-7" style="margin-top: 20px;">
                        <a href="javascript:void(0);" id="js-remove-card" data-id="<?= $this->customer->getId(); ?>" class="btn btn-danger"><i class="fa fa-remove"></i> Rimuovi Card</i></a>
                    </div>
                </div>
            </div>
            <div id="js-no-code" style="<?= !is_object($this->customer->getCard()) ? '' : 'display: none;'; ?>">
                <div class="col-lg-6">
                    <div class="alert alert-info">
                        Nessun codice card assegnato per questo utente.
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="col-lg-9">
                        <input id="typeahead-input" type="text" class="form-control" placeholder="Aggiungi Codice Card..." autocomplete="off" />
                    </div>
                    <div class="col-lg-3">
                        <a href="javascript:void(0);" id="js-assign-card" data-code="" data-id="<?= $this->customer->getId(); ?>" class="btn btn-success" style="display: none;"><i class="fa fa-plus"></i> Salva Codice</i></a>
                    </div>
                </div>
            </div>
    </div>
</div>
<script src="/js/bootstrap-typeahead.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {

        var assignButton = $('#js-assign-card');

        $("#typeahead-input").typeahead({
            onSelect: function(item) {
                $(assignButton).data('code', item.value);
                $(assignButton).show();
            },
            ajax: {
                url: "/customers/ajax-card-code-autocomplete",
                triggerLength: 4,
                method: "get"
            }
        });
    })
</script>
