<div class="row">
    <div class="col-lg-12">
        <?php if ($this->contract): ?>
            <div class="row col-lg-12">
                <h1>Contratto:</h1>
            </div><br>
            <div class="row">
                <div class="col-lg-12">Codice contratto: <span><?= $this->contract->getId(); ?></span></div>
            </div><br>
            <div class="row">
                <div class="col-lg-12">Pan: <span><?= $this->contract->getPan(); ?></span></div>
            </div><br>
            <div class="row">
                <div class="col-lg-12">Scadenza Pan: <span><?= $this->contract->getPanExpiry(); ?></span></div>
            </div><br>
            <div class="row">
                <div class="col-lg-12">
                    <?php if ($this->contract->getDisabledDate()): ?>
                        Data di disabilitazione: <span><?= $this->contract->getDisabledDate()->format('Y-m-d H:i:s'); ?></span>
                    <?php else: ?>
                        <button id="disable-contract" class="btn btn-danger" data-contract-id="<?= $this->contract->getId(); ?>">
                            <i class="fa fa-ban"></i> Disabilita contratto
                        </button>
                    <?php endif; ?>
                </div>
            </div>
        <?php else: ?>
            <div class="col-lg-12">Il cliente selezionato non ha al momento un contratto valido con Cartasi</div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customers-contract.js'; ?>"></script>