<div class="row">
    <div class="col-lg-12">
       <?php if ($this->contract): ?>
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-credit-card"></i><?= $this->translate("Contratto cliente"); ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label><?= $this->translate("Codice contratto"); ?></label>
                                <div class="form-control" disabled><?= $this->contract->getId(); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label><?= $this->translate("Data attivazione contratto"); ?></label>
                                <div class="form-control" disabled><?= $this->contract->getInsertedTs()->format('d/m/Y'); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label><?= $this->translate("Carta di credito inserita"); ?></label>
                                <div class="form-control" disabled><?= $this->contract->getPan(); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label><?= $this->translate("Scadenza carta di credito"); ?></label>
                                <div class="form-control" disabled><?= implode('/', str_split($this->contract->getPanExpiry(), 4)); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->contract->getDisabledDate()): ?>
                                <?= $this->translate("Data di disabilitazione:"); ?> <span><?= $this->contract->getDisabledDate()->format('Y-m-d H:i:s'); ?></span>
                            <?php else: ?>
                                <button id="disable-contract" class="btn btn-danger" data-contract-id="<?= $this->contract->getId(); ?>">
                                    <i class="fa fa-ban"></i> <?= $this->translate("Disabilita contratto"); ?>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="col-lg-12"><?= $this->translate("Il cliente selezionato non ha al momento un contratto valido con Cartasi"); ?></div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customers-contract.js'; ?>"></script>
<script>
    var infoUrl = "<?= $this->url('customers/edit', ['id' => $this->customer->getId()], ['force_canonical' => true]) ?>";
</script>