<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->prependFile('/js/jquery.validate-messages-it.js')
    ->prependFile('/js/spin.min.js')
    ->prependFile('/js/jquery.validate.min.js')
    ->appendFile($this->basePath() .'/js/customers.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    <?= $this->translate("MODIFICA CLIENTE"); ?> <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('customers'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-tabs" id="js-tabs" role="tablist">
                    <li role="presentation" id="menu-info"><a href="<?= $this->url('customers/ajax-tab-info', ['id' => $this->customer->getId()]); ?>" data-target="#tab-info" role="tab" data-toggle="tab"><?= $this->translate("Informazioni"); ?></a></li>
                    <li role="presentation" id="menu-edit"><a href="<?= $this->url('customers/ajax-tab-edit', ['id' => $this->customer->getId()]); ?>" data-target="#tab-edit" role="tab" data-toggle="tab"><?= $this->translate("Modifica"); ?></a></li>
                    <li role="presentation" id="menu-bonus"><a href="<?= $this->url('customers/ajax-tab-bonus', ['id' => $this->customer->getId()]); ?>" data-target="#tab-bonus" role="tab" data-toggle="tab"><?= $this->translate("Bonus"); ?></a></li>
                    <li role="presentation" id="menu-points"><a href="<?= $this->url('customers/ajax-tab-points', ['id' => $this->customer->getId()]); ?>" data-target="#tab-points" role="tab" data-toggle="tab"><?= $this->translate("Points"); ?></a></li>
                    <li role="presentation" id="menu-card"><a href="<?= $this->url('customers/ajax-tab-card', ['id' => $this->customer->getId()]); ?>" data-target="#tab-card" role="tab" data-toggle="tab"><?= $this->translate("Card"); ?></a></li>
                    <li role="presentation" id="menu-invoices"><a href="<?= $this->url('customers/ajax-tab-invoices', ['id' => $this->customer->getId()]); ?>" data-target="#tab-invoices" role="tab" data-toggle="tab"><?= $this->translate("Fatture"); ?></a></li>
                    <li role="presentation" id="menu-contract"><a href="<?= $this->url('customers/ajax-tab-contract', ['id' => $this->customer->getId()]); ?>" data-target="#tab-contract" role="tab" data-toggle="tab"><?= $this->translate("Contratto"); ?></a></li>
                    <li role="presentation" id="menu-notes"><a href="<?= $this->url('customers/ajax-tab-notes', ['id' => $this->customer->getId()]); ?>" data-target="#tab-notes" role="tab" data-toggle="tab"><?= $this->translate("Note"); ?></a></li>
                    <li role="presentation" id="menu-failure"><a href="<?= $this->url('customers/ajax-tab-failure', ['id' => $this->customer->getId()]); ?>" data-target="#tab-failure" role="tab" data-toggle="tab"><?= $this->translate("Pagamenti falliti"); ?></a></li>
                    <li role="presentation" id="menu-extra"><a href="<?= $this->url('customers/ajax-tab-extra', ['id' => $this->customer->getId()]); ?>" data-target="#tab-extra" role="tab" data-toggle="tab"><?= $this->translate("Extra/Penali fallite"); ?></a></li>
                    <li role="presentation" id="menu-license"><a href="<?= $this->url('customers/ajax-tab-license', ['id' => $this->customer->getId()]); ?>" data-target="#tab-license" role="tab" data-toggle="tab"><?= $this->translate("Patente"); ?></a></li>
                </ul>

                <div class="tab-content">
                    <div id="spinner-loader"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-info"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-edit"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-bonus"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-points"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-card"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-invoices"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-contract"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-notes"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-failure"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-extra"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-license"></div>
                </div>
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
<?php
echo $this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {

    var opts = {
      lines: 13 // The number of lines to draw
        , length: 28 // The length of each line
        , width: 14 // The line thickness
        , radius: 42 // The radius of the inner circle
        , scale: 0.25 // Scales overall size of the spinner
        , corners: 1 // Corner roundness (0..1)
        , color: '#000' // #rgb or #rrggbb or array of colors
        , opacity: 0.25 // Opacity of the lines
        , rotate: 0 // The rotation offset
        , direction: 1 // 1: clockwise, -1: counterclockwise
        , speed: 1 // Rounds per second
        , trail: 60 // Afterglow percentage
        , fps: 20 // Frames per second when using setTimeout() as a fallback for CSS
        , zIndex: 2e9 // The z-index (defaults to 2000000000)
        , className: 'spinner' // The CSS class to assign to the spinner
        , top: '50%' // Top position relative to parent
        , left: '50%' // Left position relative to parent
        , shadow: false // Whether to render a shadow
        , hwaccel: false // Whether to use hardware acceleration
        , position: 'absolute' // Element positioning
    }
    var target = document.getElementById('spinner-loader')
    var spinner = new Spinner(opts).spin(target);
    var tab = '{$this->tab}';
    var idTab = '#tab-' + tab;
    $('#menu-' + tab).addClass('active');
    $(idTab).addClass('active');

    var href = $(document).find('#js-tabs .active a').attr("href");

    $(idTab).load(href,function(e){
      $('#js-tabs .active a').tab('show');
      spinner.stop();
    });

    $('#js-tabs a').click(function(e) {
        var spinner = new Spinner(opts).spin(target);
        var _this = $(this);
        var loadurl = _this.attr('href');
        var targ = _this.attr('data-target');

        $.get(loadurl, function(data) {
            $(targ).html(data);
            spinner.stop();
        });

        _this.tab('show');
        return false;
    });
});
JS;
$this->inlineScript()->captureEnd(); ?>
