<?php
$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
$form->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formDriver->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
$formSetting->setAttribute('action', $this->url('customers/edit', ['id' => $this->customer->getId()]));
?>
<div class="row">
    <div class="col-lg-9">

        <div class="panel panel-default">
            <div class="panel-heading">Anagrafica</div>
            <div class="panel-body">

                <?= $this->form()->openTag($form); ?>
                    <input type="hidden" name="type" value="customer">

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender">Titolo</label>
                                <?= $this->formRow($form->get('customer')->get('gender')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname">Cognome</label>
                                <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender">Email</label>
                                <?= $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name">Data di nascita</label>
                                <?= $this->formRow($form->get('customer')->get('birthDate')->setAttributes(['readonly'=> 'true', 'class' => 'form-control'])); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname">Stato di nascita</label>
                                <?= $this->formRow($form->get('customer')->get('birthCountry')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender">Provincia di nascita (EE = estero)</label>
                                <?= $this->formRow($form->get('customer')->get('birthProvince')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name">Comune di nascita</label>
                                <?= $this->formRow($form->get('customer')->get('birthTown')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname">Via e numero civico</label>
                                <?= $this->formRow($form->get('customer')->get('address')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="gender">Informazioni aggiuntive</label>
                                <?= $this->formRow($form->get('customer')->get('addressInfo')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="name">CAP</label>
                                <?= $this->formRow($form->get('customer')->get('zipCode')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="surname">Città</label>
                                <?= $this->formRow($form->get('customer')->get('town')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="language">Lingua preferita</label>
                                <?= $this->formRow($form->get('customer')->get('language')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="taxCode">Codice fiscale</label>
                                <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="vat">Partita IVA (opzionale)</label>
                                <?= $this->formRow($form->get('customer')->get('vat')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="mobile">Cellulare</label>
                                <?= $this->formRow($form->get('customer')->get('mobile')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="phone">Telefono</label>
                                <?= $this->formRow($form->get('customer')->get('phone')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success">Salva Dati Anagrafici</button>
                        </div>
                    </div>

                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Dati Patente</div>
            <div class="panel-body">

                <?= $this->form()->openTag($formDriver); ?>
                    <input type="hidden" name="type" value="driver">

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicense">Patente</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicense')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseAuthority">Rilasciato da (autorità)</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseAuthority')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseReleaseDate">Rilasciato il</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseReleaseDate')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseName">Nome sulla patente</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseCountry">Rilasciata da (nazione)</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')); ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="driverLicenseExpire">Data di scadenza</label>
                                <?= $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success">Salva Dati Patente</button>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>

    <div class="col-lg-3">

        <?= $this->form()->openTag($formSetting); ?>
            <input type="hidden" name="type" value="setting">

        <div class="panel panel-default">

            <div class="panel-heading">Altri dati</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Abilitato</label>
                            <?= $this->formRow($formSetting->get('setting')->get('enabled'));?>
                        </div>
                    </div>
                </div>
                    
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Stato Iscrizione</label>
                            <?= $this->formRow($formSetting->get('setting')->get('registrationCompleted'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Stato Primo Pagamento</label>
                            <?= $this->formRow($formSetting->get('setting')->get('firstPaymentCompleted'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Percentuale Sconto</label>
                            <?= $this->formRow(is_null($formSetting->get('setting')->get('discountRate')) ? '0' : $formSetting->get('setting')->get('discountRate'));?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success">Salva Dati</button>
                    </div>
                </div>

            </div>

        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

<style>
    .error {color: red;}
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $("#customerForm").validate();
        $("#driverForm").validate();
        $("#settingForm").validate();
        $('.date-picker').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            weekStart: 1
        });
    });
</script>
