<?php
$form = $this->customerForm->prepare();
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() .'/js/customers.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    MODIFICA CLIENTE <small><?= $this->customer->getName() . ' ' . $this->customer->getSurname(); ?></small>
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?php echo $this->url('customers'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> Torna alla lista</a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->form()->openTag($form); ?>

                <div class="panel panel-default">
                    <div class="panel-heading">Anagrafica</div>
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="gender">Titolo</label>
                                    <?= $this->formRow($form->get('customer')->get('gender')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="name">Nome</label>
                                    <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="surname">Cognome</label>
                                    <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="gender">Email</label>
                                    <?= $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'true')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="name">Data di nascita</label>
                                    <?= $this->formRow($form->get('customer')->get('birthDate')->setAttribute('readonly', 'true')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="surname">Stato di nascita</label>
                                    <?= $this->formRow($form->get('customer')->get('birthCountry')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="gender">Provincia di nascita (EE = estero)</label>
                                    <?= $this->formRow($form->get('customer')->get('birthProvince')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="name">Comune di nascita</label>
                                    <?= $this->formRow($form->get('customer')->get('birthTown')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="surname">Via e numero civico</label>
                                    <?= $this->formRow($form->get('customer')->get('address')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="gender">Informazioni aggiuntive</label>
                                    <?= $this->formRow($form->get('customer')->get('addressInfo')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="name">CAP</label>
                                    <?= $this->formRow($form->get('customer')->get('zipCode')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="surname">Città</label>
                                    <?= $this->formRow($form->get('customer')->get('town')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="language">Lingua preferita</label>
                                    <?= $this->formRow($form->get('customer')->get('language')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="taxCode">Codice fiscale</label>
                                    <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="vat">Partita IVA (opzionale)</label>
                                    <?= $this->formRow($form->get('customer')->get('vat')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="mobile">Cellulare</label>
                                    <?= $this->formRow($form->get('customer')->get('mobile')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="phone">Telefono</label>
                                    <?= $this->formRow($form->get('customer')->get('phone')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                            </div>
                        </div>

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Dati Patente</div>
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicense">Patente</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicense')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicenseAuthority">Rilasciato da (autorità)</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicenseAuthority')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicenseReleaseDate">Rilasciato il</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicenseReleaseDate')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicenseName">Nome sulla patente</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicenseName')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicenseCountry">Rilasciata da (nazione)</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicenseCountry')); ?>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="driverLicenseExpire">Data di scadenza</label>
                                    <?= $this->formRow($form->get('customer')->get('driverLicenseExpire')); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">Stato Iscrizione</div>
                            <div class="panel-body">

                                <div class="row">
                                    <div class="col-lg-6">
                                        <?php if($this->customer->getRegistrationCompleted()): ?>
                                            <h4 class="text-success">Registrazione Confermata</h4>
                                        <?php else: ?>
                                            <h4 class="text-danger">Registrazione Non Confermata</h4>
                                        <?php endif; ?>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="registrationCompleted">Registrazione</label>
                                            <?= $this->formRow($form->get('customer')->get('registrationCompleted')); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">Stato Pagamento</div>
                            <div class="panel-body">

                                <div class="row">
                                    <div class="col-lg-12">
                                        <?php if($this->customer->getFirstPaymentCompleted()): ?>
                                            <h4 class="text-success">Pagamento Effettuato</h4>
                                        <?php else: ?>
                                            <h4 class="text-danger">Pagamento Non Ancora Effettuato</h4>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success">Salva</button>
                    </div>
                </div>

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
