<?php
$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
?>
<div class="row">
    <div class="col-lg-9">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Anagrafica"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Titolo"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('gender')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?php echo $this->translate("Nome"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?php echo $this->translate("Cognome"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Email"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?php echo $this->translate("Data di nascita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthDate')->setAttributes(['readonly'=> 'true', 'class' => 'form-control'])); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?php echo $this->translate("Stato di nascita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Provincia di nascita (EE = estero)"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthProvince')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?php echo $this->translate("Comune di nascita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthTown')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?php echo $this->translate("Via e numero civico"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('address')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Informazioni aggiuntive"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('addressInfo')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?php echo $this->translate("CAP"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('zipCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?php echo $this->translate("Città"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('town')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="language"><?php echo $this->translate("Lingua preferita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('language')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="taxCode"><?php echo $this->translate("Codice fiscale"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="vat"><?php echo $this->translate("Partita IVA (opzionale)"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('vat')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="mobile"><?php echo $this->translate("Cellulare"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('mobile')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="phone"><?php echo $this->translate("Telefono"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('phone')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="id"><?php echo $this->translate("Id"); ?></label>
                            <?php $idElement = $form->get('customer')->get('id');
                                $idElement->setAttributes(['type'=>'text','readonly'=>'true','class'=>'form-control']);
                            ?>
                            <?= $this->formRow($idElement); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Dati Patente"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicense"><?php echo $this->translate("Patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicense')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseAuthority"><?php echo $this->translate("Rilasciato da (autorità)"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseAuthority')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseReleaseDate"><?php echo $this->translate("Rilasciato il"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseReleaseDate')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName"><?php echo $this->translate("Nome sulla patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName"><?php echo $this->translate("Cognome sulla patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseSurname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseCountry"><?php echo $this->translate("Rilasciata da (nazione)"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseExpire"><?php echo $this->translate("Data di scadenza"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading"><?php echo $this->translate("Altri dati"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Abilitato"); ?></label>
                            <?php if($this->customer->getEnabled()): ?>
                                <div class="alert alert-success"><?php echo $this->translate("Abilitato"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?php echo $this->translate("Non Abilitato"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Stato Iscrizione"); ?></label>
                            <?php if($this->customer->getRegistrationCompleted()): ?>
                                <div class="alert alert-success"><?php echo $this->translate("Registrazione Confermata"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?php echo $this->translate("Registrazione Non Confermata"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Stato Primo Pagamento"); ?></label>
                            <?php if($this->customer->getFirstPaymentCompleted()): ?>
                                <div class="alert alert-success"><?php echo $this->translate("Pagamento Effettuato"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?php echo $this->translate("Pagamento Non Ancora Effettuato"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Percentuale Sconto"); ?></label>
                            <h1 class="text-center"><?= is_null($this->customer->getDiscountRate()) ? '0' : $this->customer->getDiscountRate(); ?>%</h1>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?php echo $this->translate("Data/Ora"); ?></label>
                            <h4><?php echo $this->translate("Iscrizione:"); ?><br><?= is_object($this->customer->getInsertedTs()) ? $this->customer->getInsertedTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                            <h4><?= is_object($this->customer->getUpdateTs()) ? $this->translate('Ultima Modifica: ') . $this->customer->getUpdateTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="maintainer"><?php echo $this->translate("Maintainer"); ?></label>
                            <?php if($this->customer->getMaintainer()): ?>
                                <div class="alert alert-success"><?php echo $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?php echo $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="goldList"><?php echo $this->translate("Gold List"); ?></label>
                            <?php if($this->customer->getGoldList()): ?>
                                <div class="alert alert-success"><?php echo $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?php echo $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>
