<?php
$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
$input = '<input type="text" class="form-control" required="required" readonly="readonly" value="">';
?>
<div class="row">
    <div class="col-lg-9">

        <?= $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Anagrafica"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Titolo"); ?></label>
                            <?= is_null($form->get('customer')->get('gender')->getValue()) ? $input : $this->formRow($form->get('customer')->get('gender')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Nome"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Cognome"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Email"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Data di nascita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthDate')->setAttributes(['readonly'=> 'true', 'class' => 'form-control'])); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Stato di nascita"); ?></label>
                            <?= is_null($form->get('customer')->get('birthCountry')->getValue()) ? $input :  $this->formRow($form->get('customer')->get('birthCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Provincia di nascita (EE = estero)"); ?></label>
                            <?= is_null($form->get('customer')->get('birthProvince')->getValue()) ? $input : $this->formRow($form->get('customer')->get('birthProvince')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Comune di nascita"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('birthTown')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Via e numero civico"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('address')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Informazioni aggiuntive"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('addressInfo')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("CAP"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('zipCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Città"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('town')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="language"><?= $this->translate("Lingua preferita"); ?></label>
                            <?= is_null($form->get('customer')->get('language')->getValue()) ? $input : $this->formRow($form->get('customer')->get('language')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="taxCode"><?= $this->translate("Codice fiscale"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="vat"><?= $this->translate("Partita IVA (opzionale)"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('vat')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="mobile"><?= $this->translate("Cellulare"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('mobile')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="phone"><?= $this->translate("Telefono"); ?></label>
                            <?= $this->formRow($form->get('customer')->get('phone')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="id"><?= $this->translate("Id"); ?></label>
                            <?php $idElement = $form->get('customer')->get('id');
                                $idElement->setAttributes(['type'=>'text','readonly'=>'true','class'=>'form-control']);
                            ?>
                            <?= $this->formRow($idElement); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Dati Patente"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicense"><?= $this->translate("Patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicense')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName"><?= $this->translate("Nome sulla patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName"><?= $this->translate("Cognome sulla patente"); ?></label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseSurname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseCountry"><?= $this->translate("Rilasciata da (nazione)"); ?></label>
                            <?= is_null($formDriver->get('driver')->get('driverLicenseCountry')->getValue()) ? $input : $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseExpire"><?= $this->translate("Data di scadenza"); ?></label>
                            <?= is_null($formDriver->get('driver')->get('driverLicenseExpire')->getValue()) ? $input : $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3">
<!--        <?php /*if(!$this->customer->getRegistrationCompleted()){*/?>
        <div class="panel panel-default">
            <div class="panel-heading"><?/*= $this->translate("Reinvio email di completamento iscrizione"); */?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <button onclick="resendEmailRegistrationComplite(<?php /*$form->get('customer')->get('id') */?>)" class="btn btn-success"><?/*= $this->translate('Invia email'); */?></button>
                    </div>
                </div>
            </div>
        </div>
        --><?php /*}*/?>
        <div id="responseMessageSendEmail" style="display:none"></div>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Altri dati"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Abilitato"); ?></label>
                            <?php if ($this->customer->getEnabled()): ?>
                                <div class="alert alert-success"><?= $this->translate("Abilitato"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("Non Abilitato"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Stato Iscrizione"); ?></label>
                            <?php if($this->customer->getRegistrationCompleted()): ?>
                                <div class="alert alert-success"><?= $this->translate("Registrazione Confermata"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("Registrazione Non Confermata"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Stato Primo Pagamento"); ?></label>
                            <?php if($this->customer->getFirstPaymentCompleted()): ?>
                                <div class="alert alert-success"><?= $this->translate("Pagamento Effettuato"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("Pagamento Non Ancora Effettuato"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Percentuale Sconto"); ?></label>
                            <h1 class="text-center"><?= is_null($this->customer->getDiscountRate()) ? '0' : $this->customer->getDiscountRate(); ?>%</h1>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Data/Ora"); ?></label>
                            <h4><?= $this->translate("Iscrizione:"); ?><br><?= is_object($this->customer->getInsertedTs()) ? $this->customer->getInsertedTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                            <h4><?= is_object($this->customer->getUpdateTs()) ? $this->translate('Ultima Modifica: ') . $this->customer->getUpdateTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="maintainer"><?= $this->translate("Maintainer"); ?></label>
                            <?php if($this->customer->getMaintainer()): ?>
                                <div class="alert alert-success"><?= $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="goldList"><?= $this->translate("Gold List"); ?></label>
                            <?php if($this->customer->getGoldList()): ?>
                                <div class="alert alert-success"><?= $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="silverList"><?= $this->translate("Silver List"); ?></label>
                            <?php if($this->customer->getSilverList()): ?>
                                <div class="alert alert-success"><?= $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="firstPaymentCompleted"><?= $this->translate("First Payment Completed"); ?></label>
                            <?php if ($this->customer->getFirstPaymentCompleted()): ?>
                                <div class="alert alert-success"><?= $this->translate("Si"); ?></div>
                            <?php else: ?>
                                <div class="alert alert-danger"><?= $this->translate("No"); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    

</div>
