<?php
$form = $this->customerForm->prepare();
$formDriver =  $this->driverForm->prepare();
$formSetting = $this->settingForm->prepare();
?>
<div class="row">
    <div class="col-lg-9">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="panel panel-default">
            <div class="panel-heading">Anagrafica</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender">Titolo</label>
                            <?= $this->formRow($form->get('customer')->get('gender')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name">Nome</label>
                            <?= $this->formRow($form->get('customer')->get('name')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname">Cognome</label>
                            <?= $this->formRow($form->get('customer')->get('surname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender">Email</label>
                            <?= $this->formRow($form->get('customer')->get('email')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name">Data di nascita</label>
                            <?= $this->formRow($form->get('customer')->get('birthDate')->setAttributes(['readonly'=> 'true', 'class' => 'form-control'])); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname">Stato di nascita</label>
                            <?= $this->formRow($form->get('customer')->get('birthCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender">Provincia di nascita (EE = estero)</label>
                            <?= $this->formRow($form->get('customer')->get('birthProvince')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name">Comune di nascita</label>
                            <?= $this->formRow($form->get('customer')->get('birthTown')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname">Via e numero civico</label>
                            <?= $this->formRow($form->get('customer')->get('address')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="gender">Informazioni aggiuntive</label>
                            <?= $this->formRow($form->get('customer')->get('addressInfo')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name">CAP</label>
                            <?= $this->formRow($form->get('customer')->get('zipCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="surname">Città</label>
                            <?= $this->formRow($form->get('customer')->get('town')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="language">Lingua preferita</label>
                            <?= $this->formRow($form->get('customer')->get('language')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="taxCode">Codice fiscale</label>
                            <?= $this->formRow($form->get('customer')->get('taxCode')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="vat">Partita IVA (opzionale)</label>
                            <?= $this->formRow($form->get('customer')->get('vat')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="mobile">Cellulare</label>
                            <?= $this->formRow($form->get('customer')->get('mobile')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="phone">Telefono</label>
                            <?= $this->formRow($form->get('customer')->get('phone')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="id">Id</label>
                            <?php $idElement = $form->get('customer')->get('id');
                                $idElement->setAttributes(['type'=>'text','readonly'=>'true','class'=>'form-control']);
                            ?>
                            <?= $this->formRow($idElement); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Dati Patente</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicense">Patente</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicense')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseAuthority">Rilasciato da (autorità)</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseAuthority')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseReleaseDate">Rilasciato il</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseReleaseDate')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName">Nome sulla patente</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseName')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseName">Cognome sulla patente</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseSurname')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseCountry">Rilasciata da (nazione)</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseCountry')->setAttribute('disabled', 'true')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseExpire">Data di scadenza</label>
                            <?= $this->formRow($formDriver->get('driver')->get('driverLicenseExpire')->setAttribute('readonly', 'true')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading">Altri dati</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Abilitato</label>
                            <?php if($this->customer->getEnabled()): ?>
                                <div class="alert alert-success">Abilitato</div>
                            <?php else: ?>
                                <div class="alert alert-danger">Non Abilitato</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Stato Iscrizione</label>
                            <?php if($this->customer->getRegistrationCompleted()): ?>
                                <div class="alert alert-success">Registrazione Confermata</div>
                            <?php else: ?>
                                <div class="alert alert-danger">Registrazione Non Confermata</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Stato Primo Pagamento</label>
                            <?php if($this->customer->getFirstPaymentCompleted()): ?>
                                <div class="alert alert-success">Pagamento Effettuato</div>
                            <?php else: ?>
                                <div class="alert alert-danger">Pagamento Non Ancora Effettuato</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Percentuale Sconto</label>
                            <h1 class="text-center"><?= is_null($this->customer->getDiscountRate()) ? '0' : $this->customer->getDiscountRate(); ?>%</h1>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender">Data/Ora</label>
                            <h4>Iscrizione:<br><?= is_object($this->customer->getInsertedTs()) ? $this->customer->getInsertedTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                            <h4><?= is_object($this->customer->getUpdateTs()) ? 'Ultima Modifica: ' . $this->customer->getUpdateTs()->format('d-m-Y - H:i:s') : ''; ?></h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="maintainer">Maintainer</label>
                            <?php if($this->customer->getMaintainer()): ?>
                                <div class="alert alert-success">Si</div>
                            <?php else: ?>
                                <div class="alert alert-danger">No</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="goldList">Gold List</label>
                            <?php if($this->customer->getGoldList()): ?>
                                <div class="alert alert-success">Si</div>
                            <?php else: ?>
                                <div class="alert alert-danger">No</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>
