<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p>Operazione eseguita con successo</p>
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- Filter container -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">

                            <!-- Filter selector -->
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- Seleziona --</option>
                                    <option value="e.invoiceNumber">N° Fattura</option>
                                    <!-- <option value="e.type">Tipo</option> -->
                                </select>
                            </div>
                            <!-- filter selector -->

                            <!-- Type selector -->
                            <div class="form-group">
                                <select name="js-clean-type" id="js-clean-type" class="form-control" style="display: none;">
                                    <option value="FIRST_PAYMENT">Iscrizione</option>
                                    <option value="TRIP">Corsa</option>
                                    <option value="PENALTY">Sanzione</option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="Filtra...">
                            </div>
                            <!-- type selector -->

                            <!-- Search buttons -->
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> Cerca
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> Pulisci Ricerca
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- search buttons -->

                        </div>
                    </div>
                </div>
                <!-- filter container -->

                <hr>

                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>Elenco Fatture
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-invoices-table">
                            <thead>
                            <tr>
                                <th>N° Fattura</th>
                                <th>Data</th>
                                <th>Tipo</th>
                                <th>Totale</th>
                                <th>Download</th>
                            </tr>
                            </thead>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- datatable container -->

            </div>
        </div>
    </div>
</div>

<script>
var customerId = "<?= $this->customer->getId() ?>";
</script>
<script type="text/javascript" src="<?= $this->basePath() ?>/js/invoices.js"></script>
