<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p><?= $this->translate("Operazione eseguita con successo"); ?></p>
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- Filter container -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">

                            <!-- Filter selector -->
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.invoiceNumber"><?= $this->translate("N° Fattura"); ?></option>
                                    <!-- <option value="e.type">Tipo</option> -->
                                </select>
                            </div>
                            <!-- filter selector -->

                            <!-- Type selector -->
                            <div class="form-group">
                                <select name="js-clean-type" id="js-clean-type" class="form-control" style="display: none;">
                                    <option value="FIRST_PAYMENT"><?= $this->translate("Iscrizione"); ?></option>
                                    <option value="TRIP"><?= $this->translate("Corsa"); ?></option>
                                    <option value="PENALTY"><?= $this->translate("Sanzione"); ?></option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <!-- type selector -->

                            <!-- Search buttons -->
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- search buttons -->

                        </div>
                    </div>
                </div>
                <!-- filter container -->

                <hr>

                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Fatture"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-invoices-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("N° Fattura"); ?></th>
                                <th><?= $this->translate("Data"); ?></th>
                                <th><?= $this->translate("Tipo"); ?></th>
                                <th><?= $this->translate("Totale"); ?></th>
                                <th><?= $this->translate("Download"); ?></th>
                            </tr>
                            </thead>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- datatable container -->

            </div>
        </div>
    </div>
</div>

<script>
var customerId = "<?= $this->customer->getId(); ?>";
var pdfPath = "<?= $this->url('pdf/invoices'); ?>/";
</script>
<script type="text/javascript" src="<?= $this->basePath() ?>/js/customer-invoices.js"></script>
