<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() .'/js/customers.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?php echo $this->translate("ELENCO CLIENTI"); ?> <small><?php echo $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?php echo $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.id"><?php echo $this->translate("Id"); ?></option>
                                    <option value="e.surname"><?php echo $this->translate("Cognome"); ?></option>
                                    <option value="e.taxCode"><?php echo $this->translate("Codice Fiscale"); ?></option>
                                    <option value="e.driverLicense"><?php echo $this->translate("Patente"); ?></option>
                                    <option value="e.phone"><?php echo $this->translate("Cellulare"); ?></option>
                                    <option value="e.town"><?php echo $this->translate("Città"); ?></option>
                                    <option value="cc.code"><?php echo $this->translate("Codice Card"); ?></option>
                                    <option value="e.email"><?php echo $this->translate("Email"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?php echo $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> <?php echo $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?php echo $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">

                            <?php echo $this->translate("Elenco clienti"); ?>

                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-customers-table">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate("Id"); ?></th>
                                <th><?php echo $this->translate("Nome"); ?></th>
                                <th><?php echo $this->translate("Cognome"); ?></th>
                                <th><?php echo $this->translate("Cellulare"); ?></th>
                                <th><?php echo $this->translate("Card"); ?></th>
                                <th><?php echo $this->translate("Patente"); ?></th>
                                <th><?php echo $this->translate("Scadenza Patente"); ?></th>
                                <th><?php echo $this->translate("Email"); ?></th>
                                <th><?php echo $this->translate("Codice Fiscale"); ?></th>
                                <th><?php echo $this->translate("Registrazione"); ?></th>
                                <th><?php echo $this->translate("Azioni"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
