<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/cards.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            ELENCO CARD <small>ricerca</small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <div class="row">
                    <div class="col-md-8">

                    </div>
                    <div class="col-md-4">
                        <a href="<?= $this->url('customers/list-card/add'); ?>" class="btn green pull-right"><i class="fa fa-plus"></i> Aggiungi Card</a>
                    </div>
                </div>

                <br />

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            Elenco card
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-cards-table">
                            <thead>
                            <tr>
                                <th>Code</th>
                                <th>Is_assigned</th>
                                <th>Notes</th>
                                <th>Assignable</th>
                                <th>Utente</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
