<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p>Operazione eseguita con successo</p>
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i>Elenco Note
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table id="notes-table" class="table table-striped table-bordered table-hover" id="js-invoices-table">
                            <thead>
                                <tr>
                                    <th>Data</th>
                                    <th>Utente</th>
                                    <th>Nota</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->notes as $note): ?>
                                <tr>
                                    <td><?= $note->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                    <td><?= $note->getWebuser()->getId(); ?></td>
                                    <td><?= $note->getNote(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#notes-table').DataTable();
} );
</script>
