<?php
$this->headScript()->appendFile($this->basePath() .'/js/extra-payments.js?v=1.6');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- TITLE -->
        <h3 class="page-title"><?= $this->translate("ADDEBITI EXTRA/PENALI"); ?></h3>

        <!-- BEGIN TOP INPUT ROW -->
        <div class="row">

            <!-- INPUT CUSTOMER ID -->
            <div class="col-lg-2">
                <label><?= $this->translate("Id Cliente"); ?></label>
                <input id="customer" class="form-control" type="text">
            </div>

            <!-- SELECT FLEET -->
            <div class="col-lg-2">
                <label><?= $this->translate("Flotta"); ?></label>
                <select id="fleet" class="form-control">
                    <option id="fleet-option-null">---</option>
                    <?php foreach ($this->fleets as $fleet): ?>
                    <option value="<?= $fleet->getId() ?>"><?= $fleet->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <!-- SELECT TYPE -->
            <div class="col-lg-2">
                <label><?= $this->translate("Tipologia"); ?></label>
                <select id="type" class="form-control">
                    <option id="type-option-null">---</option>
                    <?php foreach ($this->types as $type): ?>
                    <option value="<?= $type ?>"><?= $type ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <!-- END TOP INPUT ROW -->

        <!-- PAYMENT ROWS CONTAINER -->
        <div id="payment-rows"></div>

        <!-- ADD PAYMENT ROW BUTTON -->
        <!-- 
        <div class="row sng-margin-top">
            <div class="col-lg-2">
                <button id="js-add-row" class="sng-green-btn"></i> <?= $this->translate("Aggiungi addebito"); ?></button>
            </div>
        </div>
        -->

        <!-- SUBMIT BUTTON -->
        <div class="row sng-margin-top">
            <div class="col-lg-12 sng-margin-top">
                <button id="js-extra-payment" class="btn btn-success sng-faded"><?= $this->translate("Effettua pagamento"); ?></button>
            </div>
        </div>

        <div id="extraTries" style="display:none">
            <hr>
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i><?= $this->translate("Risultato tentativo effettuato"); ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th><?= $this->translate("Data del tentativo"); ?></th>
                                <th><?= $this->translate("Utente Admin"); ?></th>
                                <th><?= $this->translate("Prodotto"); ?></th>
                                <th><?= $this->translate("Esito"); ?></th>
                                <th><?= $this->translate("Risultato"); ?></th>
                                <th><?= $this->translate("Messaggio"); ?></th>
                                <th><?= $this->translate("Costo"); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td id='date'></td>
                                <td id='webuser'></td>
                                <td id='product'></td>
                                <td id='outcome'></td>
                                <td id='result'></td>
                                <td id='message'></td>
                                <td id='amount'></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
var causalOptions = "";
$('#type').change(function() {
    if($('#type').val() == "extra"){
        <?php
        echo 'causalOptions = "';
        echo '<option>Non definito</option>';
        foreach($this->causal as $causal) {
            echo '<option data-reason=\"' . $causal->getReason() . '\">' .
                $causal->getReason() .
                '</option>';
        }
        echo '"';
        ?>
    }
});
    
function deactivate(e)
{
    if (!confirm(translate("deactivateUser"))) {
        e.preventDefault();
    }
}


<?php
/**
 * This code creates a js variable that holds all the options for the penalties
 * selector. The generated variable contains a string that is ready to be added
 * to the html of a selector.
 */
echo 'var penaltyOptions = "';
echo '<option></option>';
foreach($this->penalties as $penalty) {
    echo '<option data-reason=\"' . $penalty->getReason() . '\" data-amount=\"' . $penalty->getAmount() . '\">' .
        $penalty->getReason() . ' (' .number_format($penalty->getAmount()/100, 2) . '\u20ac)' .
        '</option>';
}
echo '"';
?>
</script>
