<?php
$this->headScript()
    ->appendFile($this->basePath() .'/js/extra-payments.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <h3 class="page-title">
            ADDEBITI EXTRA/PENALI
        </h3>

        <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-lg-2">
                    <div class="form-group">
                        <label for="customerId">Id Cliente</label>
                        <?= $this->formRow($form->get('extra')->get('customerId')); ?>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="form-group">
                        <label for="paymentType">Tipologia</label>
                        <?= $this->formRow($form->get('extra')->get('paymentType')); ?>
                    </div>
                </div>
            </div>

            <div class="row">
                <div id="penaltyField" class="col-lg-12">
                    <div class="form-group">
                        <label for="penalty">Penale</label>
                        <select id="penalty" name="penalty" class="form-control">
                            <option>---</option>
                            <?php foreach($this->penalties as $penalty): ?>
                                <option data-reason="<?= $penalty->getReason()?>" data-amount="<?= $penalty->getAmount() ?>">
                                    <?= $penalty->getReason() ?> (<?= number_format($penalty->getAmount()/100, 2) ?> &euro;)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="reason">Causale</label>
                        <?= $this->formRow($form->get('extra')->get('reason')); ?>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="amount">Importo (&euro;)</label>
                        <?= $this->formRow($form->get('extra')->get('amount')); ?>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <button id="js-extra-payment" type="submit" class="btn btn-success">Effettua pagamento</button>
                </div>
            </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
