<?php
$this->headLink()
        ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
        ->appendStylesheet('/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() . '/js/datatable-session-data.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() .'/js/failed-payments.js?v=1.1');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("PAGAMENTI FALLITI"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>
        <div class="page-bar">
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="cu.surname"><?= $this->translate("Cognome"); ?></option>
                                    <option value="cu.id"><?= $this->translate("ID Cliente"); ?></option>
                                    <option value="e.firstPaymentTryTs"><?= $this->translate("Data pagamento"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco pagamenti falliti"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-payments-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Data pagamento"); ?></th>
                                <th><?= $this->translate("ID cliente"); ?></th>
                                <th><?= $this->translate("Nome"); ?></th>
                                <th><?= $this->translate("Cognome"); ?></th>
                                <th><?= $this->translate("Cellulare"); ?></th>
                                <th><?= $this->translate("Email"); ?></th>
                                <th><?= $this->translate("ID Corsa"); ?></th>
                                <th><?= $this->translate("Corsa"); ?></th>
                                <th><?= $this->translate("Parcheggio"); ?></th>
                                <th><?= $this->translate("Sconto"); ?></th>
                                <th><?= $this->translate("Costo"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var filters = <?= $this->filters ?>;
</script>