<?php
$form = $this->faresForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <h3 class="page-title">
            TARIFFE
        </h3>
        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

        <?= $this->form()->openTag($form); ?>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="reason">Soglia Tariffaria 60 min</label>
                    <?= $this->formRow($form->get('fares')->get('costStep60')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="reason">Soglia Tariffaria 240 min</label>
                    <?= $this->formRow($form->get('fares')->get('costStep240')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="reason">Soglia Tariffaria 1440 min</label>
                    <?= $this->formRow($form->get('fares')->get('costStep1440')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <button id="submit" type="submit" class="btn btn-success">Salva tariffe</button>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>