<?php
$form = $this->faresForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <h3 class="page-title">
            <?= $this->translate("TARIFFE"); ?>
        </h3>
        <?= $this->partial('partials/flash-messages.phtml', []); ?>

        <?= $this->form()->openTag($form); ?>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="reason"><?= $this->translate("Soglia Tariffaria 60 min"); ?></label>
                    <?= $this->formRow($form->get('fares')->get('costStep60')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="reason"><?= $this->translate("Soglia Tariffaria 1440 min"); ?></label>
                    <?= $this->formRow($form->get('fares')->get('costStep1440')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <button id="submit" type="submit" class="btn btn-success"><?= $this->translate("Salva tariffe"); ?></button>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>