<?php

setlocale(LC_TIME, 'it_IT.UTF-8');
$daily = $this->daily;

?>

<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Title -->
        <h3 class="page-title"><?= $this->translate("COMPETENZE"); ?></h3>
        <!-- BEGIN tabs container -->
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span6">

                    <?php if($this->roles[0]==="superadmin") { ?>
                    <!-- BEGIN tabs -->
                    <div class="tabbable tabbable-custom">

                        <!-- BEGIN tabs headers -->
                        <ul class="nav nav-tabs">
                            <li <?= ($tab == 1)?'class="active"':''; ?>><a href="" id="tab_1"><?= $this->translate("Riepilogo giornaliero"); ?></a></li>
                            <li <?= ($tab == 2)?'class="active"':''; ?>><a href="" id="tab_2"><?= $this->translate("Riepilogo mensile"); ?></a></li>
                        </ul>
                        <!-- END tabs headers -->

                        <div class="tab-content">

                            <!-- BEGIN daily tab -->
                            <div class="tab-pane <?= ($tab == 1)?'active':''; ?>" id="tab_1_1">
                                <form action="<?= $this->url('payments/recap'); ?>?tab=1" method="POST">
                                    <select id="fleet-selector1" name="fleet">
                                        <?php foreach($this->fleets as $id => $fleet): ?>
                                            <option value="<?= $id ?>" <?= ($id == $this->selectedFleet)?'selected':''; ?> ><?= $fleet ?></option>
                                        <?php endforeach; ?>
                                    </select>

                                    <input id="day-selector1" type="date" name="day" value="<?= $this->selectDay; ?>" max="<?= $this->max_day; ?>">
                                    
                                    <input type="submit" value="<?= $this->translate("Cerca"); ?>">
                                </form>
                                <table class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th class="sng-date-column"><?= $this->translate("Data"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Viaggi"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Iscrizioni"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Multe e penali"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Pacchetti"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Totale"); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody id="daily-body">
                                        <?php foreach($daily as $day => $amount): ?>
                                            <tr>
                                                <td><?= $day ?></td>
                                                
                                                
                                                <td class="sng-dt-right"><?= number_format($amount['tp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['sp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['ep_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['bpp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['amount'] / 100, 0, '.', ','); ?></td>
                                                
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <!-- END daily tab -->

                            <!-- BEGIN monthly tab -->
                            <div class="tab-pane <?= ($tab == 2)?'active':''; ?>" id="tab_1_2">
                                
                                <form action="<?= $this->url('payments/recap'); ?>?tab=2" method="POST">
                                    <select id="fleet-selector2" name="fleet2">
                                        <?php foreach($this->fleets as $id => $fleet): ?>
                                            <option value="<?= $id ?>" <?= ($id == $this->selectedFleet2)?'selected':''; ?> ><?= $fleet ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                    
                                    <input id="month-selector" type="month" name="month" value="<?= $this->selectMonth; ?>" max="<?= $this->max_month; ?>">
                                    
                                    <input type="submit" value="<?= $this->translate("Cerca"); ?>">
                                </form>
                                
                                <table class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th class="sng-date-column"><?= $this->translate("Data"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Viaggi"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Iscrizioni"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Multe e penali"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Pacchetti"); ?></th>
                                            <th class="sng-text-right"><?= $this->translate("Totale"); ?></th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach($monthly as $month => $amount):
                                            $month = date_create_from_format("Y-m", $month);
                                            $month = strftime("%B %G", $month->getTimestamp());
                                        ?>
                                            <tr>
                                                <td><?= $month ?></td>
                                                
                                                <td class="sng-dt-right"><?= number_format($amount['tp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['sp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['ep_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['bpp_amount'] / 100, 0, '.', ','); ?></td>
                                                <td class="sng-dt-right"><?= number_format($amount['amount'] / 100, 0, '.', ','); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <!-- END monthly tab -->

                        </div>
                    </div>
                    <!-- END tabs -->
                    <?php }
                    else {
                        echo ($this->translate("Attenzione! Area riservata agli utenti super-admin."));
                    }
                    ?>
                </div>

            </div>
        </div>
        <!-- END tabs container -->

    </div>
</div>

<?php
setlocale(LC_TIME, 'en_EN.UTF-8');
?>

<!-- JavaScript -->
<script type="text/javascript">
var reloadUrl = "<?= $this->url('payments/recap'); ?>";
</script>
<script type="text/javascript" src="<?= $this->basePath(); ?>/js/payments-recap.js"></script>
