<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/retry-extra.js');
?>

<?php
$extraPayment = $this->extraPayment;
$customer = $this->customer;
?>

<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("RITENTA PAGEMENTO DI UN EXTRA"); ?>
        </h3>
        
        <?php if($extraPayment->getStatus() == 'wrong_payment' || $extraPayment->getStatus() == 'to_be_payed'){ ?>
        <div class="row">
            <div class="col-md-8">
                <div class="form-inline">
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-new-try">
                            <i class="fa fa-try"></i>
                            <?= $this->translate("Effettua nuovo tentativo di pagamento"); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php } else { ?>
            <hr>
            <h4><span class="glyphicon glyphicon-ok"></span> Pagamento avvenuto con successo</h4>
        <?php } ?>

        <div class="row hidden" id="js-refused-message">
            <div class="col-md-12">
                <div class="alert alert-warning">
                    <strong><?= $this->translate("Il pagamento non è andato a buon fine"); ?> <span id="js-wrong-reason"></span></strong>
                </div>
            </div>
        </div>

        <hr>
        
        <!-- Details table -->
        <div class="row">
            <div class="col-lg-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-server"></i><?= $this->translate("Riepilogo"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID Cliente"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getId() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Email"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getEmail() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Nome"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getName() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Cognome"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getSurname() ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Cellulare"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getMobile() ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Data"); ?></label>
                                    <div class="sng-info-box"><?= $extraPayment->getGeneratedTs()->format('Y-m-d H:i:s') ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Data primo tentativo"); ?></label>
                                    <?php if(!is_null($extraPayment->getFirstExtraTryTs())){ ?>
                                        <div class="sng-info-box"><?= $extraPayment->getFirstExtraTryTs()->format('Y-m-d H:i:s') ?></div>
                                    <?php }else{ ?>
                                        <div class="sng-info-box"> Non ancora effettuato </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Costo"); ?></label>
                                    <div class="sng-info-box"><?= $extraPayment->getFormattedTotalCost() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Tipologia"); ?></label>
                                    <div class="sng-info-box"><?= $extraPayment->getPaymentType() ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Reason"); ?></label>
                                    <?php
                                    $as = '';
                                    foreach ($extraPayment->getReasons() as $reason){
                                        $as .= $reason[0][0] . ' || ';
                                    }
                                    ?> 
                                    <div class="sng-info-box"><?= rtrim($as,' || ') ?></div>
                                </div>
                            </div>
                            
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Stato"); ?></label>
                                    <div class="sng-info-box"><?= $extraPayment->getStatus() ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- details table -->
        
        <!-- Retries list table -->
        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco tentativi effettuati"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-extra-table">
                            <thead>
                                <tr>
                                    <th><?= $this->translate("Data del tentativo"); ?></th>
                                    <th><?= $this->translate("Utente Admin"); ?></th>
                                    <th><?= $this->translate("Prodotto"); ?></th>
                                    <th><?= $this->translate("Esito"); ?></th>
                                    <th><?= $this->translate("Risultato"); ?></th>
                                    <th><?= $this->translate("Messaggio"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->extraPaymentTries as $try): ?>
                                    <tr>
                                        <td><?= $try->getTs()->format('Y-m-d H:i:s') ?></td>
                                        <td><?= $try->getWebuserName() ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getProductType() : 'n.d.' ?></td>
                                        <td><?= $try->getOutcome() ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getOutcome() : 'n.d.'  ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getMessage() : 'n.d.'  ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- retries list table -->

        <!-- END PAGE CONTENT-->
        
    </div>
</div>
<script>
    var extraPaymentId = "<?= $this->extraPayment->getId() ?>",
        retryUrl = "<?= $this->url('payments/do-retry-extra', ['id' => $this->extraPayment->getId()], ['force_canonical' => true]) ?>",
        abilitateUrl = "<?= $this->url('customers/reactivate', ['id' => $this->customer->getId()], ['force_canonical' => true]) ?>",
        listUrl = "<?= $this->url('payments/failed-payments', [], ['force_canonical' => true]) ?>";
</script>
