<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->headLink()->appendStylesheet('/css/addons.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/retry-payment.js');
?>

<?php
$tripPayment = $this->tripPayment;
$customer = $this->customer;
?>

<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            RITENTA PAGAMENTO
        </h3>

        <div class="row">
            <div class="col-md-8">
                <div class="form-inline">
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-new-try">
                            <i class="fa fa-try"></i>
                            Effettua nuovo tentativo di pagamento
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row hidden" id="js-completed-message">
            <div class="col-md-12">
                <div class="alert alert-success">
                    <strong>Pagamento completato con successo</strong>
                </div>
                <div class="form-inline">
                    <div class="form-group col-sm-2 text-center">
                        <label for="send-mail">Inviare mail di notifica</label>
                        <input type="checkbox" name="send-mail" id="send-mail" checked="checked">
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-abilitate-customer">
                            <i class="fa fa-caret-square-o-right"></i>
                            Riabilita utente
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row hidden" id="js-refused-message">
            <div class="col-md-12">
                <div class="alert alert-warning">
                    <strong>Il pagamento non è andato a buon fine <span id="js-wrong-reason"></span></strong>
                </div>
            </div>
        </div>

        <hr>

        <!-- Details table -->
        <div class="row">
            <div class="col-lg-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-server"></i>Riepilogo
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>ID Corsa</label>
                                    <div class="sng-info-box"><?= $tripPayment->getTrip()->getId() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Data</label>
                                    <div class="sng-info-box"><?= $tripPayment->getCreatedAt()->format("d-m-Y H:i:s") ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <div class="sng-info-box"><?= $customer->getName() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Cognome</label>
                                    <div class="sng-info-box"><?= $customer->getSurname() ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Corsa</label>
                                    <div class="sng-info-box"><?= $tripPayment->getTripMinutes() . " min." ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Parcheggio</label>
                                    <div class="sng-info-box"><?= $tripPayment->getParkingMinutes() . " min." ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Sconto</label>
                                    <div class="sng-info-box"><?= $tripPayment->getDiscountPercentage() . "%" ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Costo</label>
                                    <div class="sng-info-box"><?= $tripPayment->getFormattedTotalCost() ?></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- details table -->

        <!-- Retries list table -->
        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>Elenco tentativi effettuati
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-payments-table">
                            <thead>
                                <tr>
                                    <th>Data del tentativo</th>
                                    <th>Utente Admin</th>
                                    <th>Prodotto</th>
                                    <th>Esito</th>
                                    <th>Risultato</th>
                                    <th>Messaggio</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->tripPaymentTries as $try): ?>
                                    <tr>
                                        <td><?= $try->getTs()->format('Y-m-d H:i:s') ?></td>
                                        <td><?= $try->getWebuserName() ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getProductType() : 'n.d.' ?></td>
                                        <td><?= $try->getOutcome() ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getOutcome() : 'n.d.'  ?></td>
                                        <td><?= (null != $try->getTransaction()) ? $try->getTransaction()->getMessage() : 'n.d.'  ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- retries list table -->

        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var tripPaymentId = "<?= $tripPayment->getId() ?>",
        retryUrl = "<?= $this->url('payments/do-retry', ['id' => $tripPayment->getId()], ['force_canonical' => true]) ?>",
        abilitateUrl = "<?= $this->url('customers/activate', ['id' => $customer->getId()], ['force_canonical' => true]) ?>";
</script>
