<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/retry-payment.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            RITENTA PAGAMENTO
        </h3>

        <div class="row">
            <div class="col-md-8">
                <div class="form-inline">
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-new-try">
                            <i class="fa fa-try"></i>
                            Effettua nuovo tentativo di pagamento
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row hidden" id="js-completed-message">
            <div class="col-md-12">
                <div class="alert alert-success">
                    <strong>Pagamento completato con successo</strong>
                </div>
                <div class="form-inline">
                    <div class="form-group col-sm-2 text-center">
                        <label for="send-mail">Inviare mail di notifica</label>
                        <input type="checkbox" name="send-mail" id="send-mail" checked="checked">
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-abilitate-customer">
                            <i class="fa fa-caret-square-o-right"></i>
                            Riabilita utente
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row hidden" id="js-refused-message">
            <div class="col-md-12">
                <div class="alert alert-warning">
                    <strong>Il pagamento non è andato a buon fine <span id="js-wrong-reason"></span></strong>
                </div>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>Elenco tentativi effettuati
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-payments-table">
                            <thead>
                                <tr>
                                    <th>Data del tentativo</th>
                                    <th>Utente</th>
                                    <th>Esito</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->tripPaymentTries as $try): ?>
                                    <tr>
                                        <td><?= $try->getTs()->format('Y-m-d H:i:s') ?></td>
                                        <td><?= $try->getWebuserName() ?></td>
                                        <td><?= $try->getOutcome() ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var tripPaymentId = "<?= $this->tripPayment->getId() ?>",
        retryUrl = "<?= $this->url('payments/do-retry', ['id' => $this->tripPayment->getId()], ['force_canonical' => true]) ?>",
        abilitateUrl = "<?= $this->url('customers/activate', ['id' => $this->customer->getId()], ['force_canonical' => true]) ?>";

</script>