<script>
    var translations = {
        "Spostati su": "<?= $this->translate('Spostati su') ?>",

        // map.js
        "Passa a Posizione di Arrivo": '<?= $this->translate("Passa a Posizione di Arrivo") ?>',
        "Passa a Posizione di Partenza": '<?= $this->translate("Passa a Posizione di Partenza") ?>',

        // menu.js
        "Corse per Citt&agrave;": '<?= $this->translate("Corse per Citt&agrave;") ?>',
        "Roma" : '<?= $this->translate("Roma") ?>',
        "Milano" : '<?= $this->translate("Milano") ?>',
        "Firenze" : '<?= $this->translate("Firenze") ?>',
        "Modena" : '<?= $this->translate("Modena") ?>',
        "Dummy fleet" : '<?= $this->translate("Dummy fleet") ?>',

        // routes.js
        "corse precedenti a" : '<?= $this->translate("corse precedenti a") ?>',
        "Targa Veicolo" : '<?= $this->translate("Targa Veicolo") ?>',
        "Durata" : '<?= $this->translate("Durata") ?>',
        "Numero Punti" : '<?= $this->translate("Numero Punti") ?>',
        "Data Inizio Corsa" : '<?= $this->translate("Data Inizio Corsa") ?>',
        "Data Fine Corsa" : '<?= $this->translate("Data Fine Corsa") ?>',
        "Itinerario" : '<?= $this->translate("Itinerario") ?>',
        "Non sono state trovate corse con i filtri selezionati" : '<?= $this->translate("Non sono state trovate corse con i filtri selezionati") ?>',
        "Controlli" : '<?= $this->translate("Controlli") ?>',
        "Ferma" : '<?= $this->translate("Ferma") ?>',
        "Pausa" : '<?= $this->translate("Pausa") ?>',
        "Avvia" : '<?= $this->translate("Avvia") ?>',
        "Velocit&agrave;" : '<?= $this->translate("Velocit&agrave;") ?>',
        "Data Rilevazione Punto" : '<?= $this->translate("Data Rilevazione Punto") ?>',
        "Blocca Vista su Auto" : '<?= $this->translate("Blocca Vista su Auto") ?>',
        "Durata Corsa" : '<?= $this->translate("Durata Corsa") ?>',
        "Apri" : '<?= $this->translate("Apri") ?>',

        // trips.city.js / trips.js
        "Lunedi" : '<?= $this->translate("Lunedi") ?>',
        "Martedi" : '<?= $this->translate("Martedi") ?>',
        "Mercoledi" : '<?= $this->translate("Mercoledi") ?>',
        "Giovedi" : '<?= $this->translate("Giovedi") ?>',
        "Venerdi" : '<?= $this->translate("Venerdi") ?>',
        "Sabato" : '<?= $this->translate("Sabato") ?>',
        "Domenica" : '<?= $this->translate("Domenica") ?>',
        "oltre" : '<?= $this->translate("oltre") ?>',
        "Uomini" : '<?= $this->translate("Uomini") ?>',
        "Donne" : '<?= $this->translate("Donne") ?>',
        "Area" : '<?= $this->translate("Area") ?>',
        "Concentrazione" : '<?= $this->translate("Concentrazione") ?>',
        "selezionate di" : '<?= $this->translate("selezionate di") ?>',
        "corse" : '<?= $this->translate("corse") ?>',
        "Azzera tutti i filtri" : '<?= $this->translate("Azzera tutti i filtri") ?>',
        "Tutte le" : '<?= $this->translate("Tutte le") ?>',
        "corse sono selezionate. Clicca su uno dei grafici per applicarne dei filtri." : '<?= $this->translate("corse sono selezionate. Clicca su uno dei grafici per applicarne dei filtri.") ?>',
    };

    function translate(key) {
        return translations[key];
    }
</script>
