<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/pois.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO POIS"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.id"><?= $this->translate("Id"); ?></option>
                                    <option value="e.type"><?= $this->translate("Tipo"); ?></option>
                                    <option value="e.code"><?= $this->translate("Codice"); ?></option>
                                    <option value="e.name"><?= $this->translate("Nome"); ?></option>
                                    <option value="e.address"><?= $this->translate("Indirizzo"); ?></option>
                                    <option value="e.town"><?= $this->translate("Città"); ?></option>
                                    <option value="e.zipCode"><?= $this->translate("CAP"); ?></option>
                                    <option value="e.province"><?= $this->translate("Provincia"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <a href="<?= $this->url('configurations/manage-pois/add'); ?>" class="btn green pull-right">
                            <i class="fa fa-plus"></i> <?= $this->translate("Aggiungi POIS"); ?>
                        </a>
                    </div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco POIS"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-pois-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Id"); ?></th>
                                <th><?= $this->translate("Tipo."); ?></th>
                                <th><?= $this->translate("Codice"); ?></th>
                                <th><?= $this->translate("Nome"); ?></th>
                                <th><?= $this->translate("Indirizzo"); ?></th>
                                <th><?= $this->translate("Città"); ?></th>
                                <th><?= $this->translate("CAP"); ?></th>
                                <th><?= $this->translate("Provincia"); ?></th>
                                <th><?= $this->translate("Azione"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>