<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/pois.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?php echo $this->translate("ELENCO POIS"); ?> <small><?php echo $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?php echo $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.id"><?php echo $this->translate("Id"); ?></option>
                                    <option value="e.type"><?php echo $this->translate("Tipo"); ?></option>
                                    <option value="e.code"><?php echo $this->translate("Codice"); ?></option>
                                    <option value="e.name"><?php echo $this->translate("Nome"); ?></option>
                                    <option value="e.address"><?php echo $this->translate("Indirizzo"); ?></option>
                                    <option value="e.town"><?php echo $this->translate("Città"); ?></option>
                                    <option value="e.zipCode"><?php echo $this->translate("CAP"); ?></option>
                                    <option value="e.province"><?php echo $this->translate("Provincia"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?php echo $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?php echo $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?php echo $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <a href="<?= $this->url('configurations/manage-pois/add'); ?>" class="btn green pull-right">
                            <i class="fa fa-plus"></i> <?php echo $this->translate("Aggiungi POIS"); ?>
                        </a>
                    </div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?php echo $this->translate("Elenco POIS"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-pois-table">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate("Id"); ?></th>
                                <th><?php echo $this->translate("Tipo."); ?></th>
                                <th><?php echo $this->translate("Codice"); ?></th>
                                <th><?php echo $this->translate("Nome"); ?></th>
                                <th><?php echo $this->translate("Indirizzo"); ?></th>
                                <th><?php echo $this->translate("Città"); ?></th>
                                <th><?php echo $this->translate("CAP"); ?></th>
                                <th><?php echo $this->translate("Provincia"); ?></th>
                                <th><?php echo $this->translate("Azione"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>