<div class="page-content-wrapper">
    <div class="page-content">

        <h3 class="page-title">
            <?php echo $this->translate("Accesso negato"); ?>
        </h3>

        <p><?php echo $this->translate("Non sei autorizzato ad accedere a questa risorsa."); ?></p>

        <hr />

        <p><?php echo $this->translate("Se ritieni che questa pagina sia comparsa per errore, ti preghiamo di segnalarlo all'assistenza tecnica. Grazie."); ?></p>

    </div>
</div>

