<?php
$form = $this->carForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("AGGIUNGI AUTO"); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('cars'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>


        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->form()->openTag($form); ?>

                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Targa"); ?></label>
                            <?php
                            $plate = $form->get('car')->get('plate');
                            echo $this->formElement($plate);
                            echo $this->formElementErrors($plate, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Costruttore"); ?></label>
                            <?php
                            $manufactures = $form->get('car')->get('manufactures');
                            echo $this->formElement($manufactures);
                            echo $this->formElementErrors($manufactures, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Modello"); ?></label>
                            <?php
                            $model = $form->get('car')->get('model');
                            echo $this->formElement($model);
                            echo $this->formElementErrors($model, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Identificativo"); ?></label>
                            <?php
                            $label = $form->get('car')->get('label');
                            echo $this->formElement($label);
                            echo $this->formElementErrors($label, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Flotta"); ?></label>
                            <?= $this->formRow($form->get('car')->get('fleet')); ?>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Attiva"); ?></label>
                            <?= $this->formRow($form->get('car')->get('active')); ?>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="surname"><?= $this->translate("Stato"); ?></label>
                            <?= $this->formRow($form->get('car')->get('status')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="gender"><?= $this->translate("Note"); ?></label>
                            <?= $this->formRow($form->get('car')->get('notes')); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success"><?= $this->translate("Aggiungi Auto"); ?></button>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>

            </div>
        </div>

    </div>
</div>