<h4>Esegui comandi sull'auto</h4>

<?php echo $this->partial('partials/flash-messages.phtml', []); ?>

<div class="btn-group">
    <button type="button" class="btn btn-default"><?= $this->translate("Seleziona..."); ?></button>
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
    <ul class="dropdown-menu" role="menu" id="menu">
        <?php foreach ($this->commands as $key => $command): ?>
            <li>
                <a onclick="callController(<?= $key ?>)">
                    <?= $command; ?>
                </a>

            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php

function abcfd() {
    
}
?>


<script>

    var callController = function (key) {
        var RFID = null;
        if (key == 13) {
            var txt_message = prompt("Inserire RFID", "");
            RFID = txt_message;
        } else {
            confirm('<?= $this->translate("Sei sicuro di voler eseguire questo comando?"); ?>');
        }
        //ajax call
        var plate = "<?= $this->car->getPlate(); ?>";
        $.ajax({
            url: "/cars/send-command/" +plate+ "/" +key+ "/"+RFID,
        });

    }

</script>