<?php
$form = $this->carForm->prepare();
$form->setAttribute('action', $this->url('cars/ajax-tab-edit', ['plate' => $this->car->getPlate()]));
$form->get('car')->get('fleet')->setValue($this->car->getFleet()->getId());
?>
<div class="row">
    <div class="col-md-12">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender"><?= $this->translate("Targa"); ?></label>
                    <?= $this->formRow($form->get('car')->get('plate')->setAttribute('disabled', 'disabled')); ?>
                </div>
            </div>
            <div class="col-lg-1">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Stato"); ?></label><br />
                    <?= $this->CarStatus($form->get('car')->get('status')->getValue()); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name"><?= $this->translate("Costruttore"); ?></label>
                    <?php
                    $manufactures = $form->get('car')->get('manufactures');
                    echo $this->formElement($manufactures);
                    echo $this->formElementErrors($manufactures, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Modello"); ?></label>
                    <?php
                    $model = $form->get('car')->get('model');
                    echo $this->formElement($model);
                    echo $this->formElementErrors($model, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Identificativo"); ?></label>
                    <?php
                    $label = $form->get('car')->get('label');
                    echo $this->formElement($label);
                    echo $this->formElementErrors($label, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="name"><?= $this->translate("Flotta"); ?></label>
                    <?php 
                    if($this->roles[0]=="superadmin") {
                        echo $this->formRow($form->get('car')->get('fleet'));
                    } else {
                        echo $this->formRow($form->get('car')->get('fleet')->setAttribute('disabled', 'true'));
                    }
                    ?>
                </div>
            </div>
            <div class="col-lg-1">
                <div class="form-group">
                    <label for="name"><?= $this->translate("Attiva"); ?></label>
                    <?= $this->formRow($form->get('car')->get('active')); ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender"><?= $this->translate("Note"); ?></label>
                    <?= $this->formRow($form->get('car')->get('notes')); ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender"><?= $this->translate("Telaio"); ?></label>
                    <?= $this->formRow($form->get('car')->get('vin')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Aggiorna stato auto"); ?></label>
                    <?= $this->formRow($form->get('car')->get('status')); ?>
                </div>
            </div>
            <div class="col-lg-4" id="js-list-ricovery-car" style="display: none;">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Sede di ricovero auto"); ?></label>
                    <?php if ($this->disableInputStatusMaintenance): ?>
                        <?= $this->formRow($form->get('location')->setAttribute('disabled', 'true')); ?>
                    <?php else: ?>
                        <?= $this->formRow($form->get('location')); ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-lg-5" id="js-list-motivation-car" style="display: none;">
                <div class="form-group">
                    <label for="surname"><?= $this->translate("Motivazione"); ?></label>
                    <?php if ($this->disableInputStatusMaintenance): ?>
                        <?= $this->formRow($form->get('motivation')->setAttribute('disabled', 'true')); ?>
                    <?php else: ?>
                        <?= $this->formRow($form->get('motivation')); ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>


        <div class="row" style="display: none;" id="js-note">
            <div class="col-lg-12">
                <label for="note"><?= $this->translate("Note"); ?></label>
                <?php if ($this->disableInputStatusMaintenance): ?>
                    <?= $this->formRow($form->get('note')->setAttribute('readonly', 'true')); ?>
                <?php else: ?>
                    <?= $this->formRow($form->get('note')); ?>
                <?php endif; ?>
                <br /><br />
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success" onclick="verify()"><?= $this->translate("Modifica Auto"); ?></button>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var listRecovery = $('#js-list-ricovery-car');
        var selectStatus = $('.js-status');
        var noteInput = $('#js-note');
        var listMotivation = $('#js-list-motivation-car');

        showListRecovery(selectStatus.val());

        $(selectStatus).change(function () {
            var value = $(this).val();
            showListRecovery(value);
        });

        function showListRecovery(value) {
            if (value == '<?= \SharengoCore\Utility\CarStatus::MAINTENANCE; ?>') {
                listRecovery.show();
                noteInput.show();
                listMotivation.show();
                //console.log($("#motivation").val());
            } else {
                listRecovery.hide();
                noteInput.hide();
                listMotivation.hide();
            }
        }
    });

    function verify(){
        if ($("#motivation").val() == "1" && $('.js-status').val() == '<?= \SharengoCore\Utility\CarStatus::MAINTENANCE; ?>'){
            alert( "Devi selezionare una motivazione" );
            event.preventDefault();
        }
    };
</script>
