<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() . '/js/datatable-session-data.js')
    ->appendFile($this->basePath() .'/js/cars.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO AUTO"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.plate"><?= $this->translate("Targa"); ?></option>
                                    <option value="e.label"><?= $this->translate("Identificativo"); ?></option>
                                    <option value="f.name"><?= $this->translate("Flotta"); ?></option>
                                    <option value="ci.gps"><?= $this->translate("GPS"); ?></option>
                                    <option value="ci.firmwareVersion"><?= $this->translate("GPRS"); ?></option>
                                    <option value="ci.softwareVersion"><?= $this->translate("OBC"); ?></option>
                                    <option value="e.intCleanliness"><?= $this->translate("Pulizia Interna"); ?></option>
                                    <option value="e.extCleanliness"><?= $this->translate("Pulizia Esterna"); ?></option>
                                    <option value="e.running"><?= $this->translate("In Corsa"); ?></option>
                                    <option value="e.hidden"><?= $this->translate("Nascosta"); ?></option>
                                    <option value="e.active"><?= $this->translate("Attiva"); ?></option>
                                    <option value="e.statusMaintenance"><?= $this->translate("Stato manutenzione"); ?></option>
                                    <option value="e.statusOperative"><?= $this->translate("Stato operativa"); ?></option>
                                    <option value="e.statusNotOperative"><?= $this->translate("Stato non operativa"); ?></option>
                                    <option value="e.busy"><?= $this->translate("Occupata"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select name="js-clean-type" id="js-clean-type" class="form-control" style="display: none;">
                                    <option value="clean"><?= $this->translate("Pulito"); ?></option>
                                    <option value="average"><?= $this->translate("Media"); ?></option>
                                    <option value="dirty"><?= $this->translate("Sporco"); ?></option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <a href="<?= $this->url('cars/add'); ?>" class="btn green pull-right"><i class="fa fa-plus"></i> <?= $this->translate("Aggiungi Auto"); ?></a>
                    </div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Auto"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-cars-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Targa"); ?></th>
                                <th><?= $this->translate("Identif."); ?></th>
                                <th><?= $this->translate("Flotta"); ?></th>
                                <th><?= $this->translate("Batteria"); ?></th>
                                <th><?= $this->translate("Ultimo Contatto"); ?></th>
                                <th><?= $this->translate("Km"); ?></th>
                                <th><?= $this->translate("Pulizia"); ?></th>
                                <th><?= $this->translate("Posizione"); ?></th>
                                <th><?= $this->translate("Stato"); ?></th>
                                <th><?= $this->translate("Nascosta"); ?></th>
                                <th><?= $this->translate("GPS"); ?></th>
                                <th><?= $this->translate("GPRS"); ?></th>
                                <th><?= $this->translate("OBC"); ?></th>
                                <th><?= $this->translate("Posizione"); ?></th>
                                <th><?= $this->translate("Azione"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var filters = <?= $this->filters ?>;
</script>