<?php
$timestampBeginning = '';
// if trip is not yet closed
if (!$this->trip->isEnded()):
?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché non risulta ancora conclusa."); ?></p>
    </div>
</div>

<?php
// if trip has been payed successfully
elseif ($this->trip->isPaymentCompleted()):
?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché risulta già pagata."); ?></p>
    </div>
</div>

<?php

elseif ($this->scriptRunning && $this->trip->getTripPayment() !== null):

?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché è in corso la procedura di pagamento."); ?></p>
    </div>
</div>

<?php
// if trip can be edited
else:
    $form = $this->editTripForm->prepare();
    $form->setAttribute('action', $this->url('trips/edit-tab', ['id' => $this->trip->getId()]));
    $trip = $this->trip;
    $timestampBeginning = $trip->getTimestampBeginning()->format('d-m-Y H:i:s');
?>

<?= $this->form()->openTag($form); ?>
<!-- Edit table -->
<div class="row">
    <div class="col-lg-12">
        <?= $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-server"></i><?= $this->translate("Dati corsa"); ?>
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data inizio"); ?></label>
                            <div class="sng-info-box"><?= $timestampBeginning ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data fine"); ?> <span class="sng-hint"><?= $this->translate("(non precedente a quella di inizio)"); ?></span></label>
                            <?= $this->formRow($form->get('trip')->get('timestampEnd')); ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Pagabile"); ?> <span class="sng-hint"><?= $this->translate("(impostabile solo a non pagabile)"); ?></span></label>
                            <?php
                            if ($trip->getPayable()) {
                                echo $this->formRow($form->get('trip')->get('payable'));
                            } else {
                                echo '<div class="sng-info-box">' . $this->translate("NO") . '</div>';
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <button
                            type="submit"
                            onClick="<?= $this->trip->isPaymentTried() ? "removeTries(event)" : ""; ?>"
                            class="btn btn-success">
                            <?= $this->translate("Salva Dati Corsa"); ?>
                        </button>
                    </div>
                </div>
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- edit table -->
<?= $this->form()->closeTag(); ?>

<?= $this->partial('partials/events-table.phtml', ['events' => $this->events]); ?>

<?php
// close editable trip section
endif;
?>
<script type="text/javascript" src="/js/edit-trip.js"></script>
