<?php
$timestampBeginning = '';
// if trip is not yet closed
if (!$this->trip->isEnded()):
?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché non risulta ancora conclusa."); ?></p>
    </div>
</div>

<?php
// if trip has been payed successfully
elseif ($this->trip->isPaymentCompleted()):
?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché risulta già pagata."); ?></p>
    </div>
</div>

<?php

elseif ($this->scriptRunning && $this->trip->getTripPayment() !== null):

?>

<div class="row">
    <div class="col-lg-12">
        <p><?= $this->translate("La corsa non può essere modificata perché è in corso la procedura di pagamento."); ?></p>
    </div>
</div>

<?php
// if trip can be edited
else:
    $form = $this->editTripForm->prepare();
    $form->setAttribute('action', $this->url('trips/edit-tab', ['id' => $this->trip->getId()]));
    $trip = $this->trip;
    $timestampBeginning = $trip->getTimestampBeginning()->format('d-m-Y H:i:s');
?>

<?= $this->form()->openTag($form); ?>
<!-- Edit table -->
<div class="row">
    <div class="col-lg-12">
        <?= $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-server"></i><?= $this->translate("Dati corsa"); ?>
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data inizio"); ?></label>
                            <div class="sng-info-box"><?= $timestampBeginning ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data fine"); ?> <span class="sng-hint"><?= $this->translate("(non precedente a quella di inizio)"); ?></span></label>
                            <?= $this->formRow($form->get('trip')->get('timestampEnd')); ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Pagabile"); ?> <span class="sng-hint"><?= $this->translate("(impostabile solo a non pagabile)"); ?></span></label>
                            <?php
                            if ($trip->getPayable()) {
                                echo $this->formRow($form->get('trip')->get('payable'));
                            } else {
                                echo '<input type="hidden" name="trip[payable]" value="0">';
                                echo '<div class="sng-info-box">' . $this->translate("NO") . '</div>';
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <button
                            type="submit"
                            onClick="<?= $this->trip->isPaymentTried() ? "removeTries(event)" : ""; ?>"
                            class="btn btn-success">
                            <?= $this->translate("Salva Dati Corsa"); ?>
                        </button>
                    </div>
                </div>
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- edit table -->
<?= $this->form()->closeTag(); ?>

<?php
// close editable trip section
endif;
?>

<?php if (!$trip->isEnded()): ?>

    <div class="row">
        <div class="col-lg-12">

            <?= $this->partial('partials/flash-messages.phtml', []); ?>
            <div class="panel panel-default">
                <div class="panel-heading"><?= $this->translate("Chiudi corsa"); ?></div>
                <div class="panel-body">
                    <form method="post" action="<?= $this->url('trips/do-close/post'); ?>">
                        <input type="hidden" name="id" value="<?= $this->trip->getId(); ?>">

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="gender"><?= $this->translate("Data e ora chiusura"); ?></label>
                                    <input type="text" name="datetime" id="datetime" class="form-control date-picker">
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="name"><?= $this->translate("Pagabile"); ?></label>
                                    <select name="payable" id="payable" class="form-control">
                                        <option value="none">-</option>
                                        <option value="yes"><?= $this->translate("Sì"); ?></option>
                                        <option value="no"><?= $this->translate("No"); ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <button type="submit" class="btn btn-success"><?= $this->translate("Chiudi corsa"); ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>

<script type="text/javascript" src="/js/close-trip.js"></script>
<script type="text/javascript" src="/js/edit-trip.js"></script>
