<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO PRENOTAZIONI"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="beginningTs"><?= $this->translate("Data"); ?></option>
                                    <option value="c.plate"><?= $this->translate("Targa"); ?></option>
                                    <option value="cu.taxCode"><?= $this->translate("Codice Fiscale"); ?></option>
                                    <option value="cu.surname"><?= $this->translate("Cognome"); ?></option>
                                    <option value="cu.id"><?= $this->translate("ID Cliente"); ?></option>
                                    <option value="e.cards"><?= $this->translate("RFID"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green" id="js-search"><i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>

                <hr>
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
</script>