<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/invoices.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Header -->
        <h3 class="page-title">
            <?= $this->translate("ELENCO FATTURE"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <!-- Content -->
        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- Filter container -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">

                            <!-- Filter selector -->
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.invoiceNumber"><?= $this->translate("N° Fattura"); ?></option>
                                    <option value="cu.name"><?= $this->translate("Nome"); ?></option>
                                    <option value="cu.surname"><?= $this->translate("Cognome"); ?></option>
                                    <!-- <option value="e.type">Tipo</option> -->
                                </select>
                            </div>
                            <!-- filter selector -->

                            <!-- Type selector -->
                            <div class="form-group">
                                <select name="js-payment-type" id="js-payment-type" class="form-control" style="display: none;">
                                    <option value="FIRST_PAYMENT"><?= $this->translate("Iscrizione"); ?></option>
                                    <option value="TRIP"><?= $this->translate("Corsa"); ?></option>
                                    <option value="PENALTY"><?= $this->translate("Sanzione"); ?></option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <!-- type selector -->

                            <!-- Search buttons -->
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- search buttons -->

                        </div>
                    </div>
                </div>
                <!-- filter container -->

                <hr>

                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Fatture"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-invoices-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("N° Fattura"); ?></th>
                                <th><?= $this->translate("Data"); ?></th>
                                <th><?= $this->translate("Nome"); ?></th>
                                <th><?= $this->translate("Cognome"); ?></th>
                                <th><?= $this->translate("Tipo"); ?></th>
                                <th><?= $this->translate("Totale"); ?></th>
                                <th><?= $this->translate("Download"); ?></th>
                            </tr>
                            </thead>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- datatable container -->

            </div>
        </div>
        <!-- content -->

    </div>
</div>

<script>
var pdfPath = "<?= $this->url('pdf/invoices'); ?>/";
</script>
