<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Validazione Patente"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicense"><?= $this->translate("Valida"); ?></label>
                            <div class="sng-info-box"><?= $this->isValidated ? $this->translate('SI') : $this->translate('NO'); ?></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseAuthority"><?= $this->translate("Tentativi"); ?></label>
                            <div class="sng-info-box"><?= count($this->validations); ?></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="driverLicenseReleaseDate"><?= $this->translate("Straniera"); ?></label>
                            <div class="sng-info-box"><?= $this->isLicenseForeign ? $this->translate('SI') : $this->translate('NO'); ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php if (count($this->validations) > 0) : ?>
        <div class="row">
            <div class="col-md-12">

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i>
                                <?= $this->translate("Tentativi validazione"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <p><?= $this->translate("Il simbolo (*) indica che la data indicata non corrisponde alla data in cui è stato effettuato il tentativo di validazione."); ?></p>

                        <!-- Table -->
                        <table id="validations-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th><?= $this->translate("Data"); ?></th>
                                    <th><?= $this->translate("Esito"); ?></th>
                                    <th><?= $this->translate("Codice"); ?></th>
                                    <th><?= $this->translate("Messaggio"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->validations as $validation): ?>
                                <tr>
                                    <td><?= $validation->getGeneratedTs()->format('Y-m-d H:i:s') . ($validation->isFromScript() ? ' ' . $this->translate('(*)') : ''); ?></td>
                                    <td><?= $validation->isValid() ? 'OK' : 'KO'; ?></td>
                                    <td><?= $validation->getCode(); ?></td>
                                    <td><?= $validation->getMessage(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
        <?php endif; ?>

    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customer-license/customer-license.js'; ?>"></script>
