<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/js/moment.min.js')
    ->appendFile('/js/datatables/plugins/sorting/datetime-moment.js')
    ->appendFile($this->basePath() . '/js/datatable-session-data.js')
    ->appendFile($this->basePath() . '/js/trips-not-payed.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?= $this->translate("CORSE NON PAGATE"); ?></h3>
        <div class="page-bar"></div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="cu.surname"><?= $this->translate("Cognome"); ?></option>
                                    <option value="cu.id"><?= $this->translate("ID Cliente"); ?></option>
                                    <option value="cc.rfid"><?= $this->translate("RFID"); ?></option>
                                    <option value="f.name"><?= $this->translate("Flotta"); ?></option>
                                    <option value="e.id"><?= $this->translate("ID Corsa"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green" id="js-search"><i
                                        class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i
                                        class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i
                                                class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
                <hr>
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption"><?= $this->translate("Elenco"); ?></div>
                    </div>
                    <!-- BEGIN table -->
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="unpayed-trips-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Id Corsa"); ?></th>
                                <th><?= $this->translate("Cognome"); ?></th>
                                <th><?= $this->translate("Nome"); ?></th>
                                <th><?= $this->translate("RFID"); ?></th>
                                <th><?= $this->translate("Targa"); ?></th>
                                <th><?= $this->translate("Flotta"); ?></th>
                                <th><?= $this->translate("Km Inizio"); ?></th>
                                <th><?= $this->translate("Km Fine"); ?></th>
                                <th style="min-width: 60px !important;"><?= $this->translate("Inizio"); ?></th>
                                <th style="min-width: 60px !important;"><?= $this->translate("Fine"); ?></th>
                                <th style="min-width: 80px !important;"><?= $this->translate("Durata"); ?></th>
                                <th><?= $this->translate("Sosta"); ?></th>
                                <th><?= $this->translate("Costo"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- END table -->
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var filters = <?= $this->filters ?>;
</script>