<div class="row">
    <div class="col-lg-12">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Consente chiusura corsa?</th>
                <th>Zone</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\ZoneGroups $zone */
            foreach($this->list as $zone): ?>
                <tr>
                    <td><?= $zone->getId(); ?></td>
                    <td><?= $zone->getDescription(); ?></td>
                    <td><?= ($zone->getCloseTrip() ? 'si' : 'no') ?></td>
                    <td><?= $zone->getZonesListText(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
