<div class="row">
    <div class="col-lg-12">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th><?= $this->translate("ID"); ?></th>
                <th><?= $this->translate("Name"); ?></th>
                <th><?= $this->translate("Consente chiusura corsa?"); ?></th>
                <th><?= $this->translate("Zone"); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\ZoneGroups $zone */
            foreach($this->list as $zone): ?>
                <tr>
                    <td><?= $zone->getId(); ?></td>
                    <td><?= $zone->getDescription(); ?></td>
                    <td><?= ($zone->getCloseTrip() ? $this->translate("si") : $this->translate("no")) ?></td>
                    <td><?= $zone->getZonesListText(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
