<!-- BEGIN PAGE HEADER-->
<div class="page-bar">
</div>

<div class="row">
    <div class="col-md-12">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

        <div class="row">
            <div class="col-md-12">
                <div class="form-inline">
                    <div class="form-group">
                        <select name="column" id="js-column" class="form-control">
                            <option value="select" selected>-- Seleziona --</option>
                            <option value="f.name">Nome</option>
                            <option value="f.description">Descrizione</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="Filtra...">
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> Cerca</button>
                        <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> Pulisci Ricerca</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>Elenco Configurazioni
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="js-zones-table">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Attivo</th>
                        <th>Nascosto</th>
                        <th>Descrizione</th>
                        <th>Usa RevGeo</th>
                        <th>Azioni</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

<script type="text/javascript" src="/js/zones-list-tab.js"></script>