<div class="row">
    <div class="col-lg-12">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th><?= $this->translate("ID"); ?></th>
                <th><?= $this->translate("Condizione"); ?></th>
                <th><?= $this->translate("Costo"); ?></th>
                <th><?= $this->translate("Bonus"); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \SharengoCore\Entity\ZonePrices $zone */
            foreach($this->list as $zone): ?>
                <tr>
                    <td><?= $zone->getId(); ?></td>
                    <td><?= $this->translate("Inizio corsa"); ?> <strong><?= $zone->getGroupOpen()->getDescription()?></strong><br />
                        <?= $this->translate("Fine corsa"); ?> <strong><?= $zone->getGroupClose()->getDescription()?></strong></td>
                    <td><?= $zone->getCost(); ?></td>
                    <td><?= $zone->getBonus(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
