<div class="row">
    <div class="col-lg-12">
        <ul class="filter-list">
            <?php
            $data = [];
            /** @var \SharengoCore\Entity\Zone $zone */
            foreach($this->list as $zone){ ?>
            <li class="col-md-4"><label><input type="checkbox" class="area-sel" name="area-sel" value="<?= $zone->getId(); ?>"> <?= $zone->getName(); ?></label></li>
            <?php 
            $data[$zone->getId()] = json_decode($zone->getAreaUse());
            } ?>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div id="map"></div>
        
        <style>
            .filter-list {list-style:none;margin:15px 0 15px 0;padding:0}
            .filter-list li {float:left;width:30%;}
            .filter-list li input {vertical-align: top;}
            #map {margin-top:30px;min-height: 400px; height: 40%;}
        </style>
        <script>
            var map,
                loadObj = { "type": "FeatureCollection",
                  "features": [
                    { "type": "Feature",
                       "geometry" : {}
                    }
                  ]
                },
                data = <?= json_encode($data); ?>,
                allObjs = {};
                
            $(document).ready(function(){
                $('#map').height($('.page-content').outerHeight()-$('#map').offset().top);
                
                $('.filter-list li input[type=checkbox]').on('change',function(e){
                    e.preventDefault();
                    
                    var id = $(this).val();
                    if(!$(this).is(':checked')){
                        // nascondi
                        if(typeof allObjs[id]!=='undefined'){
                            for (var i = 0; i < allObjs[id].length; i++)
                                map.data.remove(allObjs[id][i]);
                        }
                    }else{
                        // visualizza
                        var newObj = $.extend(true, {}, loadObj);
                        newObj.features[0].geometry = data[id];
                        allObjs[id] = map.data.addGeoJson(newObj);
                        map.data.setStyle(function(feature){
                            return {
                                fillColor: "red",
                                fillOpacity:0.3,
                                strokeColor:"red",
                                strokeOpacity: 1,
                                strokeWeight: 2,
                                zIndex:11
                        }});
                    }
                })
                
            });

            function initMap(){
                map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 7,
                    center: {lat: 44.5563793, lng: 11.3180998}
                });
            }
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHVZSbufdhNoMVU8uJHi1aTmvPoYN4ErY&signed_in=true&callback=initMap"></script>
    </div>
</div>
