<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    <?= $this->translate("Gestione Aree"); ?>
                </h3>
            </div>
        </div>

        <div class="col-md-12">
            <div class="row row-filters">
                <div class="col-md-5">
                    <div class="form-inline">
                        <div class="form-group">
                            <select name="zone-sel" id="zone-sel" class="form-control">
                                <option value="select" selected="">-- <?= $this->translate("Seleziona"); ?> --</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div id="map"></div>

                <style>
                    #map {min-height: 400px; height: 40%;}
                    .row-filters {margin-bottom:30px;}
                </style>
                <script>
                    var geoPoly,
                        data = {<?php
                        /** @var \SharengoCore\Entity\ZoneAlarms $zone */
                        foreach ($this->list as $zone) {
                            echo $zone->getId().':{description:"'.$zone->getDescription().'",data:[';
                            $data = explode('),(', substr($zone->getGeo(), 2, -2));
                            foreach ($data as $coord) {
                                $coord = explode(',', $coord);
                                echo '{lat:'.$coord[1].',lng:'.$coord[0].'},';
                            }
                            echo ']},';
                        } ?>};

                    $(document).ready(function(){
                        $.each(data, function (i, item) {
                            // console.log("I: "+ i);
                            // console.log(item);
                            $('#zone-sel').append($('<option>', {
                                value: i,
                                text : i + " - " + item.description
                            }));
                        });

                        $('#zone-sel').on('change',function(e){
                            if(typeof geoPoly !== 'undefined'){
                                geoPoly.setMap(null);
                            }

                            geoPoly = new google.maps.Polygon({
                                paths: data[$(this).val()].data,
                                strokeColor: '#FF0000',
                                strokeOpacity: 0.8,
                                strokeWeight: 3,
                                fillColor: '#FF0000',
                                fillOpacity: 0.35
                            });
                            geoPoly.setMap(map);

                        });
                    });

                    $( window ).load(function() {
                        $('#map').height($('.page-content').outerHeight()-$('#map').offset().top);
                    });

                    function initMap(){
                        map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 7,
                            center: {lat: 44.5563793, lng: 11.3180998}
                        });
                    }
                    // Window Resize Action Bind
                    var id;
                    $(window).resize(function() {
                        clearTimeout(id);
                        id = setTimeout(doneResizing, 500);
                    });
                    var doneResizing = function(){
                        $('#map').height($('.page-content').outerHeight()-$('#map').offset().top);
                    };
                </script>
                <!--<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjv0Ry_0P18id6pWKwNn0IptB8NvZGfxY&callback=initMap"></script>-->
                <script>
                $.ajax({
                    type: "POST",
                    url: "/google-maps-call",
                    success: function (data) {
                        $mapPopup.html(
                        '<img id="map-popup-img" src="' +
                        data['src'] +
                        '" class="map-popup-img">');
                    },
                    error: function(){
                        $mapPopup.html(
                        '<img id="map-popup-img" src="" class="map-popup-img">');
                    }
                });
                </script>
            </div>
        </div>
    </div>
</div>
