<!-- Events table -->
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate("Elenco eventi"); ?>
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover events-table">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("ID"); ?></th>
                            <th><?php echo $this->translate("Data"); ?></th>
                            <th><?php echo $this->translate("Descrizione"); ?></th>
                            <th><?php echo $this->translate("Batteria"); ?></th>
                            <th><?php echo $this->translate("Km"); ?></th>
                            <th><?php echo $this->translate("Evento"); ?></th>
                            <th><?php echo $this->translate("Label"); ?></th>
                            <th><?php echo $this->translate("Valore"); ?></th>
                            <th><?php echo $this->translate("Intval"); ?></th>
                            <th><?php echo $this->translate("Posizione"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->events as $event): ?>
                            <tr>
                                <td><?= $event->getId() ?></td>
                                <td class="event-time"><?= $event->getEventTime()->format('d-m-Y H:i:s') ?></td>
                                <td><?= ($event->getEventType()) ? $event->getEventType()->getFormattedDescription($event) : ''; ?></td>
                                <td><?= $event->getBattery() . '%' ?></td>
                                <td><?= $event->getKm() ?></td>
                                <td><?= $event->getEventId() ?></td>
                                <td><?= $event->getLabel() ?></td>
                                <td><?= $event->getTxtval() ?></td>
                                <td><?= $event->getIntval() ?></td>
                                <td>
                                    <a href="http://www.openstreetmap.org/?mlat=<?= $event->getLat() ?>&mlon=<?= $event->getLon() ?>&zoom=18" target="_blank">
                                        <?= 'Lat:' . $event->getLat() . ' Lon:' . $event->getLon() ?>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- events table -->
