
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script>

<!-- Events table -->
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate("Mappa del viaggio"); ?>
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- events table -->
