<ul class="nav navbar-nav pull-right">
    <li class="dropdown dropdown-user">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="username username-hide-on-mobile">
            <?php if ($this->zfcUserIdentity()) {
                echo $this->zfcUserIdentity()->getUsername();
            }?></span>
            <i class="fa fa-angle-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-default">
            <li>
                <a href="/user/logout">
                    <i class="icon-key"></i> Log Out </a>
            </li>
        </ul>
    </li>
</ul>