<ul class="nav navbar-nav pull-right">
    <li class="dropdown dropdown-user">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="username username-hide-on-mobile">
                 <?= $this->languageManager()->currentLanguage['label'] ?>
            </span>
            <i class="fa fa-angle-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-default">
            <?php foreach ($this->languageManager()->languages as $lang) : ?>
                <li><a href="<?= $lang['url'] ?>"><?= $lang['label'] ?></a></li>
            <?php endforeach ?>
        </ul>
    </li>
</ul>
