<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Comtible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="CUP by Bulweria Ltd">

    <!-- CSS -->
    <?php
        // Load Bootstrap
        $this->headLink()->prependStylesheet($this->basePath()."/bootstrap/dist/css/bootstrap.css");

        echo $this->headLink();
    ?>
    
    <!-- Translations -->
    <?php echo $this->partial('partials/translations.phtml'); ?>
</head>
<body data-spy="scroll">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default" id="top-page">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><?=$this->translate("Dati Statistici");?></a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/reports/trips"><?=$this->translate("Corse");?></a></li>
                    <li><a href="/reports/map"><?=$this->translate("Mappa a calore");?></a></li>
                    <li><a href="/reports/routes"><?=$this->translate("Itinerari");?></a></li>
                    <li><a href="/reports/live"><?=$this->translate("In tempo reale");?></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <!-- Begin page content -->
    <?php echo $this->content; ?>

    <footer class="footer">
        <div class="container">
            <p class="text-muted">&reg;CUP by Bulweria Ltd 2016</p>
        </div>
    </footer>

    <!-- Scripts -->
    <?php
        // Load Bootstrap
        $this->inlineScript()->appendFile($this->basePath()."/bootstrap/dist/js/bootstrap.js");

        echo $this->inlineScript();
    ?>
</body>
</html>
