<?php
    $this->inlineScript()
        ->appendFile('/assets-modules/reports/js/vendor.live.js');

    $this->headLink()
        ->appendStylesheet('/assets-modules/reports/css/vendor.live.css');
?>

<!-- Begin page content -->
<div class="container-fluid bs-docs-container">
    <div class="page-header">
        <h1>Cars live location</h1>
    </div>
    <div class="row">
        <div class="col-xs-9 col-sm-9 col-md-9" id="header-buttons"></div>
        <!--
        <div class="col-xs-9 col-sm-9 col-md-9">
            <button type="button" class="btn btn-default" id="pan-to-milan">Pan to Milan</button>
            <button type="button" class="btn btn-default" id="pan-to-florence">Pan to Florence</button>
            </div>-->
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="col-xs-3 col-md-3" id="element-counter">
                <div class="col-xs-6 col-md-4">
                    <span class="date-label">Tot:</span>
                </div>
                <div class="col-xs-10 col-md-6">
                    <input type="text" class="input-sm form-control" placeholder="" disabled>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row-fluid">
        <div id="map" class="map">
            <div id="info"></div>
        </div>
    </div>
</div>
