<?php
    $this->inlineScript()
        ->appendFile('/assets-modules/reports/js/vendor.live.js')
        ->prependScript('
            // Getting the actual city id (from the controller), and save it to js $.oe vars
            var thisLanguage="'.$this->userLanguage.'";
        ');

    $this->headLink()
        ->appendStylesheet('/assets-modules/reports/css/vendor.live.css');
?>

<!-- Begin page content -->
<div class="container-fluid bs-docs-container">
    <div class="page-header">
        <h1><?=$this->translate("In tempo reale");?></h1>
    </div>
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10" id="header-buttons">
            <button id="dataupdate" type="button" class="btn btn-default" aria-label="Left Align">
                <?=$this->translate("Aggiorna i dati");?>
                <span class=" glyphicon glyphicon-refresh" aria-hidden="true"></span>
            </button>
            <button id="hidestopped" type="button" class="btn btn-default" aria-label="Left Align">
                <?=$this->translate("Nascondi auto ferme");?>
                <span class=" glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </button>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2" id="element-counter">
            <div class="col-xs-6 col-md-4">
                <span class="date-label"><?=$this->translate("Totali");?>:</span>
            </div>
            <div class="col-xs-10 col-md-6">
                <input type="text" class="input-sm form-control" placeholder="" disabled>
            </div>
        </div>
    </div>
    <br>
    <div class="row-fluid">
        <div id="map" class="map">
            <div id="info"></div>
        </div>
    </div>
</div>
