<?php
    $this->inlineScript()
        ->appendFile('/assets-modules/reports/js/vendor.map.js');

    $this->headLink()
        ->appendStylesheet('/assets-modules/reports/css/vendor.map.css');
?>
<!-- Begin page content -->
<div class="container-fluid bs-docs-container">
    <div class="page-header">
        <h1>Trips HeatMap</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-5 col-md-5" id="header-buttons">
            <button type="button" class="btn btn-default" id="change-begend">Change to Ending Location</button>
            <input id="weight" data-slider-id='weightSlider' type="text" data-slider-min="0" data-slider-max="10" data-slider-step="1" data-slider-value="4"/>
        </div>
        <div class="col-xs-12 col-sm-7 col-md-7">
            <div class="col-xs-4 col-md-2">
                <span class="date-label">Time Range:</span>
            </div>
            <div class="col-xs-10 col-md-6">
                <div class="input-daterange input-group" id="datepicker">
                    <input type="text" class="input-sm form-control" id="start" name="start" />
                    <span class="input-group-addon">to</span>
                    <input type="text" class="input-sm form-control" id="end" name="end" />
                </div>

            </div>
            <div class="col-xs-3 col-md-3" id="element-counter">
                    <div class="col-xs-6 col-md-4">
                        <span class="date-label">Tot:</span>
                    </div>
                    <div class="col-xs-10 col-md-6">
                        <input type="text" class="input-sm form-control" placeholder="" disabled>
                    </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-12">
        <div id="map" class="map"></div>
        <div id="info"></div>
    </div>
</div>
