<?php

$this->inlineScript()
    ->appendFile('/assets-modules/reports/js/vendor.routes.js')
    ->prependScript('
            // Getting the actual city id (from the controller), and save it to js $.oe vars
            var thisLanguage="'.$this->plugin('translate')->getTranslator()->getLocale().'";
        ');

if(isset($this->tripid)) {
    $this->inlineScript()->prependScript('var tripid='.$this->tripid.';');
}

$this->headLink()
    ->appendStylesheet('/assets-modules/reports/css/vendor.routes.css');
?>
<!-- Begin page content -->
<div class="container col-md-12">
    <div class="page-header">
        <h1><?=$this->translate("Itinerari");?></h1>
    </div>
    <div class="row mainrow">
        <div class="col-md-12" id="menubar">
            <div class="btn-toolbar" role="toolbar">
                <div class="col-md-2 labeldate">
                    <span><?=$this->translate("Verranno caricate");?></span>
                </div>
                    <div class="col-md-4 dataslider">
                        <input id="ex6" type="text" data-slider-min="15" data-slider-max="300" data-slider-step="25" data-slider-value="15"/>
                        <span id="ex6CurrentSliderValLabel">
                            <span id="ex6SliderVal"><?=$this->translate("le");?> 15 <?=$this->translate("corse precedenti a");?></span>
                        </span>
                    </div>
                    <div class="col-md-3">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button id="dataupdate" type="button" class="btn btn-default">
                            <?=$this->translate("Aggiorna i dati");?>
                            <span class=" glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        </button>

                        <button id="hoverenable" type="button" class="btn btn-default">
                            <?=$this->translate("Inseguimento");?>
                            <span class=" glyphicon glyphicon-screenshot" aria-hidden="true"></span>
                        </button>
                        <!--<button id="maintainer" type="button" class="btn btn-default" aria-label="Left Align">
                            Manutentori
                          <span class=" glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </button>-->
                        <input id="maintainer" type="checkbox" name="maintainer" data-on-text="<?=$this->translate("Clienti");?>" data-off-text="<?=$this->translate("Manutentori");?>" data-on-color="info" data-label-width="20" checked>
                    </div>
                </div>
            <div class="clearfix visible-xs-block"></div>
        </div>
        <div class="col-md-10 leftbar">
            <div id="map" class="map"></div>
            <div id="info"></div>

        </div>
        <div class="col-md-2 rightbar">
            <div id="steps" class="side panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?=$this->translate("Corse");?> </h3>
                </div>
                <ol class="list-group panel-body" id="trips"></ol>
            </div>
        </div>
    </div>
</div>
