<?
    $this->inlineScript()
        ->appendFile('/assets-modules/reports/js/vendor.trips.main.js');

    $this->headLink()
        ->appendStylesheet('/assets-modules/reports/css/vendor.trips.main.css');
?>
<!-- Begin page content -->
<div class="container bs-docs-container">
    <div class="page-header">
        <h1><?=$this->translate("Riepilogo Corse");?></h1>
    </div>

    <div class="row">
        <div class="col-md-9 main" role="main">

            <p class="lead">
                <div id='data-count'>
                <!--  <span class='filter-count'></span> selected out of <span class='total-count'></span> records -->
                </div>
            </p>

            <br>

            <div class="panel panel-default  affix-top" id="data-range">
                <div class="panel-heading">
                    <?=$this->translate("Range dati (Ultimi 28 giorni)");?>
                </div>
                <div class="panel-body">
                    <div id="days-chart">
                        <span class="reset" style="display: none;"> <?=$this->translate("filtro");?>: <span class="filter"></span></span>
                        <a class="reset" href="javascript:$.oe.charts.day.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="row" id="bio-data">
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="panel panel-default" id="day-of-week">
                        <div class="panel-heading">
                            <?=$this->translate("Giorno della settimana");?>
                        </div>
                        <div class="panel-body">
                            <div id="day-of-week-chart">
                                <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                                <a class="reset" href="javascript:$.oe.charts.dayOfWeek.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="panel panel-default" id="city">
                        <div class="panel-heading">
                            <?=$this->translate("Citt&agrave;");?>
                        </div>
                        <div class="panel-body">
                            <div id="city-chart">
                                <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                                <a class="reset" href="javascript:$.oe.charts.city.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default" id="duration">
                <div class="panel-heading">
                    <?=$this->translate("Durata (minuti)");?>
                </div>
                <div class="panel-body">
                    <div id="duration-chart">
                        <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                        <a class="reset" href="javascript:$.oe.charts.duration.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default" id="beginning-hour">
                <div class="panel-heading">
                    <?=$this->translate("Orario inizio corsa");?>
                </div>
                <div class="panel-body">
                    <div id="beginning-hour-chart">
                        <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                        <a class="reset" href="javascript:$.oe.charts.beginningHour.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="row" id="bio-data">
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="panel panel-default" id="customer-age">
                        <div class="panel-heading">
                            <?=$this->translate("Classe di et&agrave;");?>
                        </div>
                        <div class="panel-body">
                            <div id="age-chart">
                                <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                                <a class="reset" href="javascript:$.oe.charts.age.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                                <div class="clearfix"></div>
                            </div>
                            <div class="chart-label ">
                                <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> = 45-54&nbsp;&nbsp;&nbsp;
                                <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> = 55-64&nbsp;&nbsp;&nbsp;
                                <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> = <?=$this->translate("oltre");?> 65
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-xs-12 col-sm-6 col-md-6">
                    <div class="panel panel-default" id="customer-gender">
                        <div class="panel-heading">
                            <?=$this->translate("Sesso");?>
                        </div>
                        <div class="panel-body">
                            <div id="gender-chart">
                                <span class="reset" style="display: none;"><?=$this->translate("filtro");?>: <span class="filter"></span></span>
                                <a class="reset" href="javascript:$.oe.charts.gender.filterAll();dc.redrawAll();" style="display: none;"> <?=$this->translate("Azzera");?> </a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div style='clear:both;'></div>
        </div>
        <div class="col-md-3" role="complementary">
            <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix">
                <ul class="nav bs-docs-sidenav"  data-spy="affix" data-offset-top="100" data-offset-bottom="0">
                    <li><a href="#data-range"><?=$this->translate("Range dati (Ultimi 28 giorni)");?></a></li>
                    <li><a href="#day-of-week"><?=$this->translate("Giorno della settimana");?></a></li>
                    <li><a href="#city"><?=$this->translate("Citt&agrave;");?></a></li>
                    <li><a href="#duration"><?=$this->translate("Durata (minuti)");?></a></li>
                    <li><a href="#beginning-hour"><?=$this->translate("Orario inizio corsa");?></a></li>
                    <li><a href="#customer-age"><?=$this->translate("Classe di et&agrave;");?></a></li>
                    <li><a href="#customer-gender"><?=$this->translate("Sesso");?></a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
