angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('de', {});
    gettextCatalog.setStrings('en', {"+24hh":"+24hh","3G":"3G","Abilitato":"Enabled","Address":"Address","Aggiorna":"Update","Annulla":"Cancel","Auto":"Car","Auto scelta":"Chosen car","Autonomia":"Autonomy","Batteria":"Battery","C.F.":"Tax code","Caricamento mappa in corso...":"Map loading...","Cellulare":"Mobile","Cerca":"Search","Chiudi":"Close","Città":"Town","Civico":"Number","Cliente":"Customer","Cognome":"Surname","Conferma":"Confirm","Dati auto":"Car data","Dati cliente":"Customer data","Dati ultima corsa chiusa":"Last closed trip data","Dove si trova":"Where is it","Esci":"Exit","Eventi":"Events","Fine":"End","Fine corsa":"Trip end","GPS":"GPS","Geocode was not successful for the following reason:":"Geocode was not successful for the following reason:","IN MANUTENZIONE":"IN MAINTENANCE","IN USO":"IN USE","In Carica":"IN CHARGE","Indirizzo":"Address","Inizio":"Start","Inizio corsa":"Trip start","Inizio:":"Start:","LIBERE":"FREE","Lat: {{car.latitude}}":"Lat: {{car.latitude}}","Lon: {{car.longitude}}":"Lon: {{car.longitude}}","N.O. 3G":"N.O. 3G","N.O. Batt":"N.O. Batt","N.O. GPS":"N.O. GPS","NON OPERATIVE":"NOT OPERATIVE","Nessun risultato trovato, riprova":"No results, try again","Nessun risultato trovato, riprova con {{noResult}}":"No result, try again with {{noResult}}","Nome":"Name","N° Card":"Card N°","N° Unità":"Units N°","N°.Unità":"Units N°","POIS":"POIS","PRENOTATE":"RESERVED","Posizione":"Position","Seleziona":"Select","Seleziona cliente":"Select customer","Sporca":"Dirty","Stato esterni":"Exteriors state","Stato interni":"Interiors state","Targa":"Plate","Targa:":"Plate:","Telefono":"Phone","Ultime corse":"Last trips","Ultimo contatto":"Last contact","Veicoli trovati":"Found vehicles","batteria":"battery","un altro n° unità":"another unit n°","un'altra targa":"another plate"});
    gettextCatalog.setStrings('fr', {});
    gettextCatalog.setStrings('hu', {});
    gettextCatalog.setStrings('pl', {});
    gettextCatalog.setStrings('pt', {});
    gettextCatalog.setStrings('ru', {"+24hh":"+24hh","3G":"3G","Abilitato":"Доступ активирован","Address":"Адрес","Aggiorna":"Обновить","Annulla":"Отменить","Auto":"Aвто","Auto scelta":"Автоматический выбор","Autonomia":"Aвтономия","batteria":"аккумулятор","Batteria":"Aккумулятор","C.F.":"Идентификационный номер","Caricamento mappa in corso...":"Загрузка карты...","Cellulare":"Мобильный","Cerca":"Поиск","Chiudi":"Закрыть","Città":"Город","Civico":"Муниципальный","Cliente":"Клиент","Cognome":"Фамилия","Conferma":"Подтверждение","Dati auto":"Данные авто","Dati cliente":"Данные клиента","Dati ultima corsa chiusa":"Данные последней заключённой гонки","Dove si trova":"Место нахождения","Esci":"Выход","Eventi":"Соревнования","Fine":"Конец","Fine corsa":"Конец гонки","Geocode was not successful for the following reason:":"Geocode не удался по следующей причине:","GPS":"GPS","In Carica":"Заряжение","IN MANUTENZIONE":"На техобслуживании","IN USO":"В использовании","Indirizzo":"Адресс","Inizio":"Начало","Inizio corsa":"Начало гонки","Inizio:":"Начало гонки:","Lat: {{car.latitude}}":"Ширина:","LIBERE":"Свободные","Lon: {{car.longitude}}":"Длинна: ","N.O. 3G":"3G вне действии","N.O. Batt":"Аккумулятор вне действии","N.O. GPS":"GPS вне действии","N° Card":"№ карты","N° Unità":"№ Единиц","N°.Unità":"№ Единиц","Nessun risultato trovato, riprova":"Совпадений не найдено, попробуй еще раз","Nessun risultato trovato, riprova con {{noResult}}":"Совпадений не найдено, попробуй еще раз ","Nome":"Имя","NON OPERATIVE":"Не функциональные","POIS":"POIS","Posizione":"Позиция","PRENOTATE":"Заброни́рованные","Seleziona":"Выбор","Seleziona cliente":"Выбор клиента","Sporca":"Грязная","Stato esterni":"Внешнее сосояние","Stato interni":"Внутреннее состояние","Targa":"Номера","Targa:":"Номера:","Telefono":"Телефон","Ultime corse":"Последние гонки","Ultimo contatto":"Последний контакт","un altro n° unità":"другой номер единиц","un'altra targa":"добавочные номера","Veicoli trovati":"Обнаруженный транспорт"});
    gettextCatalog.setStrings('es_ES', {});
    gettextCatalog.setStrings('tr', {});
    gettextCatalog.setStrings('zh', {});
/* jshint +W100 */
}]);