<!doctype html>
<html ng-app="SharengoCsApp">
<head>
    <meta charset="UTF-8">
    <?php  echo $this->headLink()
            ->appendStylesheet($this->basePath() . '/assets-modules/call-center/css/vendors.css')
            ->appendStylesheet($this->basePath() . '/assets-modules/call-center/css/style.css');
    ?>
    <?php
        echo $this->headScript()
            ->appendFile($this->basePath() . '/assets-modules/call-center/js/vendors.js')
            //->appendFile($this->basePath() . '/assets-modules/call-center/MilanoBorders.json')
            ->appendFile($this->basePath() . '/assets-modules/call-center/js/translations.js')
            ->appendFile($this->basePath() . '/assets-modules/call-center/js/scripts.js');
    ?>
</head>
<body ng-controller="SharengoCsController">

<div id="map-loader" ng-show="mapLoader">
    <p><i class="fa fa-refresh"></i></p>
    <translate>Caricamento mappa in corso...</translate>
</div>

<div id="top-actions">
    <div class="heading clearfix">
        <div class="fleets">
            <select
                class="form-control"
                ng-change="changeFleet()"
                ng-model="defaultFleet"
                ng-options="fleet as fleet.name for fleet in fleets">
                <option>--</option>
            </select>
        </div>
        <div class="pull-right actions">
            <a href="javascript:;" ng-click="loadCars()" class="btn btn-success btn-xs">
                <i class="fa fa-refresh"></i> <translate>Aggiorna</translate>
            </a>
            <a href="/user/logout" class="btn btn-danger btn-xs">
                <i class="fa fa-sign-out"></i> <translate>Esci</translate>
            </a>
        </div>
    </div>
</div>

<div id="markers-control">
    <div class="pull-right actions">
        <a href="javascript:;" ng-click="poisVisible = !poisVisible;" class="btn btn-xs" ng-class="{'deactive': !poisVisible }">
            <i class="fa fa-plug"></i> &nbsp; <translate>POIS</translate>
        </a>
    </div>
</div>

<div id="top-area">
    <a href="javascript:;" class="opener hidden-md hidden-lg"><i class="fa fa-search"></i></a>
    <tabset>
        <tab heading="{{'Auto'|translate}}">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-input">
                         <div class="input-group">
                            <input type="text" class="form-control" ng-model="search.plate" placeholder="{{'Targa'|translate}}">
                            <span class="input-group-btn">
                                <button class="btn btn-green" ng-click="plateChange(search.plate, false)" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-input">
                        <div class="input-group">
                            <input type="text" class="form-control" ng-model="search.label" placeholder="{{'N°.Unità'|translate}}">
                            <span class="input-group-btn">
                                <button class="btn btn-green" ng-click="plateChange(search.label, true)" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-warning" style="margin-top: 10px;" ng-show="accordionStatus.showNoResult"  role="alert">
                        <i class="fa fa-exclamation-circle"></i> <translate>Nessun risultato trovato, riprova con {{noResult}}</translate>.
                    </div>
                </div>
            </div>

        </tab>
        <tab heading="{{'Cliente'|translate}}">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-input">
                        <input type="text" ng-model="search.name" class="form-control" placeholder="{{'Nome'|translate}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-input">
                        <input type="text" ng-model="search.card" class="form-control" placeholder="{{'N° Card'|translate}}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-input">
                        <input type="text" ng-model="search.surname" class="form-control" placeholder="{{'Cognome'|translate}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-input">
                        <input type="text" ng-model="search.mobile" class="form-control" placeholder="{{'Cellulare'|translate}}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-input">
                        <button class="btn btn-green btn-block" ng-click="userChange(search.mobile, search.name, search.surname, search.card)">
                        <i class="fa fa-search"></i> <translate>Cerca</translate></button>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-green" style="margin-top: 10px;" ng-show="accordionStatus.showNoResultByCustomer"  role="alert">
                        <i class="fa fa-exclamation-circle"></i> <translate>Nessun risultato trovato, riprova</translate>.
                    </div>
                </div>
            </div>

        </tab>

        <tab heading="{{'Indirizzo'|translate}}">

            <div class="row">
                <div class="col-md-9">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.address" class="form-control" placeholder="{{'Indirizzo'|translate}}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.number" class="form-control" placeholder="{{'Civico'|translate}}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.city" class="form-control" placeholder="{{'Città'|translate}}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-input">
                        <button class="btn btn-green btn-block" ng-click="searchAddress.search()">
                        <i class="fa fa-search"></i> <translate>Cerca</translate></button>
                    </div>
                </div>
            </div>

        </tab>
    </tabset>
</div>

<div id="controls">
    <accordion close-others="false">
        <accordion-group heading="{{'Seleziona cliente'|translate}}" ng-hide="accordionStatus.hideCustomerSelect" is-open="accordionStatus.customerSelectOpen">
            <table>
                <thead>
                <tr>
                    <th translate>Seleziona</th>
                    <th translate>Nome</th>
                    <th translate>Cognome</th>
                    <th translate>Telefono</th>
                    <th translate>C.F.</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="customer in customers">
                    <td><button type="button" class="btn btn-default btn-xs" ng-click="selectCustomer(customer)"><i class="fa fa-info"></i> <translate>Seleziona</translate></button></td>
                    <td>{{customer.name | lowercase}}</td>
                    <td>{{customer.surname | lowercase}}</td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.tax_code}}</td>
                </tr>
                </tbody>
            </table>
        </accordion-group>
        <accordion-group class="resultsCars" heading="{{'Veicoli trovati'|translate}}" ng-hide="accordionStatus.hideCarsSelect" is-open="accordionStatus.carsSelectOpen">
            <table>
                <thead>
                <tr>
                    <th translate>Seleziona</th>
                    <th translate>Targa</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="car in carsFound">
                    <td><button type="button" class="btn btn-default btn-xs" ng-click="plateChange(car.plate,false)"><i class="fa fa-info"></i> <translate>Seleziona</translate></button></td>
                    <td>{{car.plate | uppercase}}</td>
                </tbody>
            </table>
        </accordion-group>
        <accordion-group heading="{{'Dati cliente'|translate}}" id="customerData" ng-hide="accordionStatus.hideCustomerData" is-open="accordionStatus.customerDataOpen" class="acc-user-data">
            <div class="row">
                <div class="col-md-3">
                    <label translate>Nome</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.name}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label translate>Cognome</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.surname}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label translate>Cellulare</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.mobile}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label translate>Abilitato</label>
                </div>

                <div class="col-md-9">
                    <span ng-if="customer.enabled" class="ball active"></span>
                    <span ng-if="!customer.enabled" class="ball inactive"></span>
                </div>
            </div>

            <!--<div class="row">
                <div class="col-sm-3">
                    <label>Ultimi ticket</label>
                </div>

                <div class="col-sm-9">
                     <span ng-show="customer.lastTickets.length == 0" class="label label-default">Attualmente non ci sono ticket</span>
                     <span ng-repeat="ticket in customer.lastTickets">
                        {{ticket.ora | dateSharengoFormat}}
                        <button tooltip-placement="left" tooltip-html-unsafe="<b>Tipo chiamata:</b> {{ticket.tipo_chiamata}}<br /> <b>Descrizione:</b><br /> {{ticket.descrizione}}<br />" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        </button>
                        <br>
                    </span>
                </div>
            </div> -->

            <div class="row">
                <div class="col-sm-3 noPaddingRight">
                    <label translate>Ultime corse</label>
                </div>

                <div class="col-md-9" style="font-size: 12px;">
                    <span ng-repeat="trip in customer.lastTrips">
                        <strong translate>Targa:</strong> {{trip.car.plate}} <strong translate>Inizio:</strong> {{trip.beginningTx.date | dateSharengoFormat:'DD-MM-YYYY'}}
                        <button tooltip-placement="left" tooltip-html-unsafe="<b>{{'Inizio'|translate}}:</b> {{trip.timestampBeginning.date | dateSharengoFormat}} <br /><b>{{'Fine'|translate}}:</b> {{trip.timestampEnd.date | dateSharengoFormat}}" class="btn btn-default btn-xs">
                            <i class="fa fa-info-circle"></i>
                        </button>
                        <br>
                    </span>
                </div>
            </div>
        </accordion-group>
        <accordion-group heading="{{'Dati auto'|translate}}" ng-hide="accordionStatus.hideCarData" is-open="accordionStatus.carDataOpen" class="acc-car-data">
            <div class="row">
                <div class="col-md-3">
                    <label translate>Targa</label>
                </div>

                <div class="col-md-9">
                    <span>{{car.plate}}</span>
                </div>
            </div>

            <div class="row">
               <div class="col-md-3">
                    <label translate>N° Unità</label>
                </div>

                <div class="col-md-9">
                    <span>{{car.label}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Posizione</label>
                </div>

                <div class="col-md-9" style="font-size: 12px;">
                    <span translate>Lat: {{car.latitude}}</span><br />
                    <span translate>Lon: {{car.longitude}}</span><br />
                    <span><reverse-geocode lat="car.latitude" lng="car.longitude"></reverse-geocode></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Batteria</label>
                </div>

                <div class="col-md-9">
                    <span>{{car.battery}} % <i ng-if="car.charging" class="fa fa-plug"></i></span>
                </div>
            </div>

           <!-- <div class="row">
                <div class="col-md-3">
                    <label>Ultimi ticket</label>
                </div>

                <div class="col-md-9">
                    <span ng-show="car.lastTickets.length == 0" class="label label-default">Attualmente non ci sono ticket</span>
                    <span ng-repeat="ticket in car.lastTickets">
                        {{ticket.ora | dateSharengoFormat}}
                        <button tooltip-placement="left" tooltip-html-unsafe="<b>Tipo chiamata:</b> {{ticket.tipo_chiamata}}<br /> <b>Descrizione:</b><br /> {{ticket.descrizione}}<br />" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        </button>
                        <br>
                    </span>
                </div>
            </div> -->

        </accordion-group>
       <!-- <accordion-group heading="Dati corsa" ng-hide="accordionStatus.hideTripData" is-open="accordionStatus.tripDataOpen">
            <div class="row">
                <div class="col-md-3">
                    <label>Inizio corsa</label>
                </div>

                <div class="col-md-9">
                    <span>{{trip.trip | dateSharengoFormat:'DD-MM-YYYY'}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Eventi</label>
                </div>

                <div class="col-md-9">
                    <span>{{trip.events}}</span>
                </div>
            </div>
        </accordion-group> -->
        <accordion-group heading="{{'Dati ultima corsa chiusa'|translate}}" ng-hide="accordionStatus.hideLastTripData" is-open="accordionStatus.lastTripDataOpen" class="acc-run-data">

            <div class="row">
                <div class="col-md-3">
                    <label translate>Inizio corsa</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTrip.timestampBeginning.date | dateSharengoFormat}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Fine corsa</label>
                </div>

                <div class="col-md-9" ng-if="lastTrip.timestampEnd.date">
                    <span>{{lastTrip.timestampEnd.date | dateSharengoFormat}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Cliente</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.surname}} {{lastTripUser.name}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Telefono</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.phone}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Cellulare</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.mobile}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label translate>Eventi</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTrip.events}}</span>
                </div>
            </div>
        </accordion-group>
        <!--<accordion-group heading="Richiesta di supporto" ng-hide="accordionStatus.hideRequest" is-open="accordionStatus.requestOpen">

            <div class="alert alert-success" ng-show="accordionStatus.showSuccessMessageTicket"  role="alert">
                Ticket creato con successo!
            </div>

            <div ng-show="accordionStatus.showFormTicket">
                <form name="form" id="form" novalidate ng-submit="submitRequest()">
                    <div class="form-input">
                        <div class="row">
                            <div class="col-md-3">
                                <label>Tipo di chiamata</label>
                            </div>
                            <div class="col-md-9">
                                <select ng-required="true" ng-model="contact.callType">
                                    <option value="">--seleziona--</option>
                                    <option value="1">Istruzioni utilizzo</option>
                                    <option value="2">Guasto auto</option>
                                    <option value="3">Altro</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-input">
                        <div class="row">
                            <div class="col-md-3">
                                <label>Azione eseguita</label>
                            </div>
                            <div class="col-md-9">
                                <select ng-required="true" ng-model="contact.actionDone">
                                    <option value="">--seleziona--</option>
                                    <option value="1">Inoltrata telefonata alla ControlRoom</option>
                                    <option value="2">Spiegazioni telefoniche all'utente</option>
                                    <option value="3">Altro</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-input">
                        <div class="row">
                            <div class="col-md-3">
                                <label>Descrizione</label>
                            </div>
                            <div class="col-md-9">
                                <textarea ng-required="true" ng-model="contact.description" ng-trim="false" maxlength="250"></textarea>
                                <br />
                                <span><small><strong>{{250 - contact.description.length}} caratteri disponibili</strong></small></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-input">
                        <button type="submit" class="btn btn-sm btn-success" id="buttonSumbit" ng-disabled="form.$invalid">Invia richiesta</button>
                        <small><em><strong>Tutti i campi sono obbligatori</strong></em></small>
                    </div>
                </form>
            </div>
        </accordion-group>

    </accordion> -->
</div>

<div id="bottom-area">
    <div class="pull-left">
        <ul class="list-inline">
            <li><span class="block green"></span> <translate>LIBERE</translate></li>
            <li><span class="block yellow"></span> <translate>IN USO</translate></li>
            <li><span class="block black"></span> <translate>PRENOTATE</translate></li>
            <li><span class="block red"></span> <translate>IN MANUTENZIONE</translate></li>
            <li><span class="block orange"></span> <translate>NON OPERATIVE</translate></li>
            <li><span class="block azzure"></span> <translate>+24hh</translate></li>
        </ul>
    </div>
</div>

<ui-gmap-google-map center="mapOptions.center" zoom="mapOptions.zoom" events="mapEvents">
    <ui-gmap-markers models="cars" coords="'self'" icon="'carIcon'" events="markerEvents" options="'options'"></ui-gmap-markers>
    <ui-gmap-markers ng-if="poisVisible" models="pois" coords="'self'" icon="'poiIcon'" options="'options'"></ui-gmap-markers>
    <ui-gmap-polygon
        static="true"
        ng-repeat="p in polygons track by p.id"
        path="p.path"
        stroke="p.stroke"
        visible="p.visible"
        geodesic="p.geodesic"
        fill="p.fill"
        fit="false"
        editable="p.editable"
        draggable="p.draggable"></ui-gmap-polygon>
</ui-gmap-google-map>
</body>
</html>
