<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-md-12">

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i><?= $this->translate("Elenco extra/penali falliti"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table id="failures-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th><?= $this->translate("Id extra"); ?></th>
                                    <th><?= $this->translate("Importo"); ?></th>
                                    <th><?= $this->translate("Data risoluzione"); ?></th>
                                    <th><?= $this->translate("Tempo risoluzione"); ?></th>
                                    <th><?= $this->translate("Tentativi"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->extraPayments as $extraPayment): ?>
                                <tr>
                                    <td><?= $extraPayment->getId(); ?></td>
                                    <td class="sng-text-right"><?= sprintf('%01.2f €', $extraPayment->getAmount() / 100); ?></td>
                                    <td class="sng-date-column sng-text-center">
                                        <?php
                                        if ($extraPayment instanceof SharengoCore\Entity\ExtraPayments) {
                                            foreach ($extraPayment->getExtraPaymentTries() as $extraPaymentTry){
                                                if ($extraPaymentTry->getOutcome() == 'OK') {
                                                    $res = $extraPaymentTry;
                                                } else {
                                                    $res = false;
                                                }
                                            }
                                            if(!$res){
                                                echo '-</td><td class="sng-text-center">-';
                                            }else{
                                                echo $extraPaymentTry->getTs()->format('d-m-Y H:i:s') . '</td>';
                                                echo '<td class="sng-text-center">' . date_diff($extraPayment->getFirstExtraTryTs(), $extraPaymentTry->getTs())->format($this->translate("%a giorni, %h ore, %i minuti"));
                                            }
                                        } else {
                                                    echo '-</td><td class="sng-text-center">-';
                                                }
                                        ?>
                                    </td>
                                    <td>
                                        <?php foreach ($extraPayment->getExtraPaymentTries() as $extraPaymentTry): ?>
                                        <p><?= $extraPaymentTry->getTs()->format('d-m-Y H:i:s'); ?> </p>
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customer-failure.js'; ?>"></script>
