<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-md-12">

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i>Elenco pagamenti falliti
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table id="failures-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Id Corsa</th>
                                    <th>Importo</th>
                                    <th>Data risoluzione</th>
                                    <th>Tempo risoluzione</th>
                                    <th>Tentativi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->tripPayments as $tripPayment): ?>
                                <tr>
                                    <td><a href="<?= $this->url('trips/details', ['id' => $tripPayment->getTrip()->getId()]); ?>"><?= $tripPayment->getTrip()->getId(); ?></a></td>
                                    <td class="sng-text-right"><?= sprintf('%01.2f €', $tripPayment->getTotalCost() / 100); ?></td>
                                    <td class="sng-date-column sng-text-center">
                                        <?php
                                            if ($tripPayment instanceof SharengoCore\Entity\TripPayments) {
                                            if ($tripPayment->getPayedSuccessfullyAt() instanceof \DateTime) {
                                                echo $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') . '</td>';
                                                //echo '<td class="sng-date-column">' . $tripPayment->getFirstPaymentTryTs()->format('d-m-Y H:i:s') . '</td>';
                                                echo '<td class="sng-text-center">' . date_diff($tripPayment->getFirstPaymentTryTs(), $tripPayment->getPayedSuccessfullyAt())->format('%a giorni, %h ore, %i minuti');
                                            } else {
                                                echo '-</td><td class="sng-text-center">-';
                                            }
                                            }
                                        ?>
                                    </td>
                                    <td><?= count($tripPayment->getTripPaymentTries()); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customer-failure.js'; ?>"></script>
