<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-md-12">

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i><?php echo $this->translate("Elenco pagamenti falliti"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table id="failures-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th><?php echo $this->translate("Id Corsa"); ?></th>
                                    <th><?php echo $this->translate("Importo"); ?></th>
                                    <th><?php echo $this->translate("Data risoluzione"); ?></th>
                                    <th><?php echo $this->translate("Tempo risoluzione"); ?></th>
                                    <th><?php echo $this->translate("Tentativi"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->tripPayments as $tripPayment): ?>
                                <tr>
                                    <td><a href="<?= $this->url('trips/details', ['id' => $tripPayment->getTrip()->getId()]); ?>"><?= $tripPayment->getTrip()->getId(); ?></a></td>
                                    <td class="sng-text-right"><?= sprintf('%01.2f €', $tripPayment->getTotalCost() / 100); ?></td>
                                    <td class="sng-date-column sng-text-center">
                                        <?php
                                            if ($tripPayment instanceof SharengoCore\Entity\TripPayments) {
                                            if ($tripPayment->getPayedSuccessfullyAt() instanceof \DateTime) {
                                                echo $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') . '</td>';
                                                //echo '<td class="sng-date-column">' . $tripPayment->getFirstPaymentTryTs()->format('d-m-Y H:i:s') . '</td>';
                                                echo '<td class="sng-text-center">' . date_diff($tripPayment->getFirstPaymentTryTs(), $tripPayment->getPayedSuccessfullyAt())->format($this->translate("%a giorni, %h ore, %i minuti"));
                                            } else {
                                                echo '-</td><td class="sng-text-center">-';
                                            }
                                            }
                                        ?>
                                    </td>
                                    <td>
                                        <?php foreach ($tripPayment->getTripPaymentTries() as $tripPaymentTry): ?>
                                        <p><?= $tripPaymentTry->getTs()->format('d-m-Y H:i:s'); ?> </p>
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customer-failure.js'; ?>"></script>
