<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/payments-csv.js');

$form = $this->form;
$form->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Title -->
        <h3 class="page-title"><?= $this->translate("Verifica CartaSI"); ?></h3>

        <!-- BEGIN tabs container -->
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span6">

                    <!-- BEGIN tabs -->
                    <div class="tabbable tabbable-custom">

                        <!-- BEGIN tabs headers -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_1_1" data-toggle="tab"><?= $this->translate("Gestione file"); ?></a></li>
                            <li><a href="#tab_1_2" data-toggle="tab"><?= $this->translate("Lista anomalie"); ?></a></li>
                        </ul>
                        <!-- END tabs headers -->

                        <div class="tab-content">

                            <!-- BEGIN file tab -->
                            <div class="tab-pane active" id="tab_1_1">

                            <?= $this->partial('partials/flash-messages.phtml', []); ?>

                                <!-- BEGIN upload form -->
                                <?= $this->form()->openTag($form); ?>
                                <h3><?= $this->translate("Carica nuovo file"); ?></h3>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <?= $this->formRow($form->get('csv-upload')); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <?= $this->formRow($form->get('submit')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?= $this->form()->closeTag(); ?>
                                <!-- END upload form -->

                                <!-- BEGIN new files table -->
                                <?php if (count($this->newFiles) > 0): ?>
                                <h3><?= $this->translate("Nuovi file"); ?></h3>
                                <table id="new-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate("Nome"); ?></th>
                                            <th><?= $this->translate("Data inserimento"); ?></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->newFiles as $file): ?>
                                        <tr>
                                            <td><?= $file['name'] ?></td>
                                            <td><?= $file['date']->format('Y-m-d H:i:s'); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-add-file', [], ['query' => ['filename' => $file['name']]]); ?>">Analizza</a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END new files table -->

                                <!-- BEGIN loaded files table -->
                                <?php if (count($this->csvFiles) > 0): ?>
                                <h3><?= $this->translate("File analizzati"); ?></h3>
                                <table id="analyzed-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate("Nome"); ?></th>
                                            <th><?= $this->translate("Data analisi"); ?></th>
                                            <th><?= $this->translate("Anomalie riscontrate"); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvFiles as $csvFile): ?>
                                        <tr>
                                            <td><?= $csvFile->getFilename() ?></td>
                                            <td><?= $csvFile->getInsertedTs()->format('Y-m-d H:i:s') ?></td>
                                            <td><a href="javascript:void()" class="anomalies"><?= count($csvFile->getCartasiCsvAnomalies()) ?></a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END loaded files table -->

                            </div>
                            <!-- END file tab -->

                            <!-- BEGIN anomalies tab -->
                            <div class="tab-pane " id="tab_1_2">

                                <!-- BEGIN unresolved table -->
                                <?php
                                $someAnomalyFound = false;
                                if (count($this->csvUnresolvedAnomalies) > 0):
                                    $someAnomalyFound = true;
                                ?>
                                <h3><?= $this->translate("Anomalie non risolte"); ?></h3>
                                <table id="unresolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate("File"); ?></th>
                                            <th><?= $this->translate("Data"); ?></th>
                                            <th><?= $this->translate("Tipologia"); ?></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvUnresolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('Y-m-d H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-details', ['id' => $csvAnomaly->getId()]); ?>"><?= $this->translate("Dettagli"); ?></a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END unresolved table -->

                                <!-- BEGIN resolved table -->
                                <?php
                                if (count($this->csvResolvedAnomalies) > 0):
                                    $someAnomalyFound = true;
                                ?>
                                <h3><?= $this->translate("Anomalie risolte"); ?></h3>
                                <table id="resolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate("File"); ?></th>
                                            <th><?= $this->translate("Data"); ?></th>
                                            <th><?= $this->translate("Tipologia"); ?></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvResolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('Y-m-d H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-details', ['id' => $csvAnomaly->getId()]); ?>"><?= $this->translate("Dettagli"); ?></a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END resolved table -->

                                <?php if (!$someAnomalyFound): ?>
                                <h4><?= $this->translate("Nessun anomalia trovata nei file analizzati."); ?></h4>
                                <?php endif; ?>

                            </div>
                            <!-- END anomalies tab -->

                        </div>
                    </div>
                    <!-- END tabs -->

                </div>
            </div>
        </div>
        <!-- END tabs container -->

    </div>
</div>

<script>
    $('.anomalies').click(function () {
        $('ul.nav-tabs li a[href="#tab_1_2"]').click();
    });
</script>
