<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/payments-csv.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Title -->
        <h3 class="page-title">Verifica CartaSI</h3>

        <!-- BEGIN tabs container -->
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span6">

                    <!-- BEGIN tabs -->
                    <div class="tabbable tabbable-custom">

                        <!-- BEGIN tabs headers -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_1_1" data-toggle="tab">Gestione file</a></li>
                            <li><a href="#tab_1_2" data-toggle="tab">Lista anomalie</a></li>
                        </ul>
                        <!-- END tabs headers -->

                        <div class="tab-content">

                            <!-- BEGIN file list tab -->
                            <div class="tab-pane active" id="tab_1_1">

                                <!-- BEGIN new files table -->
                                <?php if (count($this->newFiles) > 0): ?>
                                <h3>Nuovi file</h3>
                                <table id="new-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Data inserimento</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->newFiles as $file): ?>
                                        <tr>
                                            <td><?= $file['name'] ?></td>
                                            <td><?= $file['date']->format('d-m-Y H:i:s'); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-add-file', [], ['query' => ['filename' => $file['name']]]); ?>">Analizza</a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END new files table -->

                                <!-- BEGIN loaded files table -->
                                <?php if (count($this->csvFiles) > 0): ?>
                                <h3>File analizzati</h3>
                                <table id="analyzed-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Data analisi</th>
                                            <th>Anomalie riscontrate</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvFiles as $csvFile): ?>
                                        <tr>
                                            <td><?= $csvFile->getFilename() ?></td>
                                            <td><?= $csvFile->getInsertedTs()->format('d-m-Y H:i:s') ?></td>
                                            <td><?= count($csvFile->getCartasiCsvAnomalies()) ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END loaded files table -->

                            </div>
                            <!-- END file list tab -->

                            <!-- BEGIN anomalies tab -->
                            <div class="tab-pane " id="tab_1_2">

                                <!-- BEGIN unresolved table -->
                                <?php
                                $someAnomalyFound = false;
                                if (count($this->csvUnresolvedAnomalies) > 0):
                                    $someAnomalyFound = true;
                                ?>
                                <h3>Anomalie non risolte</h3>
                                <table id="unresolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>File</th>
                                            <th>Data</th>
                                            <th>Tipologia</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvUnresolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-details', ['id' => $csvAnomaly->getId()]); ?>">Dettagli</a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END unresolved table -->

                                <!-- BEGIN resolved table -->
                                <?php
                                if (count($this->csvResolvedAnomalies) > 0):
                                    $someAnomalyFound = true;
                                ?>
                                <h3>Anomalie risolte</h3>
                                <table id="resolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>File</th>
                                            <th>Data</th>
                                            <th>Tipologia</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvResolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><a href="<?= $this->url('payments/csv-details', ['id' => $csvAnomaly->getId()]); ?>">Dettagli</a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END resolved table -->

                                <?php if (!$someAnomalyFound): ?>
                                <h4>Nessun anomalia trovata nei file analizzati.</h4>
                                <?php endif; ?>

                            </div>
                            <!-- END anomalies tab -->

                        </div>
                    </div>
                    <!-- END tabs -->

                </div>
            </div>
        </div>
        <!-- END tabs container -->

    </div>
</div>
