<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Title -->
        <h3 class="page-title">Verifica CartaSI</h3>

        <!-- BEGIN tabs container -->
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span6">

                    <!-- BEGIN tabs -->
                    <div class="tabbable tabbable-custom">

                        <!-- BEGIN tabs headers -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_1_1" data-toggle="tab">Gestione file</a></li>
                            <li><a href="#tab_1_2" data-toggle="tab">Lista anomalie</a></li>
                        </ul>
                        <!-- END tabs headers -->

                        <div class="tab-content">

                            <!-- BEGIN file list tab -->
                            <div class="tab-pane active" id="tab_1_1">

                                <!-- BEGIN new files table -->
                                <?php if (count($this->newFileNames) > 0): ?>
                                <h3>Nuovi file</h3>
                                <table id="new-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Data caricamento</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->newFileNames as $name): ?>
                                        <tr>
                                            <td><?= $name ?></td>
                                            <td><?= 'xx/xx/xxxx' ?></td>
                                            <td><a href="<?= $this->url('payments/csv-add-file', [], ['query' => ['filename' => $name]]); ?>">Inserisci</a></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END new files table -->

                                <!-- BEGIN loaded files table -->
                                <?php if (count($this->csvFiles) > 0): ?>
                                <h3>File caricati</h3>
                                <table id="loaded-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Data inserimento</th>
                                            <th>Analizzato</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvFiles as $csvFile): ?>
                                        <tr>
                                            <td><?= $csvFile->getFilename() ?></td>
                                            <td><?= $csvFile->getInsertedTs()->format('d-m-Y H:i:s') ?></td>
                                            <td>
                                                <?php if ($csvFile->isAnalyzed()): ?>
                                                Si
                                                <?php else: ?>
                                                <a href="<?= $this->url('payments/csv-analyze-file', [], ['query' => ['csvFileId' => $csvFile->getId()]]); ?>">Analizza</a>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END loaded files table -->

                            </div>
                            <!-- END file list tab -->

                            <!-- BEGIN anomalies tab -->
                            <div class="tab-pane " id="tab_1_2">

                                <!-- BEGIN unresolved table -->
                                <?php if (count($this->csvUnresolvedAnomalies) > 0): ?>
                                <h3>Anomalie non risolte</h3>
                                <table id="unresolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>File</th>
                                            <th>Data</th>
                                            <th>Tipologia</th>
                                            <th>Dati file</th>
                                            <th>Transazione</th>
                                            <th>Modifiche</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvUnresolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><?= 'dati test csv'; ?></td>
                                            <td>
                                                <?php
                                                $transaction = $csvAnomaly->getTransaction();
                                                if ($transaction instanceof Cartasi\Entity\Transactions) {
                                                     echo $transaction->getId();
                                                 } else {
                                                    echo '-';
                                                 }
                                                 ?>
                                            </td>
                                            <td><?= 'updates test'; ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END unresolved table -->

                                <!-- BEGIN resolved table -->
                                <?php if (count($this->csvResolvedAnomalies) > 0): ?>
                                <h3>Anomalie risolte</h3>
                                <table id="resolved-table" class="table table-striped table-bordered table-hover sng-margin-top">
                                    <thead>
                                        <tr>
                                            <th>File</th>
                                            <th>Data</th>
                                            <th>Tipologia</th>
                                            <th>Dati file</th>
                                            <th>Transazione</th>
                                            <th>Modifiche</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->csvResolvedAnomalies as $csvAnomaly): ?>
                                        <tr>
                                            <td><?= $csvAnomaly->getCartasiCsvFile()->getFilename(); ?></td>
                                            <td><?= $csvAnomaly->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                            <td><?= $csvAnomaly->getTypeTranslated(); ?></td>
                                            <td><?= 'dati test csv'; ?></td>
                                            <td>
                                                <?php
                                                $transaction = $csvAnomaly->getTransaction();
                                                if ($transaction instanceof Cartasi\Entity\Transactions) {
                                                     echo $transaction->getId();
                                                 } else {
                                                    echo '-';
                                                 }
                                                 ?>
                                            </td>
                                            <td><?= 'updates test'; ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                                <!-- END resolved table -->

                            </div>
                            <!-- END anomalies tab -->

                        </div>
                    </div>
                    <!-- END tabs -->

                </div>
            </div>
        </div>
        <!-- END tabs container -->

    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/payments-csv.js'; ?>"></script>
