<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Title -->
        <h3 class="page-title">Dettagli Anomalia</h3>

        <!-- BEGIN content container -->
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span6">

                    <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                    <!-- BEGIN csv data container -->
                    <div class="portlet box green row">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-file-text-o"></i>Dati csv
                            </div>
                        </div>

                        <div class="portlet-body col-lg-12">
                            <?php
                            $csvData = $this->csvAnomaly->getCsvData();
                            ksort($csvData);
                            foreach ($csvData as $key => $data):
                            ?>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $key; ?></label>
                                    <div class="sng-info-box sng-info-box-fixed"><?= $data ?></div>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <!-- END csv data container -->

                    <!-- BEGIN transaction container -->
                    <div class="portlet box green row">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-credit-card"></i>Dati transazione
                            </div>
                        </div>

                        <div class="portlet-body col-lg-12">

                        </div>
                    </div>
                    <!-- END transaction container -->

                    <!-- BEGIN solutions container -->
                    <div class="portlet box green row">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-calculator"></i>Soluzioni
                            </div>
                        </div>

                        <div class="portlet-body col-lg-12">

                        </div>
                    </div>
                    <!-- END solutions container -->

                    <!-- BEGIN note container -->
                    <div class="portlet box green row">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-paperclip"></i>Note
                            </div>
                        </div>

                        <div class="portlet-body col-lg-12">

                            <!-- BEGIN notes table -->
                            <?php
                            $updates = $this->csvAnomaly->getUpdates();
                            if (!empty($updates)):
                            ?>
                            <h4>Elenco Note</h4>

                            <table id="notes-table" class="table table-striped table-bordered table-hover" id="js-invoices-table">
                                <thead>
                                    <tr>
                                        <th>Data</th>
                                        <th>Id Webuser</th>
                                        <th>Nota</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($updates as $date => $note): ?>
                                    <tr>
                                        <td class="sng-date-column"><?= $date; ?></td>
                                        <td><?= $note['webuser']; ?></td>
                                        <td><?= $note['content']; ?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>

                            <!-- END notes table -->
                            <?php endif; ?>

                            <!-- BEGIN new note -->
                            <h4>Nuova Nota</h4>
                            <form action="<?= $this->url('payments/csv-add-note', ['id' => $this->csvAnomaly->getId()]); ?>"
                                method="post">

                                <textarea id="new-note" name="new-note" style="width: 100%" rows="5"></textarea><br><br>
                                <input id="add-button"
                                    class="btn btn-default btn-xs"
                                    type="submit"
                                    value="Aggiungi">
                                </input>

                            </form>
                            <!-- END new note -->

                        </div>
                    </div>
                    <!-- END note container -->

                </div>
            </div>
        </div>
        <!-- END content container -->

    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/payments-csv-details.js'; ?>"></script>
