<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
?>

<?php
$safoPenalty = $this->safoPenalty;
?>

<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("Dettagli multa"); ?>
        </h3>

        <div class="row">
            <div class="col-lg-12">
                <a href="/fines" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> Torna alla lista</a>
            </div>
        </div>

        <hr>

        <!-- Details table -->
        <div class="row">
            <div class="col-lg-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-server"></i><?= $this->translate("Riepilogo"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID multa"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getRusId() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Data multa"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getViolationTimestamp()->format("d-m-Y H:i:s") ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID cliente"); ?></label>
                                    <div class="sng-info-box"><?= (($safoPenalty->getCustomerId()>0) ? '<a href="/customers/edit/'.$safoPenalty->getCustomerId().'">'.$safoPenalty->getCustomerId().'</a>' : $safoPenalty->getCustomerId()) ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID corsa"); ?></label>
                                    <div class="sng-info-box"><?= (($safoPenalty->getTripId()>0) ? '<a href="/trips/details/'.$safoPenalty->getTripId().'">'.$safoPenalty->getTripId().'</a>' : $safoPenalty->getTripId()) ?></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Flotta veicolo"); ?></label>
                                    <div class="sng-info-box"><?
                                                                switch ($safoPenalty->getVehicleFleetId()){
                                                                    case 1:
                                                                        echo "Milano";
                                                                        break;
                                                                    case 2:
                                                                        echo "Firenze";
                                                                        break;
                                                                    case 3:
                                                                        echo "Roma";
                                                                        break;
                                                                    case 4:
                                                                        echo "Modena";
                                                                        break;
                                                                    default:
                                                                        echo "Non specificato";
                                                                        break;
                                                                }
                                                                ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Targa"); ?></label>
                                    <div class="sng-info-box"><?= ((strlen($safoPenalty->getCarPlate())>0) ? '<a href="/cars/edit/'.$safoPenalty->getCarPlate().'">'.$safoPenalty->getCarPlate().'</a>' : $safoPenalty->getCarPlate()) ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Categoria multa"); ?></label>
                                    <div class="sng-info-box"><?= ($safoPenalty->getViolationCategory()===0 ? "Nessuna categoria" : $safoPenalty->getViolationCategory()) ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Violation Authority"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getViolationAuthority() ?></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Descrizione Multa"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getViolationDescription() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Numero Multa"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getViolationNumber() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Status Multa"); ?></label>
                                    <div class="sng-info-box"><?
                                                                switch ($safoPenalty->getViolationStatus()){
                                                                    case "R":
                                                                        echo "Reintestata";
                                                                        break;
                                                                    case "C":
                                                                        echo "Contestata";
                                                                        break;
                                                                    case "P":
                                                                        echo "Pagata";
                                                                        break;
                                                                    default:
                                                                        echo "Non specificato";
                                                                        break;
                                                                }
                                                                ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Tipologia Richiesta Multa"); ?></label>
                                    <div class="sng-info-box"><?= $safoPenalty->getViolationRequestType() ?></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Costo multa"); ?></label>
                                    <div class="sng-info-box"><?= number_format(($safoPenalty->getAmount()/100),2,",","'"); ?>&euro;</div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Completato"); ?></label>
                                    <div class="sng-info-box"><?= ($safoPenalty->isComplete() ? "Completo" : "Non completo")  ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Addebitato"); ?></label>
                                    <div class="sng-info-box"><?= ($safoPenalty->isCharged() ? "SI" : "NO") ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Data Addebito"); ?></label>
                                    <div class="sng-info-box"><?= (is_null($safoPenalty->getConsumedTs()) ? "Non addebitato" : $safoPenalty->getConsumedTs()->format("d-m-Y H:i:s") ) ?></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- details table -->

        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var safoPenaltyId = "<?= $this->safoPenalty->getId() ?>";
</script>
