<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/fines.js');
?>

<?php
$tripPayment = $this->tripPayment;
$customer = $this->customer;
?>

<div class="page-content-wrapper">
    <div class="page-content">
        <? 
        echo 'test';
        /*
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("Dettagli multa"); ?>
        </h3>

        <div class="row">
            <div class="col-md-8">
                <div class="form-inline">
                    <div class="btn-group">
                        <button type="button" class="btn green" id="js-new-try">
                            <i class="fa fa-try"></i>
                            <?= $this->translate("Back"); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <!-- Details table -->
        <div class="row">
            <div class="col-lg-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-server"></i><?= $this->translate("Riepilogo"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID multa"); ?></label>
                                    <div class="sng-info-box"><?= $tripPayment->getTrip()->getId() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("Data"); ?></label>
                                    <div class="sng-info-box"><?= $tripPayment->getCreatedAt()->format("d-m-Y H:i:s") ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID cliente"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getName() ?></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label><?= $this->translate("ID corsa"); ?></label>
                                    <div class="sng-info-box"><?= $customer->getSurname() ?></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- details table -->

        <!-- END PAGE CONTENT-->
        */?>
    </div>
</div>
<script>
    var safoPenaltyId = "<?= $this->safoPenalty->getId() ?>",
</script>
