<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/js/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() . '/js/datatable-session-data.js')
    ->appendFile($this->basePath() . '/js/fines.js?v=1.5');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO MULTE"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>
        <div class="page-bar">
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="e.id"><?= $this->translate("ID"); ?></option>
                                    <option value="c.plate"><?= $this->translate("Targa"); ?></option>
                                    <option value="f.name"><?= $this->translate("Flotta"); ?></option>
                                    <option value="cu.id"><?= $this->translate("ID Cliente"); ?></option>
                                    <option value="t.id"><?= $this->translate("ID Corsa"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                        </div>
                    </div>      
                    <div class="col-md-6">
                        <div class="form-inline">
                            <div class="form-group">
                                <label> <?= $this->translate("da"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-from"
                                       placeholder="<?= $this->translate("Data inizio"); ?>">
                            </div>
                            <div class="form-group">
                                <label> <?= $this->translate("a"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-to"
                                       placeholder="<?= $this->translate("Data fine"); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-success pull-right" id="pay-fines" data-toggle="modal" data-target="#myModal" style="display: none"></button>
                    </div>
                </div>
                <br>
                <div class="row text-right">
                    <!--
                    <div class="col-md-10">
                        <div class="form-inline">
                            <div class="form-group">
                                <label> <?= $this->translate("da"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-from"
                                       placeholder="<?= $this->translate("Data inizio"); ?>">
                            </div>
                            <div class="form-group">
                                <label> <?= $this->translate("a"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-to"
                                       placeholder="<?= $this->translate("Data fine"); ?>">
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-success pull-right" id="pay-fines-betweenDate" data-toggle="modal" data-target="#myModal">Paga</button>
                            </div>
                        </div>
                    </div>
                    -->
                    
                </div>
                
                
                <div class="modal fade" id="myModal" role="dialog" data-keyboard="false" data-backdrop="static">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="titleModal"></h4>
                            </div>
                            <center>
                                <div class="modal-body">
                                    <div id="body-text-modal"></div>
                                </div>
                            </center>
                            <div class="modal-footer">
                                <div id="conteiner-btn">
                                    <button type="button" id="btn-pay" class="btn btn-default" style="display: none">Paga multe</button>
                                    <button type="button" id="btn-modal-close" class="btn btn-default" data-dismiss="modal" style="display: none">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                
                
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco multe"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-fines-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("ID"); ?></th>
                                <th><center><input type="checkbox" id='checkAll'/></th>
                                <th><?= $this->translate("Pagato"); ?></th>
                                <th><?= $this->translate("ID cliente"); ?></th>
                                <th><?= $this->translate("Descrizione"); ?></th>
                                <th><?= $this->translate("Flotta"); ?></th>
                                <th><?= $this->translate("ID Corsa"); ?></th>
                                <th><?= $this->translate("Targa"); ?></th>
                                <th><?= $this->translate("Autorità"); ?></th>
                                <th><?= $this->translate("Costo"); ?></th>
                                <th><?= $this->translate("Status"); ?></th>
                                <th><?= $this->translate("Data Infrazione"); ?></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<script>
    var filters = <?= $this->filters ?>;
    
    $('#js-date-from').datepicker({
        autoclose: true,
        format: "yyyy-mm-dd"
    });
    
    $('#js-date-to').datepicker({
        autoclose: true,
        format: "yyyy-mm-dd"
    });
    
</script>