<div class="row">
    <div class="col-lg-9">

        <div class="panel panel-default">
            <div class="panel-heading">Chiudi corsa</div>
            <div class="panel-body">
                <form method="post" action="<?= $this->url('trips/do-close/post'); ?>">
                    <input type="hidden" name="id" value="<?= $this->trip->getId(); ?>">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="gender">Data e ora chiusura</label>
                                <input type="text" name="datetime" id="datetime" class="form-control date-picker">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="name">Pagabile</label>
                                <select name="payable" id="payable" class="form-control">
                                    <option value="none">-</option>
                                    <option value="yes">Sì</option>
                                    <option value="no">No</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success">Chiudi corsa</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#datetime').datetimepicker({
        format: "DD-MM-YYYY HH:mm:ss"
    });
</script>