<?php
// Get data
$trip = $this->trip;

$tripPayment = $trip->getTripPayment();
$tripBonuses = $trip->getTripBonuses();

$businessTripFare = $this->businessTripFare;
$businessTripPayment = $this->businessTripPayment;
$businessInvoice = $this->businessInvoice;

// Parse payment
$tripFare = 'n.a.';
$parkingFare = 'n.a.';
$amount = 'n.a.';
$payable = 'n.a.';
$payed = 'NO';
$invoiced = 'NO';
$motionDiscount = "n.a.";
$parkingDiscount = "n.a.";

$pinType = $trip->getPinType();

if(is_null($pinType)) {
    // trip private (no business)
    if ($trip->getIsaccounted()) {
        $amount = 0;
    }

    if (!is_null($tripPayment)) {
        //if(false) {
        $fare = $tripPayment->getFare();
        $tripFare = $fare->getMotionCostPerMinute() . ' cent/min';
        $parkingFare = $fare->getParkCostPerMinute() . ' cent/min';

        $amount = $tripPayment->getTotalCost();
        $amount = floor($amount / 100) . ',' . ($amount % 100 < 10 ? '0' : '') . $amount % 100 . ' €';
        $motionDiscount = $trip->getDiscountPercentage() . ' %';
        $parkingDiscount = '-';
        $payable = $trip->getPayable() ? $this->translate("SI") : $this->translate("NO");

        $payed = $tripPayment->getPayedSuccessfullyAt() !== null ?
            $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') :
            $payed;

        $invoiced = $tripPayment->getInvoice() !== null ?
            $tripPayment->getInvoicedAt()->format('d-m-Y H:i:s') .
                ' <a href=' .
                $this->url('pdf/invoices') . '/' .
                $tripPayment->getInvoice()->getId() .
                '><i class="fa fa-download"></i></a>' :
            $invoiced;
    }
} else {
    // trip business
    if (!is_null($businessTripFare)) {
        $motionDiscount = $businessTripFare->getMotionDiscount() . ' %';
        $parkingDiscount = $businessTripFare->getParkDiscount() . ' %';

        $b2bMotionFare = round($businessTripFare->getBaseFareMotionCostPerMinute()  * ((100-$businessTripFare->getMotionDiscount())/100));
        $b2bParkingFare = round($businessTripFare->getBaseFareParkCostPerMinute() * ((100-$businessTripFare->getParkDiscount())/100));
        $tripFare = $b2bMotionFare . ' cent/min';
        $parkingFare = $b2bParkingFare . ' cent/min';
    }

    if (!is_null($businessTripPayment)) {
        $payable = $this->translate("SI");
        $currency = $businessTripPayment->getCurrency();
        $amount = sprintf('%.2f %s',
            round($businessTripPayment->getAmount()/100, 2),
            $currency);

        if(!is_null($businessTripPayment->getPayedOnTs())) {
            $payed = $businessTripPayment->getPayedOnTs()->format('d-m-Y H:i:s');
        }

        if(!is_null($businessInvoice)){
            $invoiced = $businessInvoice->getGeneratedTs()->format('d-m-Y H:i:s');
        }
    }
}


?>

<div class="row">
    <div class="col-lg-9">


        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Dettagli Corsa"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Inizio"); ?></label>
                            <div class="sng-info-box"><?= $trip->getTimestampBeginning()->format('d-m-Y H:i:s') ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label>Fine</label>
                            <div class="sng-info-box"><?= (null != $trip->getTimestampEnd() ? $trip->getTimestampEnd()->format('d-m-Y H:i:s') : $this->translate('n.d.')) ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Durata totale"); ?></label>
                            <div class="sng-info-box"><?= $trip->getDurationMinutes() ?> <?= $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Durata effettiva"); ?></label>
                            <div class="sng-info-box"><?= $trip->getDurationMinutes() - round($trip->getParkSeconds()/60) ?> <?= $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Tariffa corsa"); ?></label>
                            <div class="sng-info-box"><?= $tripFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Sconto corsa"); ?></label>
                            <div class="sng-info-box"><?= $motionDiscount; ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Durata sosta"); ?></label>
                            <div class="sng-info-box"><?= round($trip->getParkSeconds()/60)?> <?= $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Tariffa sosta"); ?></label>
                            <div class="sng-info-box"><?= $parkingFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label><?= $this->translate("Sconto sosta"); ?></label>
                            <div class="sng-info-box"><?= $parkingDiscount ?></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <?php if(count($trip->getTripBills()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Minuti addebitati"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?= $this->translate("Dal"); ?></th>
                            <th><?= $this->translate("Fino al"); ?></th>
                            <th><?= $this->translate("Minuti"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripBills $tripBill */
                    foreach($trip->getTripBills() as $tripBill) { ?>
                        <tr>
                            <td><?= $tripBill->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBill->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBill->getMinutes() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

        <?php if(count($trip->getTripBonuses()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Minuti bonus usufruiti"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?= $this->translate("Dal"); ?></th>
                            <th><?= $this->translate("Fino al"); ?></th>
                            <th><?= $this->translate("Minuti"); ?></th>
                            <th><?= $this->translate("Descrizione bonus"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripBonuses $tripBonuses */
                    foreach($trip->getTripBonuses() as $tripBonuses) { ?>
                        <tr>
                            <td><?= $tripBonuses->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBonuses->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBonuses->getMinutes() ?></td>
                            <td><?= $tripBonuses->getBonus()->getDescription() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

        <?php if(count($trip->getTripFreeFares()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Sconti / tariffe speciali"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?= $this->translate("Dal"); ?></th>
                            <th><?= $this->translate("Fino al"); ?></th>
                            <th><?= $this->translate("Minuti"); ?></th>
                            <th><?= $this->translate("Descrizione sconto / tariffa speciale"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripFreeFares $tripFreeFare */
                    foreach($trip->getTripFreeFares() as $tripFreeFare) { ?>
                        <tr>
                            <td><?= $tripFreeFare->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripFreeFare->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripFreeFare->getMinutes() ?></td>
                            <td><?= $tripFreeFare->getFreeFare()->getDescription() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading"><?= $this->translate("Dati pagamento"); ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Pagabile"); ?></label>
                            <div class="sng-info-box"><?= $payable ?></div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Pagata"); ?></label>
                            <div class="sng-info-box"><?= $payed ?></div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Importo"); ?></label>
                            <div class="sng-info-box"><?= $amount ?></div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Fatturata"); ?></label>
                            <div class="sng-info-box"><?= $invoiced ?></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
