<?php
// Get data
$trip = $this->trip;
$tripPayment = $this->tripPayment;
$customer = $trip->getCustomer();
$tripBonuses = $this->tripBonuses;
$tripFreeFares = $this->tripFreeFares;

// Parse payment
$tripFare = 'n.a.';
$parkingFare = 'n.a.';
$amount = 'n.a.';
$payed = 'NO';

if ($tripPayment !== null) {
    $fare = $tripPayment->getFare();
    $tripFare = $fare->getMotionCostPerMinute() . ' cent/min';
    $parkingFare = $fare->getParkCostPerMinute() . ' cent/min';

    $amount = $tripPayment->getTotalCost();
    $amount = floor($amount / 100) . ',' . ($amount % 100 < 10 ? '0' : '') . $amount % 100 . '€';

    $payed = $tripPayment->getPayedSuccessfullyAt() !== null ?
        $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') :
        $payed;
}

?>

<div class="row">
    <div class="col-lg-9">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="panel panel-default">
            <div class="panel-heading">Dettagli Corsa</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Id</label>
                            <div class="sng-info-box"><?= $trip->getId() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Nome</label>
                            <div class="sng-info-box"><?= $customer->getName() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Cognome</label>
                            <div class="sng-info-box"><?= $customer->getSurname() ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Tariffa corsa</label>
                            <div class="sng-info-box"><?= $tripFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Tariffa sosta</label>
                            <div class="sng-info-box"><?= $parkingFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Sconto</label>
                            <div class="sng-info-box"><?= $customer->getDiscountRate() . '%' ?></div>
                        </div>
                    </div>
                </div>

                <?php foreach ($tripFreeFares as $tripFreeFare): ?>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Descrizione</label>
                            <div class="sng-info-box"><?= $tripFreeFare->getFreeFare()->getDescription() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Minuti</label>
                            <div class="sng-info-box"><?= $tripFreeFare->getMinutes() . ' min.' ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Sconto</label>
                            <div class="sng-info-box"><?= '100%' ?></div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>

                <?php foreach ($tripBonuses as $tripBonus): ?>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Descrizione</label>
                            <div class="sng-info-box"><?= 'Utilizzo minuti bonus' ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Minuti</label>
                            <div class="sng-info-box"><?= $tripBonus->getMinutes() . ' min.' ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Sconto</label>
                            <div class="sng-info-box"><?= '100%' ?></div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>

            </div>
        </div>

    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading">Dati pagamento</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Importo</label>
                            <div class="sng-info-box"><?= $amount ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Pagabile</label>
                            <div class="sng-info-box"><?= $trip->getPayable() ? 'SI' : 'NO' ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Pagata</label>
                            <div class="sng-info-box"><?= $payed ?></div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>
