<?php
// Get data
$trip = $this->trip;
$customer = $trip->getCustomer();
$tripPayment = $trip->getTripPayment();
$tripFreeFares = $trip->getTripFreeFares();
$tripBonuses = $trip->getTripBonuses();

// Parse payment
$tripFare = 'n.a.';
$parkingFare = 'n.a.';
$amount = 'n.a.';
$payed = 'NO';

if ($trip->getIsaccounted()) {
    $amount = 0;
}

if ($tripPayment !== null) {
    $fare = $tripPayment->getFare();
    $tripFare = $fare->getMotionCostPerMinute() . ' cent/min';
    $parkingFare = $fare->getParkCostPerMinute() . ' cent/min';

    $amount = $tripPayment->getTotalCost();
    $amount = floor($amount / 100) . ',' . ($amount % 100 < 10 ? '0' : '') . $amount % 100 . '€';

    $payed = $tripPayment->getPayedSuccessfullyAt() !== null ?
        $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') :
        $payed;
}

?>

<div class="row">
    <div class="col-lg-9">


        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Dettagli Corsa"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?php echo $this->translate("Inizio"); ?></label>
                            <div class="sng-info-box"><?= $trip->getTimestampBeginning()->format('d-m-Y H:i:s') ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Fine</label>
                            <div class="sng-info-box"><?= (null != $trip->getTimestampEnd() ? $trip->getTimestampEnd()->format('d-m-Y H:i:s') : 'n.d.') ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?php echo $this->translate("Durata"); ?></label>
                            <div class="sng-info-box"><?= $trip->getDurationMinutes() ?> <?php echo $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?php echo $this->translate("Tariffa corsa"); ?></label>
                            <div class="sng-info-box"><?= $tripFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?php echo $this->translate("Tariffa sosta"); ?></label>
                            <div class="sng-info-box"><?= $parkingFare ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?php echo $this->translate("Sconto cliente"); ?></label>
                            <div class="sng-info-box"><?= $customer->getDiscountRate() . '%' ?></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <?php if(count($trip->getTripBills()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Minuti addebitati"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("Dal"); ?></th>
                            <th><?php echo $this->translate("Fino al"); ?></th>
                            <th><?php echo $this->translate("Minuti"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripBills $tripBill */
                    foreach($trip->getTripBills() as $tripBill) { ?>
                        <tr>
                            <td><?= $tripBill->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBill->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBill->getMinutes() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

        <?php if(count($trip->getTripBonuses()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Minuti bonus usufruiti"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("Dal"); ?></th>
                            <th><?php echo $this->translate("Fino al"); ?></th>
                            <th><?php echo $this->translate("Minuti"); ?></th>
                            <th><?php echo $this->translate("Descrizione bonus"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripBonuses $tripBonuses */
                    foreach($trip->getTripBonuses() as $tripBonuses) { ?>
                        <tr>
                            <td><?= $tripBonuses->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBonuses->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripBonuses->getMinutes() ?></td>
                            <td><?= $tripBonuses->getBonus()->getDescription() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

        <?php if(count($trip->getTripFreeFares()) > 0) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate("Sconti / tariffe speciali"); ?></div>
            <div class="panel-body">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("Dal"); ?></th>
                            <th><?php echo $this->translate("Fino al"); ?></th>
                            <th><?php echo $this->translate("Minuti"); ?></th>
                            <th><?php echo $this->translate("Descrizione sconto / tariffa speciale"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \SharengoCore\Entity\TripFreeFares $tripFreeFare */
                    foreach($trip->getTripFreeFares() as $tripFreeFare) { ?>
                        <tr>
                            <td><?= $tripFreeFare->getTimestampBeginning()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripFreeFare->getTimestampEnd()->format('d-m-Y H:i:s') ?></td>
                            <td><?= $tripFreeFare->getMinutes() ?></td>
                            <td><?= $tripFreeFare->getFreeFare()->getDescription() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php } ?>

    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading"><?php echo $this->translate("Dati pagamento"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label><?php echo $this->translate("Importo"); ?></label>
                            <div class="sng-info-box"><?= $amount ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label><?php echo $this->translate("Pagabile"); ?></label>
                            <div class="sng-info-box"><?= $trip->getPayable() ? $this->translate("SI") : $this->translate("NO") ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?php echo $this->translate("Pagata"); ?></label>
                            <div class="sng-info-box"><?= $payed ?></div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>
