<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->headLink()->appendStylesheet('/css/addons.css');
$this->headScript()
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js');
?>

<!-- Edit table -->
<div class="row">
    <div class="col-lg-12">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-server"></i>Dati corsa
                </div>
            </div>
            <div class="portlet-body">

                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>test</label>
                            <div class="sng-info-box"><?= 'test' ?></div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>test</label>
                            <div class="sng-info-box"><?= 'test' ?></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- edit table -->
