<?php
$timestampEnd = '';
// if trip is not yet closed
if ($this->trip->getTimestampEnd() === null) {
?>

<div class="row">
    <div class="col-lg-12">
        <p>La corsa non può essere modificata perché non risulta ancora conclusa.</p>
    </div>
</div>

<?php
// if trip has been payed (or even just tried)
} elseif (count($this->trip->getTripPayments()) != 0 &&
    count($this->trip->getTripPayments()[0]->getTripPaymentTries()) != 0) {
?>

<div class="row">
    <div class="col-lg-12">
        <p>La corsa non può essere modificata perché la procedura di pagamento è già iniziata.</p>
    </div>
</div>

<?php
// if trip can be edited
} else {
    $form = $this->editTripForm->prepare();
    $form->setAttribute('action', $this->url('trips/edit-tab', ['id' => $this->trip->getId()]));
    $trip = $this->trip;
    $timestampEnd = $trip->getTimestampEnd()->format('d-m-Y H:i:s');
?>

<?= $this->form()->openTag($form); ?>
<!-- Edit table -->
<div class="row">
    <div class="col-lg-12">
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-server"></i>Dati corsa
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Data fine attuale</label>
                            <div class="sng-info-box"><?= $timestampEnd ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Nuova data fine <span class="sng-hint">(non precedente a quella attuale)</span></label>
                            <?= $this->formRow($form->get('trip')->get('timestampEnd')); ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Pagabile</label>
                            <?= $this->formRow($form->get('trip')->get('payable')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success">Salva Dati Corsa</button>
                    </div>
                </div>
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- edit table -->
<?php echo $this->form()->closeTag(); ?>

<!-- Events table -->
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <!-- Header -->
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>Elenco eventi
                </div>
            </div>
            <!-- header -->
            <!-- Body -->
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Data</th>
                            <th>Batteria</th>
                            <th>Km</th>
                            <th>Evento</th>
                            <th>Valore</th>
                            <th>Intval</th>
                            <th>Posizione</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->events as $event): ?>
                            <tr>
                                <td><?= $event->getId() ?></td>
                                <td><?= $event->getEventTime()->format('d-m-Y H:i:s') ?></td>
                                <td><?= $event->getBattery() . '%' ?></td>
                                <td><?= $event->getKm() ?></td>
                                <td><?= $event->getEventId() ?></td>
                                <td><?= $event->getTxtval() ?></td>
                                <td><?= $event->getIntval() ?></td>
                                <td>
                                    <a href="http://maps.google.com/?q=<?= $event->getLat() ?>,<?= $event->getLon() ?>" target="_blank">
                                        <?= 'Lat: ' . $event->getLat() . '<br>' .
                                        'Lon: ' . $event->getLon() ?>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <!-- body -->
        </div>
    </div>
</div>
<!-- events table -->

<?php
// close editable trip section
}
?>
<script>
var timestampEnd = '<?= $timestampEnd ?>';
var payable = <?= $trip->getPayable() ? 'true' : 'false' ?>;
</script>
<script type="text/javascript" src="/js/edit-trip.js"></script>
