<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/js/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() . '/js/trips.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO CORSE"); ?>
            <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <?= $this->datatableFilters('trips-index') ?>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?= $this->translate("Elenco Corse"); ?>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-trips-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Id Corsa"); ?></th>
                                <th><?= $this->translate("eMail"); ?></th>
                                <th><?= $this->translate("Cognome"); ?></th>
                                <th><?= $this->translate("Nome"); ?></th>
                                <th><?= $this->translate("Cellulare"); ?></th>
                                <th><?= $this->translate("RFID"); ?></th>
                                <th><?= $this->translate("Targa"); ?></th>
                                <th><?= $this->translate("Km Inizio"); ?></th>
                                <th><?= $this->translate("Km Fine"); ?></th>
                                <th style="min-width: 60px !important;"><?= $this->translate("Inizio"); ?></th>
                                <th style="min-width: 60px !important;"><?= $this->translate("Fine"); ?></th>
                                <th style="min-width: 80px !important;"><?= $this->translate("Durata"); ?></th>
                                <th><?= $this->translate("Sosta"); ?></th>
                                <th><?= $this->translate("Stato Quadro"); ?></th>
                                <th><?= $this->translate("In sosta"); ?></th>
                                <th><?= $this->translate("Pagabile"); ?></th>
                                <th><?= $this->translate("Pagata"); ?></th>
                                <th><?= $this->translate("Costo"); ?></th>
                                <th><?= $this->translate("Flotta"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
