<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/js/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() .'/js/trips.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?php echo $this->translate("ELENCO CORSE"); ?> <small><?php echo $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-5">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?php echo $this->translate("Seleziona"); ?> --</option>
                                    <option value="c.timestampEnd"><?php echo $this->translate("Corse Aperte"); ?></option>
                                    <option value="e.id"><?php echo $this->translate("ID Corsa"); ?></option>
                                    <option value="cu.id"><?php echo $this->translate("ID Cliente"); ?></option>
                                    <option value="cu.surname"><?php echo $this->translate("Cognome Cliente"); ?></option>
                                    <option value="cu.email"><?php echo $this->translate("eMail Cliente"); ?></option>
                                    <option value="cc.code"><?php echo $this->translate("RFID"); ?></option>
                                    <option value="c.plate"><?php echo $this->translate("Targa"); ?></option>
                                    <option value="c.label"><?php echo $this->translate("Numero"); ?></option>
                                    <option value="payed"><?php echo $this->translate("Corse non pagate"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?php echo $this->translate("Filtra..."); ?>">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="form-inline">
                            <div class="form-group">
                                <label> da: </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" id="js-date-from" placeholder="<?php echo $this->translate("Seleziona data inizio"); ?>">
                            </div>
                            <div class="form-group">
                                <label> a: </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" id="js-date-to" placeholder="<?php echo $this->translate("Seleziona data fine"); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i class="fa fa-search"></i> <?php echo $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> <?php echo $this->translate("Pulisci Ricerca"); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Elenco Corse"); ?>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-trips-table">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate("Id Corsa"); ?></th>
                                <th><?php echo $this->translate("eMail"); ?></th>
                                <th><?php echo $this->translate("Cognome"); ?></th>
                                <th><?php echo $this->translate("Nome"); ?></th>
                                <th><?php echo $this->translate("Cellulare"); ?></th>
                                <th><?php echo $this->translate("RFID"); ?></th>
                                <th><?php echo $this->translate("Targa"); ?></th>
                                <th><?php echo $this->translate("Km Inizio"); ?></th>
                                <th><?php echo $this->translate("Km Fine"); ?></th>
                                <th style="min-width: 60px !important;"><?php echo $this->translate("Inizio"); ?></th>
                                <th style="min-width: 60px !important;"><?php echo $this->translate("Fine"); ?></th>
                                <th style="min-width: 80px !important;"><?php echo $this->translate("Durata"); ?></th>
                                <th><?php echo $this->translate("Sosta"); ?></th>
                                <th><?php echo $this->translate("Stato Quadro"); ?></th>
                                <th><?php echo $this->translate("In sosta"); ?></th>
                                <th><?php echo $this->translate("Pagabile"); ?></th>
                                <th><?php echo $this->translate("Pagata"); ?></th>
                                <th><?php echo $this->translate("Costo"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
