<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/trips.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            ELENCO CORSE <small>ricerca</small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- Seleziona --</option>
                                    <option value="id">Id</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="Filtra...">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn blue" id="js-search"><i class="fa fa-search"></i> Cerca</button>
                                <button type="button" class="btn blue dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear"><i class="fa fa-remove"></i> Pulisci Ricerca</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            Elenco Corse
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-trips-table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Utente</th>
                                <th>Targa</th>
                                <th>Card</th>
                                <th>Km</th>
                                <th>Prezzo &euro;</th>
                                <th>Indi. Inizio</th>
                                <th>Indi. Fine</th>
                                <th>Ora Inizio</th>
                                <th>Ora Fine</th>
                                <th>Pagabile</th>
                                <th>Durata Sosta</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
