<?php
// Get data
$trip = $this->trip;
$tripPayment = $trip->getTripPayment();
$customer = $trip->getCustomer();

// parse card
// must write something even if empty otherwise the box shrinks in height
$rfid = $customer->getCard() !== null ? $customer->getCard()->getCode() : 'n.a.';

// Parse payment
$payed = 'NO';
$invoiced = 'NO';

if ($tripPayment !== null) {
    $payed = $tripPayment->getPayedSuccessfullyAt() !== null ?
        $tripPayment->getPayedSuccessfullyAt()->format('d-m-Y H:i:s') :
        $payed;
    $invoiced = $tripPayment->getInvoice() !== null ?
        $tripPayment->getInvoicedAt()->format('d-m-Y H:i:s') .
            ' <a href=' .
            $this->url('pdf/invoices') . '/' .
            $tripPayment->getInvoice()->getId() .
            '><i class="fa fa-download"></i></a>' :
        $invoiced;

}

$beginning_trip = '';
if(!is_null($trip->getLatitudeBeginning()) && !is_null($trip->getLongitudeBeginning())){
    //$beginning_trip ='<a href="http://maps.google.com/?q='.$trip->getLatitudeBeginning().','.$trip->getLongitudeBeginning().'" target="_blank"> <i class="fa fa-map-marker"></i></a>';
    $beginning_trip ='<a href="http://www.openstreetmap.org/?mlat='.$trip->getLatitudeBeginning().'&mlon='.$trip->getLongitudeBeginning().'&zoom=16" target="_blank"> <i style="font-size: 20px" class="fa fa-map-marker"></i></a>';
}

$end_trip = '';
if(!is_null($trip->getLatitudeEnd()) && !is_null($trip->getLongitudeEnd())){
    //$end_trip ='<a href="http://maps.google.com/?q='.$trip->getLatitudeEnd().','.$trip->getLongitudeEnd().'" target="_blank"> <i class="fa fa-map-marker"></i></a>';
    $end_trip ='<a href="http://www.openstreetmap.org/?mlat='.$trip->getLatitudeEnd().'&mlon='.$trip->getLongitudeEnd().'&zoom=16" target="_blank"> <i style="font-size: 20px" class="fa fa-map-marker"></i></a>';
}

?>
<div class="row">
    <div class="col-lg-9">

        <?= $this->partial('partials/flash-messages.phtml', []); ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->translate("Dettagli Corsa"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label><?= $this->translate("Id corsa"); ?></label>
                            <div class="sng-info-box"><?= $trip->getId() ?></div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label><?= $this->translate("Nome"); ?></label>
                            <div class="sng-info-box"><?= $customer->getName() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label><?= $this->translate("Cognome"); ?></label>
                            <div class="sng-info-box"><?= $customer->getSurname() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label><?= $this->translate("Cellulare"); ?></label>
                            <div class="sng-info-box"><?= $customer->getMobile() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label><?= $this->translate("RFID cliente"); ?></label>
                            <div class="sng-info-box"><?= $rfid ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Targa"); ?></label>
                            <div class="sng-info-box"><?= $trip->getCar()->getPlate() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Numero auto"); ?></label>
                            <div class="sng-info-box"><?= $trip->getCar()->getLabel() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Stato quadro"); ?></label>
                            <div class="sng-info-box"><?= $trip->getCar()->getKeystatus() ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Sosta"); ?></label>
                            <div class="sng-info-box"><?= round($trip->getParkSeconds()/60)?> <?= $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("In sosta"); ?></label>
                            <div class="sng-info-box"><?= $trip->getCar()->getParking() ? $this->translate("SI") : $this->translate("NO") ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Indirizzo inizio"); ?></label>
                            <div class="sng-info-box"><?=$beginning_trip ?> <?= $trip->getAddressBeginning() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Indirizzo fine"); ?></label>
                            <div class="sng-info-box">
                                <?= $end_trip ?>
                                    <?= $trip->getAddressEnd() ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data inizio"); ?></label>
                            <div class="sng-info-box"><?= $trip->getTimestampBeginning()->format('d-m-Y H:i:s') ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Data fine"); ?></label>
                            <div class="sng-info-box"><?= (null != $trip->getTimestampEnd() ? $trip->getTimestampEnd()->format('d-m-Y H:i:s') : $this->translate('n.d.')) ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Durata"); ?></label>
                            <div class="sng-info-box"><?= $trip->getDurationMinutes() ?> <?= $this->translate("minuti"); ?></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Km inizio"); ?></label>
                            <div class="sng-info-box"><?= $trip->getKmBeginning() ?></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label><?= $this->translate("Km fine"); ?></label>
                            <div class="sng-info-box"><?= $trip->getKmEnd() ?></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">

            <div class="panel-heading"><?= $this->translate("Dati pagamento"); ?></div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Pagabile"); ?></label>
                            <div class="sng-info-box"><?= $trip->getPayable() ? $this->translate("SI") : $this->translate("NO") ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Pagata"); ?></label>
                            <div class="sng-info-box"><?= $payed ?></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label><?= $this->translate("Fatturata"); ?></label>
                            <div class="sng-info-box"><?= $invoiced ?></div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>
