<?php
    $form = $this->carsConfigurationsForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate('AGGIUNGI CONFIGURAZIONE AUTO') ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('cars'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate('Torna alla lista') ?></a>
            </div>
        </div>
        <div class="page-bar">
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="fleet"><?= $this->translate('Flotta') ?></label>
                            <?php
                                $fleet = $form->get('carsConfigurations')->get('fleet');
                                echo $this->formElement($fleet);
                                echo $this->formElementErrors($fleet, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="model"><?= $this->translate('Modello Auto') ?></label>
                            <?php
                                $model = $form->get('carsConfigurations')->get('model');
                                echo $this->formElement($model);
                                echo $this->formElementErrors($model, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="plate"><?= $this->translate('Targa Auto') ?></label>
                            <?php
                                $plate = $form->get('carsConfigurations')->get('plate');
                                echo $this->formElement($plate);
                                echo $this->formElementErrors($plate, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="key"><?= $this->translate('Tipo di Configurazione') ?></label>
                            <?php
                                $key = $form->get('carsConfigurations')->get('key');
                                echo $this->formElement($key);
                                echo $this->formElementErrors($key, array('class' => 'text-danger list-unstyled'));
                            ?>
                        </div>
                    </div>
                </div>
                <?php
                    $key = $form->get('carsConfigurations')->get('value');
                    echo $this->formElement($key);
                    echo $this->formElementErrors($key, array('class' => 'text-danger list-unstyled'));
                ?>
                <div class="row">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success"><?= $this->translate("Aggiungi Configurazione Auto e Inserisci i/il Valore"); ?></button>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>