<?php 
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');

// Get data
$configuration = $this->configuration;
$dtValues = $this->indexedValues;

?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title">
                    <?= $this->translate("DETTAGLI CONFIGURAZIONE"); ?>
                    <small>ID - <?= $this->thisId ?></small>
                </h3>
            </div>

            <div class="col-lg-6">
                <a href="<?= $this->url('cars-configurations/list/all'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="tab-info">
                        <div class="row">
                            <div class="col-lg-12">
                                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                                <!-- CONFIGURATION POSITION -->
                                <div class="portlet box green">
                                    <div class="portlet-title">
                                        <div class="caption">
                                            <?= $this->translate("Posizionamento"); ?>
                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Tipo Posizionamento"); ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $this->translate($configuration->getPriority()) ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Targa"); ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $configuration->getCarPlate() ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Flotta") ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $configuration->getFleetName() ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Modello Auto") ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $configuration->getModel() ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- CONFIGURATION RAW VALUE -->
                                <div class="portlet box green">
                                    <div class="portlet-title">
                                        <div class="caption">
                                            <?= $this->translate("Valore Grezzo"); ?>
                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Chiave"); ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $configuration->getKey() ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group">
                                                    <label>
                                                        <?= $this->translate("Valore Grezzo"); ?>
                                                    </label>
                                                    <div class="sng-info-box">
                                                        <?= $configuration->getValue() ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- CONFIGURATION VALUE -->
                                <div class="portlet box green">
                                    <div class="portlet-title">
                                        <div class="caption">
                                            <?= $this->translate("Valore Formattato"); ?>
                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <? if ($this->hasMultipleValues){ ?>
                                                        <table class="table table-striped table-bordered table-hover" id="js-cars-configurations-element-table">
                                                            <thead>
                                                                <tr>
                                                                    <?php
                                                                        foreach($dtValues[0] as $key => $val ){
                                                                            echo '<th>'.$this->translate($key).'</th>';
                                                                        }
                                                                    ?>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <?php
                                                                    foreach($dtValues as $row ){
                                                                        echo '<tr>';
                                                                        
                                                                        foreach($row as $value ){
                                                                            echo '<td>'.$this->translate($value).'</td>';
                                                                        }
                                                                        
                                                                        echo '</tr>';
                                                                    }
                                                                ?>
                                                            </tbody>
                                                        </table>
                                                    <? } else { ?>
                                                        <div class="sng-info-box">
                                                            <?= $this->formattedValue ?>
                                                        </div>
                                                    <? } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>

<script>
    var tab = '<?= $this->tab ?>';
</script>