<?php
    $this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
    $this->headScript()
        ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
        ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
        ->appendFile($this->basePath() .'/js/cars-configurations-edit.js');
    $form = $this->form->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?=$this->translate('MODIFICA CONFIGURAZIONE AUTO')?>: <?= $this->carConfiguration->getKey(); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('cars-configurations'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate('Torna alla lista') ?></a>
            </div>
        </div>
        <div class="page-bar">
        </div>
        <?php if ($this->hasMultipleValues){ ?>
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Lista Opzioni")?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-cars-configurations-element-table">
                            <thead>
                                <tr>
                                    <?php
                                        foreach($this->form->getElements() as $element ){
                                            echo '<th>'.$this->translate($element->getLabel()).'</th>';
                                        }
                                    ?>
                                    <th><?= 'Id' ?></th>
                                    <th><?= $this->translate('Azioni')?></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <?php } ?>
          <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Modifica Configurazione")?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <?php
                            echo $this->partial('partials/flash-messages.phtml', []);
                            echo $this->form()->openTag($form); 

                            $elements = $this->form->getElements();
                            foreach($elements as $element) {
                        ?>
                        <div>
                            <div class="form-group">
                                <?= $this->formRow($element) ?>
                            </div>
                        </div>
                        <?php } ?>
                            <div>
                                <button type="submit" class="btn btn-success"><?= $this->hasMultipleValues ? $this->translate('Modifica Opzione Configurazione Auto') : $this->translate('Modifica Configurazione Auto') ?></button>
                            </div>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                    <div id="data-processing" class="dataTables_processing" style="display: none;position: fixed;top: 50%;left: 50%;min-width: 125px;margin-left: 0;padding: 7px;text-align: center; color: #333; font-size: 13px; border: 1px solid #ddd; background-color: #eee; vertical-align: middle; -webkit-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.1); -moz-box-shadow: 0 1px 8px rgba(0, 0, 0, 0.1); box-shadow: 0 1px 8px rgba(0, 0, 0, 0.1);"><?= $this->translate("Elaborazione in corso...") ?></div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if ($this->hasMultipleValues){ ?>
    <script>
        var dataValues = <?=json_encode($this->indexedValues)?>;
        var thisId = <?= $this->thisId ?>;
        renderDatatable(dataValues);
    </script>
<?php } ?>