<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            Dashboard <small>ricerca</small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
