<div class="row">
    <div class="col-lg-12">

        <div class="alert alert-success" style="display: none;" id="js-message">
            <p>Operazione eseguita con successo</p>
        </div>

        <div class="row">
            <div class="col-md-12">

                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                <!-- Input container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i>Nuova nota
                        </div>
                    </div>
                    <form class="portlet-body"
                        action="<?= $this->url('customers/add-note', ['id' => $this->customer->getId()]); ?>"
                        method="post">

                        <textarea id="new-note" name="new-note" style="width: 100%" rows="5"></textarea><br><br>
                        <input id="add-button"
                            class="btn btn-default btn-xs"
                            type="submit"
                            value="Aggiungi">
                        </input>

                    </form>
                </div>
                <!-- input container -->

                <!-- Table container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-paperclip"></i>Elenco Note
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table id="notes-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Data</th>
                                    <th>Id Utente</th>
                                    <th>Nota</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->notes as $note): ?>
                                <tr>
                                    <td class="sng-date-column"><?= $note->getInsertedTs()->format('d-m-Y H:i:s'); ?></td>
                                    <td><?= $note->getWebuser()->getId() ?> - <?= $note->getWebuser()->getDisplayName() ?></td>
                                    <td><?= $note->getNote(); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- table -->

                    </div>
                </div>
                <!-- table container -->

            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?= $this->basePath() .'/js/customer-notes.js'; ?>"></script>
