<!doctype html>
<html ng-app="SharengoCsApp">
<head>
    <meta charset="UTF-8">
    <?php  echo $this->headLink()
            ->appendStylesheet($this->basePath() . '/assets-modules/alarms/css/vendors.css')
            ->appendStylesheet($this->basePath() . '/assets-modules/alarms/css/style.css');
    ?>
    <?php 
        echo $this->headScript()
            ->appendFile($this->basePath() . '/assets-modules/alarms/js/vendors.js')
            ->appendFile($this->basePath() . '/assets-modules/alarms/js/scripts.js');
    ?>
</head>
<body ng-controller="SharengoCsController">

<div id="map-loader" ng-show="mapLoader">
    <p><i class="fa fa-refresh"></i></p>
    Caricamento mappa in corso...
</div>
  
<div id="top-area">
    <tabset>
        <tab heading="Auto">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-input">
                         <div class="input-group">
                            <input type="text" class="form-control" ng-model="search.plate" placeholder="Targa">
                            <span class="input-group-btn">
                                <button class="btn btn-green" ng-click="plateChange(search.plate, false)" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-input">
                        <div class="input-group">
                            <input type="text" class="form-control" ng-model="search.label" placeholder="N°.Unità">
                            <span class="input-group-btn">
                                <button class="btn btn-green" ng-click="plateChange(search.label, true)" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-warning" style="margin-top: 10px;" ng-show="accordionStatus.showNoResult"  role="alert">
                        <i class="fa fa-exclamation-circle"></i> Nessun risultato trovato, riprova con {{noResult}}.
                    </div>
                </div>
            </div>

        </tab>
        <tab heading="Indirizzo">

            <div class="row">
                <div class="col-md-9">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.address" class="form-control" placeholder="Indirizzo">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.number" class="form-control" placeholder="Civico">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-input">
                        <input type="text" ng-model="searchAddress.city" class="form-control" placeholder="Città">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-input">
                        <button class="btn btn-green btn-block" ng-click="searchAddress.search()">
                        <i class="fa fa-search"></i> Cerca</button>
                    </div>
                </div>
            </div>

        </tab>
    </tabset>
</div>
<div id="top-actions">
    <div class="heading clearfix">
        <div class="fleets">
            <select 
                class="form-control"
                ng-change="changeFleet()"
                ng-model="defaultFleet"
                ng-options="fleet as fleet.name for fleet in fleets">
                <option>--</option>
            </select>
        </div>
        <div class="pull-right actions">
            <a href="javascript:;" ng-click="loadCars()" class="btn btn-success btn-xs">
                <i class="fa fa-refresh"></i> Agggiorna
            </a>
            <a href="/user/logout" class="btn btn-danger btn-xs">
                <i class="fa fa-sign-out"></i> Esci
            </a>
        </div>
    </div>
</div>

<div id="controls" ng-hide="accordionStatus.hideCustomerSelect && accordionStatus.hideCarsSelect && accordionStatus.hideCustomerData && accordionStatus.hideCarData && accordionStatus.hideLastTripData">
    <accordion close-others="false">
        <accordion-group heading="Seleziona cliente" ng-hide="accordionStatus.hideCustomerSelect" is-open="accordionStatus.customerSelectOpen">
            <table>
                <thead>
                <tr>
                    <th>Seleziona</th>
                    <th>Nome</th>
                    <th>Cognome</th>
                    <th>Telefono</th>
                    <th>C.F.</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="customer in customers">
                    <td><button type="button" class="btn btn-default btn-xs" ng-click="selectCustomer(customer)"><i class="fa fa-info"></i> Seleziona</button></td>
                    <td>{{customer.name | lowercase}}</td>
                    <td>{{customer.surname | lowercase}}</td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.tax_code}}</td>
                </tr>
                </tbody>
            </table>
        </accordion-group>
        <accordion-group class="resultsCars" heading="Veicoli trovati" ng-hide="accordionStatus.hideCarsSelect" is-open="accordionStatus.carsSelectOpen">
            <table>
                <thead>
                <tr>
                    <th>Seleziona</th>
                    <th>Targa</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="car in carsFound">
                    <td><button type="button" class="btn btn-default btn-xs" ng-click="plateChange(car.plate,false)"><i class="fa fa-info"></i> Seleziona</button></td>
                    <td>{{car.plate | uppercase}}</td>
                </tbody>
            </table>
        </accordion-group>        
        <accordion-group heading="Dati cliente" id="customerData" ng-hide="accordionStatus.hideCustomerData" is-open="accordionStatus.customerDataOpen" class="acc-user-data">
            <div class="row">
                <div class="col-md-3">
                    <label>Nome</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.name}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Cognome</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.surname}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Cellulare</label>
                </div>

                <div class="col-md-9">
                    <span>{{customer.mobile}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Abilitato</label>
                </div>

                <div class="col-md-9">
                    <span ng-if="customer.enabled" class="ball active"></span>
                    <span ng-if="!customer.enabled" class="ball inactive"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-3 noPaddingRight">
                    <label>Ultime corse</label>
                </div>

                <div class="col-md-9" style="font-size: 12px;">
                    <span ng-repeat="trip in customer.lastTrips">
                        <strong>Targa:</strong> {{trip.car.plate}} <strong>Inizio:</strong> {{trip.beginningTx.date | dateSharengoFormat:'DD-MM-YYYY'}} 
                        <button tooltip-placement="left" tooltip-html-unsafe="<b>Inizio:</b> {{trip.timestampBeginning.date | dateSharengoFormat}} <br /><b>Fine:</b> {{trip.timestampEnd.date | dateSharengoFormat}}" class="btn btn-default btn-xs">
                            <i class="fa fa-info-circle"></i>
                        </button>
                        <br>
                    </span>
                </div>
            </div>
        </accordion-group>
        <accordion-group heading="Dati auto" ng-hide="accordionStatus.hideCarData" is-open="accordionStatus.carDataOpen" class="acc-car-data">
            <div class="row">
                <div class="col-md-3">
                    <label>Targa</label>
                </div>

                <div class="col-md-9">
                    <span>{{car.plate}}</span>
                </div>
            </div>

            <div class="row">
               <div class="col-md-3">
                    <label>N° Unità</label>
                </div> 

                <div class="col-md-9">
                    <span>{{car.label}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Posizione</label>
                </div>

                <div class="col-md-9" style="font-size: 12px;">
                    <span>Lat: {{car.latitude}}</span><br />
                    <span>Lon: {{car.longitude}}</span><br />
                    <span><reverse-geocode lat="car.latitude" lng="car.longitude"></reverse-geocode></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Batteria</label>
                </div>

                <div class="col-md-9">
                    <span>{{car.battery}} % <i ng-if="car.charging" class="fa fa-plug"></i></span>
                </div>
            </div>

        </accordion-group>

        <accordion-group heading="Dati ultima corsa chiusa" ng-hide="accordionStatus.hideLastTripData" is-open="accordionStatus.lastTripDataOpen" class="acc-run-data">

            <div class="row">
                <div class="col-md-3">
                    <label>Inizio corsa</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTrip.timestampBeginning.date | dateSharengoFormat}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Fine corsa</label>
                </div>

                <div class="col-md-9" ng-if="lastTrip.timestampEnd.date">
                    <span>{{lastTrip.timestampEnd.date | dateSharengoFormat}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Cliente</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.surname}} {{lastTripUser.name}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Telefono</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.phone}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Cellulare</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTripUser.mobile}}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label>Eventi</label>
                </div>

                <div class="col-md-9">
                    <span>{{lastTrip.events}}</span>
                </div>
            </div>
        </accordion-group>
</div>
<div id="markers-control">
    <div class="pull-right actions">
        <a href="javascript:;" ng-click="poisVisible = !poisVisible;" class="btn btn-xs" ng-class="{'deactive': !poisVisible }">
            <i class="fa fa-plug"></i> &nbsp; POIS
        </a>
    </div>
</div>

<div id="left-area">
    <div class="pull-left">
        <ul class="list-inline">
            <li ng-click="markerFilters['libere'] = !markerFilters['libere'];" ng-class="{'active': markerFilters['libere']}" ><span class="block" style="background-color:{{markerColors['green']}}"></span> LIBERE</li>
            <li  ng-click="markerFilters['prenotate'] = !markerFilters['prenotate'];" ng-class="{'active': markerFilters['prenotate']}"><span class="block" style="background-color:{{markerColors['black']}}"></span> PRENOTATE</li>
            <li  ng-click="markerFilters['inuso'] = !markerFilters['inuso'];" ng-class="{'active': markerFilters['inuso']}"><span class="block" style="background-color:{{markerColors['yellow']}}"></span> IN USO</li>
            <li  ng-click="markerFilters['manut'] = !markerFilters['manut'];" ng-class="{'active': markerFilters['manut']}"><span class="block" style="background-color:{{markerColors['red']}}"></span> IN MANUTENZIONE</li> 
            <li  ng-click="markerFilters['h24'] = !markerFilters['h24'];" ng-class="{'active': markerFilters['h24']}"><span class="block" style="background-color:{{markerColors['azzure']}}"></span> +24hh</li>
            <li  ng-click="markerFilters['no3g'] = !markerFilters['no3g'];" ng-class="{'active': markerFilters['no3g']}"><span class="block" style="background-color:{{markerColors['brown']}}"><small class="text-label">3G</small></span> N.O. 3G</li>
            <li  ng-click="markerFilters['nobatt'] = !markerFilters['nobatt'];" ng-class="{'active': markerFilters['nobatt']}"><span class="block" style="background-color:{{markerColors['brown']}}"><i class="fa fa-battery-half"></i></span> N.O. Batt</li>
            <li  ng-click="markerFilters['nogps'] = !markerFilters['nogps'];" ng-class="{'active': markerFilters['nogps']}"><span class="block" style="background-color:{{markerColors['brown']}}"><small class="text-label">GPS</small></span> N.O. GPS</li>
            <li  ng-click="markerFilters['sporche'] = !markerFilters['sporche'];" ng-class="{'active': markerFilters['sporche']}"><span class="block" style="background-color:{{markerColors['purple']}}"></span> Sporca</li>
        </ul>
    </div>
</div>

<ui-gmap-google-map center="mapOptions.center" zoom="mapOptions.zoom" events="mapEvents" control="mapOptions.control">
    <ui-gmap-markers models="cars" coords="'self'" icon="'carIcon'" events="markerEvents" options="'options'" doRebuildAll="true" modelsbyref="true"></ui-gmap-markers>
    <ui-gmap-markers ng-if="poisVisible" models="pois" coords="'self'" icon="'poiIcon'" options="'options'"></ui-gmap-markers>
    <ui-gmap-polygon
        static="true"
        ng-repeat="p in polygons track by p.id"
        path="p.path"
        stroke="p.stroke"
        visible="p.visible"
        geodesic="p.geodesic"
        fill="p.fill"
        fit="false"
        editable="p.editable"
        draggable="p.draggable"></ui-gmap-polygon>
</ui-gmap-google-map>
</body>
</html>
