<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

$serverInstance = $this->ConfigHelper()->getServerInstance();

//fix per risolvere la mancata traduzione dentro ZfcUser
$as_errorsIdentity = array();
$login_error = false;
if ($form->get('identity') instanceof Zend\Form\Element &&
    count($form->get('identity')->getMessages())>0 ) {
    $as_errorsIdentity = array("Nome utente o password errati");
    $login_error = true;
}
//sso hack
if(strpos($_SERVER['HTTP_HOST'], 'sharengo.it') !== false){
    if(!isset($_GET["old"])) {
        if($login_error){
            header('Location: https://sso.sharengo.it/error.php?portal=admin');
            exit;
        }
        header('Location: https://sso.sharengo.it/log365.php?portal=admin&direct=true');
        exit;
    }
}

$as_errors = array_merge($as_errorsIdentity,
    $form->get('credential')->getMessages());
?>

<h3 class="form-title">Share'nGo</h3>

<?php if (count($as_errors) > 0) { ?>
    <div class="alert alert-danger">
        <?php echo implode(', ', $as_errors); ?>
    </div>
<?php } ?>

<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
    <label class="control-label visible-ie8 visible-ie9">Username</label>
    <?php echo $this->formInput($form->get('identity')->setAttributes(array('class'=>'form-control form-control-solid placeholder-no-fix', 'placeholder' => 'Nome utente')));?>
</div>

<div class="form-group">
    <label class="control-label visible-ie8 visible-ie9">Password</label>
    <?php echo $this->formInput($form->get('credential')->setAttributes(array('class'=>'form-control form-control-solid placeholder-no-fix', 'placeholder' => 'Password'))); ?>
</div>

<div class="form-actions">
    <?php echo $this->formButton($form->get('submit')->setAttributes(array('class'=>'btn btn-success uppercase palette-change login-button'))->setLabel('Login'));?>
</div>


<?php

if(!isset($serverInstance) || $serverInstance == "it_IT" || $serverInstance == "") {
    echo '<div style="text-align:center ">';
    //echo '<hr style= "border-top: 1px solid #999">';
    echo '<a href="https://sso.sharengo.it/log365.php?portal=admin&direct=true"><img src="/img/login365.png"></a>';
    echo '</div>';
}

echo $this->form()->closeTag()

?>
